/* GMAT Prep — fast routes and takeaways for the third block of the official
   Reading Comprehension passages. No `steps`: the transcribed explanations
   already point to the supporting text and dispose of every wrong option, so
   they are kept as the full solution. Added here is the ⚡ fast route and the
   transferable reading rule.
   Keys are "setId#n"; index.html merges these over the question files. */
window.GMAT_EXPL = Object.assign(window.GMAT_EXPL || {}, {

"rc-ss-mooncore#1": {
  fast: "Follow the chain in paragraph 2: radio-signal shifts → velocity changes → gravitational inconsistencies → a gravity map → lunar mass concentrations → the core's size and composition.\n" +
    "The map is one link in that chain. Prephrase \"a step in working out the Moon's mass\" and take it. It is the magnetic data that [[confirmed]] the map, not the other way round.",
  take: "When a paragraph describes a method as a sequence, a function question asks which link the detail is. Trace the chain and read off its position."
},

"rc-ss-mooncore#2": {
  fast: "The passage says the observed variations were \"minute, relatively rapid\" and that they resulted from [[inconsistency]] in the Moon's gravitational pull.\n" +
    "Slow oscillation instead of rapid variation means less inconsistency. Prephrase \"the gravity would seem more uniform\" and take it. Nothing about core size follows directly, since that came through a whole further chain of inference.",
  take: "Hypothetical-change questions turn on the direct link. Change the reading, change the immediately measured quantity — and stop there."
},

"rc-ss-mooncore#3": {
  fast: "Straight retrieval: the second data set came from \"the faint magnetic field generated by electrical currents within the lunar core caused by the Moon's monthly passage through the Earth's magnetosphere\".\n" +
    "Take the option that restates the cause. Options reversing the roles of the electric and magnetic field, or having the currents question the radio results, contradict a passage that says the two agreed.",
  take: "Long causal sentences are detail-question mines. Break them into cause and effect before reading the options."
},

"rc-ss-mooncore#4": {
  fast: "Two methods: radio-signal wavelength changes as the craft moved towards or away from Earth, and magnetic echoes. The question asks what one method [[measured]].\n" +
    "Prephrase \"wavelength changes as its position relative to Earth changed\" and take it. Gravitational pull is what the measurement revealed, not what was measured.",
  take: "Distinguish the measured quantity from the quantity inferred from it. Detail options often swap the instrument reading for the conclusion."
},

"rc-ss-mooncore#5": {
  fast: "The numbers are all in paragraph 1: Earth's core is 55 percent of radius and 32 percent of mass; the Moon's is 20 percent and 2 percent.\n" +
    "Prephrase \"the Earth's core is a bigger share on both counts\" and take it. Everything else in the option list is speculation about origins that the passage leaves open.",
  take: "When a passage supplies two pairs of percentages, expect an inference that simply compares them. Read the numbers off rather than reasoning."
},

"rc-ss-bilingual#1": {
  fast: "Paragraph 2 contrasts the traditional pattern with the Spanish-speaking \"revolving door\" of moving back and forth between communities.\n" +
    "Prephrase \"traditionally, immigrants didn't move back and forth\" and take it. Discrimination is described as consistent across groups, so the option about it inverts the passage.",
  take: "A stated departure from a pattern tells you what the pattern was. Read the contrast backwards to get the traditional case."
},

"rc-ss-bilingual#2": {
  fast: "Paragraph 4 says the issue \"has, nevertheless, served to unite the leadership of the nation's Hispanic communities\".\n" +
    "Prephrase \"it gave the leadership a common cause\" and take it. The option about polarising them says the opposite of the sentence in front of you.",
  take: "\"Nevertheless\" marks the sentence the author wants noticed. Effects questions are usually answered by exactly that sentence."
},

"rc-ss-bilingual#3": {
  fast: "The phrase is glossed in its own sentence: agendas ranging \"from absorption at one pole to separatism at the other\".\n" +
    "Prephrase \"how far Hispanics should blend into the wider society\" and take it. That is the axis the two poles define; options about methods or officials name a different dispute.",
  take: "When a passage names the endpoints of a spectrum, the phrase in question refers to the dimension those endpoints measure."
},

"rc-ss-bilingual#4": {
  fast: "The reason is stated in paragraph 5: \"given the present state of understanding about the effects of bilingual education on learning, it would be unwise\".\n" +
    "Prephrase \"we don't yet know whether it would help or hurt\" and take it. Paragraph 4 explicitly calls the learning debates inconclusive, which rules out options asserting proven benefits.",
  take: "An argument from ignorance — \"we don't know yet\" — is a distinct reason. Do not upgrade it into a claim that the evidence points one way."
},

"rc-ss-bilingual#5": {
  fast: "Paragraph 5 opens \"More direct efforts to force inclusion can be misguided\" and then lists objections: alienation, unnecessary, unwise, and a matter for parents.\n" +
    "Prephrase \"reasons against forcing inclusion\" and take it. The option offering virtues [[and]] limitations is wrong because the paragraph offers no virtues at all.",
  take: "Count the sides a paragraph presents. A one-sided list of objections cannot be described as weighing pros and cons."
},

"rc-ss-dallasdiet#1": {
  fast: "The passage calls the mounds \"earthen mounds that served as substructures for buildings important to civic and religious affairs\".\n" +
    "Prephrase \"they were the base of important buildings\" and take it. Some burials were in them, but that is not what they served as — the option calling them primarily burial grounds swaps a use for the function.",
  take: "Match the passage's own \"served as\" phrase. A secondary use mentioned nearby is not the stated function."
},

"rc-ss-dallasdiet#2": {
  fast: "Paragraph 2 opens \"While it is possible that taller people were simply more successful… it is more likely that…\".\n" +
    "That is a rival explanation raised and then set aside. Prephrase \"heading off an objection\" and take it. The word \"more likely\" rules out the option calling the two equally plausible.",
  take: "\"While it is possible that X… it is more likely that Y\" is a concession structure. Its function is to anticipate and answer the objection, not to endorse it."
},

"rc-ss-dallasdiet#3": {
  fast: "The word to hunt for is \"first\". The passage says \"The first real clue came when archaeologists discovered that skeletons of higher-status individuals tended to be several centimeters taller\".\n" +
    "Prephrase \"the height difference between groups\" and take it. Trace elements came later in the investigation, so that option gets the order wrong.",
  take: "\"Initially recognised\" questions are answered by the passage's own words — first, initially, the first clue. Order matters more than content."
},

"rc-ss-dallasdiet#4": {
  fast: "Translate the chemistry: very low vanadium indicates meat, and vanadium was found in \"considerably greater quantities\" in lower-status burials.\n" +
    "So lower-status people ate less meat and more plants. Prephrase \"game was less available to them than plants\" and take it. Options claiming a well-balanced diet or a purely local food supply are unsupported.",
  take: "Turn a marker into the thing it marks before comparing groups. High marker of scarcity means low quantity of the resource."
}

});
