/* GMAT Prep — additional practice questions that EXPAND existing sets.
   Merged into the matching window.GMAT_SETS entry at load time (see index.html):
   each question is appended to the set with id === setId, and its `n` is
   assigned automatically. Same question shape as sets.js:
     { topic, correct:"A".., options, text, choices[], hint, expl, level }
   Quant / Data-Insights answer keys here are compute-verified (verify script). */
(function () {
  var DS = ["(1) ALONE sufficient, (2) alone not","(2) ALONE sufficient, (1) alone not","BOTH together sufficient, neither alone","EACH alone sufficient","Together still NOT sufficient"];

  window.GMAT_SETS_EXTRA = [

  /* ---------------- QUANT ---------------- */
  { setId:"quant-percentage-ex", add:[
    { topic:"Percentages & percent change", level:"easy", correct:"B", options:5,
      text:"A shirt's price is first increased by 25% and then the new price is decreased by 20%. Compared with the original price, the final price is:",
      choices:["5% lower","the same","5% higher","4% higher","10% higher"],
      hint:"Chain the factors: 1.25 then 0.80.",
      expl:"Final factor \\(=1.25\\times0.80=1.00\\), so the price returns to its original value — no net change.\nAnswer: B." },
    { topic:"Percentages & percent change", level:"easy", correct:"C", options:5,
      text:"If 40% of a number is 240, what is 75% of the same number?",
      choices:["360","420","450","480","180"],
      hint:"Find the whole first.",
      expl:"\\(0.40N=240\\Rightarrow N=600\\). Then \\(0.75\\times600=450\\).\nAnswer: C." },
    { topic:"Percentages & percent change", level:"medium", correct:"B", options:5,
      text:"In a class, 60% of the students are boys. If 20% of the boys and 40% of the girls wear glasses, what percent of the whole class wears glasses?",
      choices:["24%","28%","30%","32%","20%"],
      hint:"Weight each group by its share of the class.",
      expl:"Boys: \\(0.60\\times0.20=0.12\\). Girls: \\(0.40\\times0.40=0.16\\). Total \\(=0.28=28\\%\\).\nAnswer: B." },
    { topic:"Percentages & percent change", level:"medium", correct:"A", options:5,
      text:"The price of sugar rises by 25%. By what percent must a family reduce its consumption so that its total spending on sugar stays the same?",
      choices:["20%","25%","15%","33⅓%","30%"],
      hint:"Spending = price × quantity; keep the product fixed.",
      expl:"To offset a factor of \\(1.25\\), consumption must be multiplied by \\(1/1.25=0.8\\), a reduction of \\(20\\%\\). (In general a \\(+x\\%\\) price needs a \\(\\frac{x}{100+x}\\) cut.)\nAnswer: A." },
    { topic:"Percentages & percent change", level:"medium", correct:"B", options:5,
      text:"A town's population grew by 20% in 2023 and by a further 25% in 2024. Over the two years combined, the population increased by:",
      choices:["45%","50%","55%","22.5%","60%"],
      hint:"Multiply the growth factors, don't add the percents.",
      expl:"\\(1.20\\times1.25=1.50\\), a \\(50\\%\\) increase overall.\nAnswer: B." }
  ]},

  { setId:"quant-ratio-ex", add:[
    { topic:"Ratios & proportions", level:"medium", correct:"A", options:5,
      text:"If \\(a:b = 2:3\\) and \\(b:c = 4:5\\), then \\(a:c\\) equals:",
      choices:["8 : 15","2 : 5","4 : 5","10 : 15","3 : 5"],
      hint:"Make b the same in both ratios.",
      expl:"Scale to a common b: \\(a:b=8:12\\) and \\(b:c=12:15\\), so \\(a:c=8:15\\).\nAnswer: A." },
    { topic:"Ratios & proportions", level:"easy", correct:"C", options:5,
      text:"$720 is divided among A, B and C in the ratio 2 : 3 : 4. C's share is:",
      choices:["$160","$240","$320","$360","$280"],
      hint:"Total parts = 2+3+4.",
      expl:"9 parts \\(=\\$720\\Rightarrow\\) one part \\(=\\$80\\). C gets \\(4\\times80=\\$320\\).\nAnswer: C." },
    { topic:"Ratios & proportions", level:"medium", correct:"A", options:5,
      text:"Two numbers are in the ratio 5 : 8. When 9 is added to each, the ratio becomes 8 : 11. The smaller number is:",
      choices:["15","20","24","18","12"],
      hint:"Let the numbers be 5k and 8k and cross-multiply.",
      expl:"\\(\\frac{5k+9}{8k+9}=\\frac{8}{11}\\Rightarrow 11(5k+9)=8(8k+9)\\Rightarrow 55k+99=64k+72\\Rightarrow 9k=27,\\ k=3\\). Smaller \\(=5k=15\\).\nAnswer: A." },
    { topic:"Ratios & proportions", level:"medium", correct:"B", options:5,
      text:"A 60-litre mixture contains milk and water in the ratio 2 : 1. How much water must be added to make the ratio 1 : 1?",
      choices:["10 L","20 L","30 L","15 L","40 L"],
      hint:"The amount of milk doesn't change.",
      expl:"Milk \\(=40\\) L, water \\(=20\\) L. For 1 : 1 we need water \\(=40\\) L, so add \\(40-20=20\\) L.\nAnswer: B." },
    { topic:"Ratios & proportions", level:"easy", correct:"A", options:5,
      text:"If \\(\\dfrac{x}{3}=\\dfrac{y}{4}=\\dfrac{z}{7}\\), then \\(\\dfrac{x+y+z}{z}\\) equals:",
      choices:["2","\\(\\tfrac72\\)","14","1","7"],
      hint:"Let the common value be k.",
      expl:"\\(x=3k,\\ y=4k,\\ z=7k\\Rightarrow \\frac{x+y+z}{z}=\\frac{14k}{7k}=2\\).\nAnswer: A." }
  ]},

  { setId:"quant-interest-ex", add:[
    { topic:"Simple & compound interest", level:"easy", correct:"B", options:5,
      text:"Find the simple interest on $2,000 at 5% per annum for 3 years.",
      choices:["$250","$300","$315","$330","$350"],
      hint:"SI = P·r·t.",
      expl:"\\(2000\\times0.05\\times3=\\$300\\).\nAnswer: B." },
    { topic:"Simple & compound interest", level:"medium", correct:"B", options:5,
      text:"A sum of money doubles itself in 8 years at simple interest. In how many years will it triple?",
      choices:["12","16","20","24","8"],
      hint:"Under SI the interest is a fixed amount per year.",
      expl:"Doubling means the interest earned equals the principal in 8 years. Tripling needs interest equal to twice the principal, i.e. \\(2\\times8=16\\) years.\nAnswer: B." },
    { topic:"Simple & compound interest", level:"easy", correct:"B", options:5,
      text:"What is the compound interest on $10,000 at 10% per annum, compounded annually, for 2 years?",
      choices:["$2,000","$2,100","$2,200","$1,100","$1,000"],
      hint:"Amount = P(1+r)^t, then subtract P.",
      expl:"\\(10000\\times1.1^2=12100\\); interest \\(=12100-10000=\\$2100\\).\nAnswer: B." },
    { topic:"Simple & compound interest", level:"medium", correct:"A", options:5,
      text:"The difference between the compound interest and the simple interest on a certain sum for 2 years at 10% per annum is $50. The sum is:",
      choices:["$5,000","$2,500","$10,000","$4,000","$2,000"],
      hint:"For 2 years the difference equals P·r².",
      expl:"Difference \\(=P\\left(\\frac{r}{100}\\right)^2=P(0.1)^2=0.01P=50\\Rightarrow P=\\$5000\\).\nAnswer: A." }
  ]},

  { setId:"quant-speed-ex", add:[
    { topic:"Speed, distance & time", level:"easy", correct:"B", options:5,
      text:"A car covers 150 km in 2 hours 30 minutes. Its average speed is:",
      choices:["55 km/h","60 km/h","62.5 km/h","75 km/h","50 km/h"],
      hint:"Convert the time to hours.",
      expl:"\\(2\\text{h }30\\text{m}=2.5\\) h; speed \\(=150/2.5=60\\) km/h.\nAnswer: B." },
    { topic:"Speed, distance & time", level:"medium", correct:"C", options:5,
      text:"A train 120 m long passes a stationary pole in 6 seconds. The train's speed is:",
      choices:["60 km/h","66 km/h","72 km/h","20 km/h","80 km/h"],
      hint:"To pass a pole, the train travels its own length.",
      expl:"Speed \\(=120/6=20\\) m/s \\(=20\\times\\frac{18}{5}=72\\) km/h.\nAnswer: C." },
    { topic:"Speed, distance & time", level:"medium", correct:"C", options:5,
      text:"Two trains, 100 m and 120 m long, run toward each other on parallel tracks at 40 km/h and 32 km/h. How long do they take to completely pass each other?",
      choices:["9 s","10 s","11 s","12 s","8 s"],
      hint:"Add the speeds (opposite directions) and the lengths.",
      expl:"Relative speed \\(=72\\) km/h \\(=20\\) m/s; combined length \\(=220\\) m; time \\(=220/20=11\\) s.\nAnswer: C." },
    { topic:"Speed, distance & time", level:"medium", correct:"B", options:5,
      text:"A boat travels 12 km downstream in 2 hours and returns the same 12 km upstream in 3 hours. The speed of the boat in still water is:",
      choices:["4 km/h","5 km/h","6 km/h","10 km/h","1 km/h"],
      hint:"Still-water speed is the average of downstream and upstream speeds.",
      expl:"Downstream \\(=6\\) km/h, upstream \\(=4\\) km/h; still water \\(=(6+4)/2=5\\) km/h.\nAnswer: B." },
    { topic:"Speed, distance & time", level:"medium", correct:"C", options:5,
      text:"Walking at \\(\\tfrac34\\) of his usual speed, a man reaches his office 20 minutes late. His usual travel time (in minutes) is:",
      choices:["40","45","60","80","90"],
      hint:"Speed and time are inversely proportional over a fixed distance.",
      expl:"At \\(\\frac34\\) speed the time is \\(\\frac43\\) of usual, i.e. \\(\\frac13\\) longer. That extra \\(\\frac13 T=20\\Rightarrow T=60\\) min.\nAnswer: C." }
  ]},

  { setId:"quant-timework-ex", add:[
    { topic:"Work & rate", level:"medium", correct:"B", options:5,
      text:"A can finish a job in 12 days and B in 18 days. Working together, they finish it in:",
      choices:["6 days","7.2 days","9 days","15 days","30 days"],
      hint:"Add the rates.",
      expl:"Combined rate \\(=\\frac1{12}+\\frac1{18}=\\frac{3+2}{36}=\\frac5{36}\\) per day, so time \\(=\\frac{36}{5}=7.2\\) days.\nAnswer: B." },
    { topic:"Work & rate", level:"easy", correct:"B", options:5,
      text:"15 workers build a wall in 8 days. Working at the same rate, how many days would 10 workers take?",
      choices:["10 days","12 days","5⅓ days","16 days","20 days"],
      hint:"Total work in worker-days is constant.",
      expl:"Work \\(=15\\times8=120\\) worker-days; with 10 workers, \\(120/10=12\\) days.\nAnswer: B." },
    { topic:"Work & rate", level:"medium", correct:"C", options:5,
      text:"A works twice as fast as B. Together they complete a task in 8 days. B working alone would take:",
      choices:["12 days","16 days","24 days","36 days","48 days"],
      hint:"Let B's rate be r; A's is 2r.",
      expl:"Combined rate \\(=3r=\\frac18\\Rightarrow r=\\frac1{24}\\), so B alone needs 24 days.\nAnswer: C." },
    { topic:"Work & rate", level:"medium", correct:"C", options:5,
      text:"An inlet pipe can fill a tank in 6 hours; an outlet pipe can empty the full tank in 9 hours. If both are open on an empty tank, the tank fills in:",
      choices:["12 hours","15 hours","18 hours","3.6 hours","9 hours"],
      hint:"Net rate = fill rate − drain rate.",
      expl:"Net rate \\(=\\frac16-\\frac19=\\frac{3-2}{18}=\\frac1{18}\\) per hour, so 18 hours.\nAnswer: C." }
  ]},

  { setId:"quant-average-ex", add:[
    { topic:"Weighted averages", level:"easy", correct:"B", options:5,
      text:"The average of 5 numbers is 27. If the number 35 is removed, the average of the remaining four numbers is:",
      choices:["24","25","26","23","27"],
      hint:"Work with the total sum.",
      expl:"Sum \\(=5\\times27=135\\); after removing 35, sum \\(=100\\), average \\(=100/4=25\\).\nAnswer: B." },
    { topic:"Weighted averages", level:"medium", correct:"C", options:5,
      text:"The average age of 30 students is 12 years. When the teacher's age is included, the average rises to 13 years. The teacher's age is:",
      choices:["40","42","43","45","44"],
      hint:"Compare the two totals.",
      expl:"Students' total \\(=360\\). With teacher: \\(13\\times31=403\\). Teacher \\(=403-360=43\\).\nAnswer: C." },
    { topic:"Weighted averages", level:"medium", correct:"C", options:5,
      text:"A batsman's average after 10 innings is 40. What must he score in his 11th innings to raise his average to 42?",
      choices:["52","60","62","64","42"],
      hint:"Target total minus current total.",
      expl:"Needed total \\(=42\\times11=462\\); current \\(=400\\); required score \\(=62\\).\nAnswer: C." },
    { topic:"Weighted averages", level:"medium", correct:"B", options:5,
      text:"What is the average of the first 20 positive even integers (2, 4, …, 40)?",
      choices:["20","21","22","19","40"],
      hint:"For an evenly spaced list, average = (first + last)/2.",
      expl:"\\((2+40)/2=21\\).\nAnswer: B." }
  ]},

  { setId:"quant-statistics-ex", add:[
    { topic:"Mean, median & mode", level:"easy", correct:"B", options:5,
      text:"The mean of the five numbers 2, 5, 7, x, 10 is 6. The value of x is:",
      choices:["4","6","8","12","5"],
      hint:"Sum of the five = 5 × mean.",
      expl:"Sum \\(=30\\); the known four sum to 24, so \\(x=6\\).\nAnswer: B." },
    { topic:"Mean, median & mode", level:"medium", correct:"B", options:5,
      text:"A list contains 7 consecutive integers whose median is 20. The greatest of these integers is:",
      choices:["22","23","24","26","20"],
      hint:"For an odd count of consecutive integers, the median is the middle term.",
      expl:"The 4th term is 20, so the terms are 17…23; the greatest is 23.\nAnswer: B." },
    { topic:"Mean, median & mode", level:"medium", correct:"B", options:5,
      text:"Each number in the set {5, 8, 11, 14, 17} is multiplied by 3. The standard deviation of the new set is the old standard deviation multiplied by:",
      choices:["1","3","9","\\(\\sqrt3\\)","6"],
      hint:"Scaling every value scales the spread by the same factor.",
      expl:"Multiplying every element by a constant \\(k\\) multiplies the standard deviation by \\(|k|\\); here \\(k=3\\).\nAnswer: B." },
    { topic:"Mean, median & mode", level:"easy", correct:"C", options:5,
      text:"For the data set {4, 4, 6, 8, 8, 8, 10}, the mode is:",
      choices:["4","6","8","10","7"],
      hint:"The mode is the most frequent value.",
      expl:"8 appears three times, more than any other value.\nAnswer: C." }
  ]},

  { setId:"quant-probability-ex", add:[
    { topic:"Permutations & combinations", level:"medium", correct:"C", options:5,
      text:"How many distinct arrangements can be made from the letters of the word LEVEL?",
      choices:["20","24","30","120","60"],
      hint:"Divide by the factorials of repeated letters.",
      expl:"LEVEL has 5 letters with L twice and E twice: \\(\\frac{5!}{2!\\,2!}=\\frac{120}{4}=30\\).\nAnswer: C." },
    { topic:"Permutations & combinations", level:"easy", correct:"B", options:5,
      text:"In how many ways can a committee of 3 people be chosen from 8 people?",
      choices:["24","56","112","336","28"],
      hint:"Order doesn't matter — use a combination.",
      expl:"\\(\\binom{8}{3}=\\frac{8\\cdot7\\cdot6}{3\\cdot2\\cdot1}=56\\).\nAnswer: B." },
    { topic:"Permutations & combinations", level:"medium", correct:"B", options:5,
      text:"Two fair dice are rolled. What is the probability that the sum of the two faces is 8?",
      choices:["\\(\\tfrac16\\)","\\(\\tfrac{5}{36}\\)","\\(\\tfrac19\\)","\\(\\tfrac1{12}\\)","\\(\\tfrac{7}{36}\\)"],
      hint:"Count the ordered pairs that total 8 out of 36.",
      expl:"Favorable: (2,6),(3,5),(4,4),(5,3),(6,2) — 5 outcomes. \\(P=5/36\\).\nAnswer: B." },
    { topic:"Permutations & combinations", level:"medium", correct:"A", options:5,
      text:"A bag holds 4 red and 6 blue marbles. Two are drawn at random without replacement. The probability that both are red is:",
      choices:["\\(\\tfrac{2}{15}\\)","\\(\\tfrac16\\)","\\(\\tfrac{4}{25}\\)","\\(\\tfrac15\\)","\\(\\tfrac{3}{25}\\)"],
      hint:"Multiply the two conditional probabilities.",
      expl:"\\(\\frac{4}{10}\\times\\frac{3}{9}=\\frac{12}{90}=\\frac{2}{15}\\).\nAnswer: A." }
  ]},

  { setId:"quant-exponents-ex", add:[
    { topic:"Exponent rules", level:"easy", correct:"B", options:5,
      text:"\\(\\dfrac{2^{10}\\times 2^{5}}{2^{12}}\\) equals:",
      choices:["4","8","16","\\(2^{7}\\)","32"],
      hint:"Add exponents when multiplying, subtract when dividing.",
      expl:"\\(2^{10+5-12}=2^{3}=8\\).\nAnswer: B." },
    { topic:"Exponent rules", level:"easy", correct:"B", options:5,
      text:"If \\(3^{x}=81\\), then \\(3^{x-2}\\) equals:",
      choices:["3","9","27","1","81"],
      hint:"First find x.",
      expl:"\\(3^x=81=3^4\\Rightarrow x=4\\); \\(3^{4-2}=3^2=9\\).\nAnswer: B." },
    { topic:"Exponent rules", level:"medium", correct:"B", options:5,
      text:"\\((2^{3})^{2}\\times 2^{-4}\\) equals:",
      choices:["2","4","8","16","1"],
      hint:"Power of a power multiplies exponents.",
      expl:"\\((2^3)^2=2^6\\); \\(2^6\\times2^{-4}=2^{2}=4\\).\nAnswer: B." },
    { topic:"Exponent rules", level:"medium", correct:"B", options:5,
      text:"If \\(5^{2x}=100\\), then \\(5^{x}\\) equals:",
      choices:["5","10","25","50","20"],
      hint:"Note that \\(5^{2x}=(5^{x})^{2}\\).",
      expl:"\\((5^x)^2=100\\Rightarrow 5^x=10\\) (positive root).\nAnswer: B." }
  ]},

  { setId:"quant-linear-ex", add:[
    { topic:"Linear equations", level:"easy", correct:"C", options:5,
      text:"If \\(3x+5=20\\), then x equals:",
      choices:["3","4","5","15","8"],
      hint:"Isolate x.",
      expl:"\\(3x=15\\Rightarrow x=5\\).\nAnswer: C." },
    { topic:"Linear equations", level:"medium", correct:"B", options:5,
      text:"If \\(x+y=10\\) and \\(x-y=4\\), then \\(xy\\) equals:",
      choices:["16","21","24","25","10"],
      hint:"Solve for x and y first.",
      expl:"Adding: \\(2x=14,\\ x=7\\); then \\(y=3\\); \\(xy=21\\).\nAnswer: B." },
    { topic:"Linear equations", level:"easy", correct:"B", options:5,
      text:"A number added to twice itself equals 27. The number is:",
      choices:["8","9","10","13.5","27"],
      hint:"Translate to x + 2x.",
      expl:"\\(x+2x=3x=27\\Rightarrow x=9\\).\nAnswer: B." },
    { topic:"Linear equations", level:"medium", correct:"C", options:5,
      text:"At a fair, adult tickets cost $8 and child tickets cost $5. A group of 10 tickets cost $68 in total. How many child tickets were bought?",
      choices:["2","3","4","6","5"],
      hint:"Let c = child tickets; adults = 10 − c.",
      expl:"\\(8(10-c)+5c=68\\Rightarrow 80-3c=68\\Rightarrow c=4\\).\nAnswer: C." }
  ]},

  /* ---------------- DATA INSIGHTS ---------------- */
  { setId:"di-datasufficiency-ex", add:[
    { topic:"Value questions", level:"medium", correct:"B", options:5, choices:DS,
      text:"Is the number x positive?\n(1) \\(x^{2}=9\\)\n(2) \\(x^{3}=27\\)",
      hint:"An even power hides the sign; an odd power keeps it.",
      expl:"(1) \\(x=\\pm3\\) — sign unknown, not sufficient.\n(2) \\(x^3=27\\Rightarrow x=3>0\\) — sufficient.\nOnly (2) alone works.\nAnswer: B." },
    { topic:"Value questions", level:"medium", correct:"E", options:5, choices:DS,
      text:"What is the value of the integer n?\n(1) n is a prime number between 20 and 30.\n(2) n is odd.",
      hint:"List the candidates that satisfy each statement.",
      expl:"(1) primes in (20,30) are 23 and 29 — two values, not sufficient. (2) far too broad. Together, both 23 and 29 are odd primes in range, so n is still not pinned down.\nAnswer: E." },
    { topic:"Value questions", level:"easy", correct:"D", options:5, choices:DS,
      text:"If x and y are positive, is \\(x>y\\)?\n(1) \\(x/y = 1.2\\)\n(2) \\(x-y = 5\\)",
      hint:"Each statement is a yes/no test — you need a definite answer, not a value.",
      expl:"(1) \\(x=1.2y>y\\) (y>0) — definitely yes, sufficient. (2) \\(x=y+5>y\\) — definitely yes, sufficient.\nEach alone answers the question.\nAnswer: D." },
    { topic:"Value questions", level:"medium", correct:"C", options:5, choices:DS,
      text:"What is the area of rectangle R?\n(1) The length of R is 8.\n(2) The perimeter of R is 28.",
      hint:"Area needs both dimensions.",
      expl:"(1) gives length only — insufficient. (2) gives \\(l+w=14\\) — insufficient. Together: \\(w=14-8=6\\), area \\(=8\\times6=48\\) — sufficient.\nAnswer: C." },
    { topic:"Value questions", level:"medium", correct:"C", options:5, choices:DS,
      text:"Is the positive integer k divisible by 6?\n(1) k is divisible by 3.\n(2) k is divisible by 4.",
      hint:"Divisible by 6 means divisible by both 2 and 3.",
      expl:"(1) alone: divisible by 3 but maybe odd — not sufficient. (2) alone: divisible by 4 but maybe not by 3 — not sufficient. Together k is divisible by lcm(3,4)=12, hence by 6 — always yes.\nAnswer: C." }
  ]},

  { setId:"di-twopart-ex", add:[
    { topic:"Quantitative two-part", level:"medium", correct:"C", options:5,
      text:"A vendor sells apples at $2 each and mangoes at $3 each. A customer buys 12 pieces of fruit in total and pays $29. Which pair gives (number of apples, number of mangoes)?",
      choices:["(5, 7)","(6, 6)","(7, 5)","(8, 4)","(9, 3)"],
      hint:"Let a + m = 12 and 2a + 3m = 29.",
      expl:"\\(2a+3(12-a)=36-a=29\\Rightarrow a=7,\\ m=5\\) → (7, 5).\nAnswer: C." },
    { topic:"Quantitative two-part", level:"medium", correct:"B", options:5,
      text:"A factory makes chairs and tables. Each chair uses 3 kg of wood; each table uses 8 kg. One batch used 20 items and 95 kg of wood. Which pair gives (chairs, tables)?",
      choices:["(12, 8)","(13, 7)","(14, 6)","(15, 5)","(11, 9)"],
      hint:"c + t = 20 and 3c + 8t = 95.",
      expl:"\\(3c+8(20-c)=160-5c=95\\Rightarrow 5c=65,\\ c=13,\\ t=7\\) → (13, 7).\nAnswer: B." },
    { topic:"Quantitative two-part", level:"hard", correct:"D", options:5,
      text:"Two investments together total $10,000. One pays 6% annual interest and the other 9%, and the combined interest for one year is $750. Which pair gives (amount at 6%, amount at 9%)?",
      choices:["($3,000, $7,000)","($4,000, $6,000)","($4,500, $5,500)","($5,000, $5,000)","($6,000, $4,000)"],
      hint:"Let x be the amount at 6%; 0.06x + 0.09(10000 − x) = 750.",
      expl:"\\(0.06x+0.09(10000-x)=900-0.03x=750\\Rightarrow 0.03x=150,\\ x=5000\\); the other is $5,000 → ($5,000, $5,000).\nAnswer: D." }
  ]},

  /* ---------------- CRITICAL REASONING ---------------- */
  { setId:"cr-weaken", add:[
    { topic:"Weaken", level:"medium", correct:"B", options:5,
      text:"A city installed brighter streetlights along Main Street, and over the following year the number of traffic accidents there fell by 30%. City officials concluded that the brighter lighting caused the decline. Which of the following, if true, most weakens the officials' conclusion?",
      choices:["The brighter lights also coincided with a drop in street crime along Main Street.","In the same year, the city lowered the speed limit on Main Street and installed speed cameras.","Accidents on streets near Main Street remained unchanged over the year.","The new streetlights cost considerably more than the city had budgeted.","Most Main Street accidents had historically occurred after dark."],
      hint:"One year, two changes. Ask whether the lights were the only thing that moved.",
      expl:"Conclusion \u2014 the brighter streetlights caused the 30% fall in accidents.\nSupport \u2014 accidents fell in the year after the lights were installed.\nThe weak point \u2014 this is bare sequence, so any other change made in the same year is a rival explanation.\nWhy (B) works \u2014 the city also lowered the speed limit and installed speed cameras that year. Either could account for the drop, so the lights cannot be credited with it.\n(A) A fall in street crime is a second effect, not an alternative cause of the accident decline.\n(C) Unchanged accidents on nearby streets rules out a city-wide trend, which strengthens the officials' case.\n(D) Going over budget is about cost, not about whether the lights worked.\n(E) Accidents historically happening after dark makes lighting a more plausible cause, supporting the conclusion." },
    { topic:"Weaken", level:"medium", correct:"B", options:5,
      text:"A supplement company observes that customers who take its daily vitamin report fewer colds per year than people who take no vitamin, and concludes that the vitamin prevents colds. Which of the following, if true, most weakens the conclusion?",
      choices:["The vitamin is inexpensive and widely available.","People who choose to take a daily vitamin also tend to exercise more and sleep more than those who do not.","Colds are caused by viruses rather than by nutrient deficiencies.","Some customers take the vitamin only during winter months.","The company based its claim on a survey of several thousand customers."],
      hint:"The two groups chose for themselves. Ask what else that choice says about them.",
      expl:"Conclusion \u2014 the vitamin prevents colds.\nSupport \u2014 customers who take it report fewer colds than people who take no vitamin.\nThe weak point \u2014 nobody assigned people to the groups. They selected themselves, so the groups may differ in ways beyond the vitamin.\nWhy (B) works \u2014 if vitamin-takers also exercise and sleep more, those habits could produce the lower cold rate on their own. The correlation survives while the causal claim does not.\n(A) Price and availability have no bearing on whether the vitamin works.\n(C) Colds being viral does not rule out a nutrient affecting susceptibility, so this does not settle the question.\n(D) Seasonal use would blur the effect but does not offer a rival explanation for the difference observed.\n(E) A large sample makes the finding more reliable, which supports the conclusion." },
    { topic:"Weaken", level:"medium", correct:"B", options:5,
      text:"To cut costs, a hospital plans to replace its brand-name IV bags with a chemically identical generic that costs 40% less. An administrator argues the switch will save money with no downside. Which of the following, if true, most weakens the administrator's argument?",
      choices:["The generic bags are manufactured in the same country as the brand-name bags.","The generic bags come only in sizes that do not fit the hospital's existing infusion pumps, which would all have to be replaced.","The brand-name bags have been used at the hospital for over ten years.","Nurses are more familiar with the brand-name bags' labeling.","The generic manufacturer also supplies other hospital products."],
      hint:"\"No downside\" is a strong claim. One hidden cost is enough.",
      expl:"Conclusion \u2014 switching to the generic IV bags will save money with no downside.\nSupport \u2014 the generic is chemically identical and costs 40% less.\nThe weak point \u2014 chemical identity says nothing about whether the bags fit the equipment the hospital already owns.\nWhy (B) works \u2014 if the generic comes only in sizes that do not fit the existing infusion pumps, every pump would have to be replaced. That is both a downside and a cost that could swallow the savings.\n(A) Country of manufacture has no bearing on cost or fit.\n(C) Ten years of use is familiarity, not a reason the switch fails.\n(D) Nurses knowing the old labelling is a minor training matter, far weaker than replacing every pump.\n(E) The generic maker supplying other products is neutral, if not mildly reassuring." }
  ]},

  { setId:"cr-strengthen", add:[
    { topic:"Strengthen", level:"medium", correct:"B", options:5,
      text:"A researcher claims that a new math app improves scores, noting that students who used it scored higher on a year-end test than students who did not. Which of the following, if true, most strengthens the claim?",
      choices:["The app was designed by experienced classroom teachers.","Before the study, the two groups of students had scored equally on a comparable math pretest.","The app is popular and enjoyable to use.","The year-end test covered some topics the app did not teach.","A few students in the app group used it only occasionally."],
      hint:"Two groups, one used the app. Ask whether they started level.",
      expl:"Conclusion \u2014 the maths app improves scores.\nSupport \u2014 students who used it scored higher on a year-end test than students who did not.\nThe gap \u2014 if the app group was stronger to begin with, the higher scores show nothing about the app.\nWhy (B) works \u2014 equal scores on a comparable pretest establish that the two groups started level, so the later difference has to come from what happened in between.\n(A) Who designed the app says nothing about whether it worked.\n(C) Popularity and enjoyment are not evidence of learning.\n(D) The test covering untaught topics would blunt any measured effect, weakening the claim.\n(E) Occasional use in the app group also works against the finding rather than for it." },
    { topic:"Strengthen", level:"medium", correct:"A", options:5,
      text:"A town credits its new curbside recycling program for a drop in landfill tonnage, which fell in the year after the program began. Which of the following, if true, most strengthens the town's conclusion?",
      choices:["Neighboring towns without such a program saw no change in their landfill tonnage over the same year.","The recycling program was more expensive to run than expected.","Residents initially found the sorting rules confusing.","The regional landfill is nearing its capacity.","Recycling participation has been rising nationwide."],
      hint:"Landfill tonnage could have fallen for reasons that had nothing to do with the programme.",
      expl:"Conclusion \u2014 the curbside recycling programme caused the drop in landfill tonnage.\nSupport \u2014 tonnage fell in the year after the programme began.\nThe gap \u2014 a regional or economic shift could have reduced waste everywhere, programme or no programme.\nWhy (A) works \u2014 neighbouring towns [[without]] such a programme saw no change over the same year. That rules out the general-trend explanation and isolates the programme.\n(B) Higher-than-expected cost is about the budget, not about the tonnage.\n(C) Confusing sorting rules would reduce the programme's effect, weakening the claim.\n(D) A landfill nearing capacity explains why the town cares, not why tonnage fell.\n(E) Rising participation nationwide suggests a broad trend, which offers a [[rival]] explanation rather than support." },
    { topic:"Strengthen", level:"medium", correct:"B", options:5,
      text:"A company switched to a four-day workweek and total weekly output rose. Management concludes the shorter week caused the increase. Which of the following, if true, most strengthens the claim that the schedule change—rather than another factor—was responsible?",
      choices:["Employees said they enjoyed the extra day off.","The company made no other changes—no new hires, equipment, or pay—when it adopted the four-day week.","Output is measured by the number of units shipped.","Four-day weeks are becoming common in the industry.","A few employees still answered email on their day off."],
      hint:"The question asks you to rule out other causes, not to praise the policy.",
      expl:"Conclusion \u2014 the shorter week, rather than something else, caused output to rise.\nSupport \u2014 weekly output rose after the company moved to four days.\nThe gap \u2014 any other change made at the same time could be the real cause.\nWhy (B) works \u2014 no new hires, no new equipment, no pay change. With everything else held fixed, the schedule is the only candidate left.\n(A) Employees enjoying the day off explains why they like it, not why output rose.\n(C) How output is measured is a definition, not a cause.\n(D) Industry adoption of four-day weeks says nothing about this company's result.\n(E) A few people answering email on their day off suggests the week was not truly shorter, which weakens the claim." }
  ]},

  { setId:"cr-assumption", add:[
    { topic:"Assumption", level:"medium", correct:"C", options:5,
      text:"Editorial: Our newspaper should stop printing horoscopes. Horoscopes have no scientific basis, and a serious newspaper should print only material that has scientific support. The argument depends on assuming which of the following?",
      choices:["Readers of the newspaper dislike horoscopes.","Horoscopes are expensive for the newspaper to produce.","The newspaper is, or aims to be, a serious newspaper.","No competing newspaper prints horoscopes.","Every horoscope prediction turns out to be inaccurate."],
      hint:"The rule quoted is about serious newspapers. Ask whether it applies to this one.",
      expl:"Conclusion \u2014 our newspaper should stop printing horoscopes.\nSupport \u2014 horoscopes have no scientific basis, and a serious newspaper should print only material with scientific support.\nThe gap \u2014 the principle is stated about [[serious]] newspapers. It reaches this newspaper only if this newspaper is one, or is trying to be. That is (C).\nNegation test \u2014 if the paper neither is nor aims to be serious, the principle simply does not apply to it and the recommendation has no support. So (C) is required.\n(A) Reader preference is not part of the stated principle, which turns on scientific support.\n(B) Cost never enters the argument.\n(D) What competitors print is irrelevant to what this paper's own standard requires.\n(E) Far too strong. The objection is that horoscopes lack scientific support, not that every prediction fails." },
    { topic:"Assumption", level:"medium", correct:"B", options:5,
      text:"Company X's profits rose in the year after it relocated its factory overseas. A manager concludes that the relocation increased the company's profits. The argument assumes which of the following?",
      choices:["The overseas factory produces exactly the same products as before.","No other factor was chiefly responsible for the rise in profits during that year.","Overseas labor is less expensive than domestic labor.","The company's profits will keep rising in future years.","Shareholders approved of the relocation."],
      hint:"Profits rose [[after]] the move. That is the whole of the evidence.",
      expl:"Conclusion \u2014 relocating the factory overseas increased the company's profits.\nSupport \u2014 profits rose in the year following the relocation.\nThe gap \u2014 this is bare sequence. Any causal reading of it assumes nothing else was responsible for the rise. That is (B).\nNegation test \u2014 if some other factor was chiefly responsible \u2014 a price rise, a competitor's collapse, a surge in demand \u2014 the relocation is not what lifted profits and the conclusion fails. So (B) is required.\n(A) An unchanged product line would make the comparison cleaner, but the profit rise could still be caused by the move even if the products changed.\n(C) Cheaper labour is a plausible mechanism, not a requirement; the move could pay off through shipping, tax or scale instead.\n(D) A claim about future years goes beyond a conclusion that is only about the year just past.\n(E) Shareholder approval has no bearing on what caused the profits." },
    { topic:"Assumption", level:"medium", correct:"B", options:5,
      text:"A planner argues that the new bridge will reduce commute times because it offers a more direct route between the suburbs and downtown. The argument assumes which of the following?",
      choices:["The bridge was inexpensive to build.","A substantial number of commuters will actually use the new bridge instead of their current routes.","The old routes into downtown will be permanently closed.","Downtown has enough parking for additional commuters.","The suburbs will continue to grow in population."],
      hint:"A shorter route only shortens commutes for people who take it.",
      expl:"Conclusion \u2014 the new bridge will reduce commute times.\nSupport \u2014 it offers a more direct route between the suburbs and downtown.\nThe gap \u2014 a route nobody drives saves nobody any time. The argument assumes enough commuters will actually switch to it. That is (B).\nNegation test \u2014 if commuters keep to their current routes, traffic is unchanged and commute times do not fall. The conclusion collapses, so (B) is required.\n(A) Construction cost has nothing to do with travel time.\n(C) Closing the old routes would force the switch, but the argument does not need anything that drastic \u2014 it needs only that a substantial number choose the bridge.\n(D) Parking capacity affects where commuters end up, not how long the drive takes.\n(E) Continued growth in the suburbs would add traffic, working against the conclusion rather than supporting it." }
  ]},

  { setId:"cr-paradox", add:[
    { topic:"Explain the paradox", level:"medium", correct:"B", options:5,
      text:"A retailer cut the price of its umbrellas by 20%, yet its total revenue from umbrella sales rose. Which of the following, if true, best explains this result?",
      choices:["The retailer simultaneously raised the price of its raincoats.","The lower price led to a more-than-proportional increase in the number of umbrellas sold.","Umbrella sales are highly seasonal.","The retailer advertised its raincoats heavily that month.","Several competitors also sell umbrellas."],
      hint:"Revenue is price times quantity. One went down, so ask about the other.",
      expl:"The puzzle \u2014 the price fell 20% and yet total revenue from umbrellas rose.\nWhy (B) resolves it \u2014 revenue is price multiplied by quantity. If the number sold rose by more than the proportion by which the price fell, the product goes up. That is exactly what (B) states.\n(A) Raincoat prices affect raincoat revenue, not umbrella revenue.\n(C) Seasonality might explain a change over time but not the effect of this price cut.\n(D) Raincoat advertising is again the wrong product.\n(E) Competitors selling umbrellas is background, not an explanation of the rise." },
    { topic:"Explain the paradox", level:"medium", correct:"B", options:5,
      text:"After a company hired more customer-service agents, the average time customers spent waiting on hold increased. Which of the following, if true, best explains the increase?",
      choices:["The newly hired agents received thorough training.","A concurrent advertising campaign sharply increased the number of customers calling in.","The company uses an automated phone menu to route calls.","Agents are paid by the hour rather than per call.","Some customers prefer to contact the company by email."],
      hint:"More agents should mean shorter waits. Ask what happened to the queue.",
      expl:"The puzzle \u2014 the company added agents, yet average hold times went up.\nWhy (B) resolves it \u2014 an advertising campaign sharply increased the number of calls. If demand grew faster than capacity, waits lengthen despite the extra staff.\n(A) Thorough training would shorten calls, not lengthen waits.\n(C) An automated menu existed before and after; it explains nothing about the change.\n(D) How agents are paid does not determine how many calls arrive.\n(E) Customers using email instead would reduce call volume, deepening the puzzle." },
    { topic:"Explain the paradox", level:"medium", correct:"B", options:5,
      text:"Over the past decade a country's factories became markedly more energy-efficient per unit of output, yet the country's total industrial energy consumption rose. Which of the following, if true, best resolves this apparent discrepancy?",
      choices:["Energy prices fell steadily over the decade.","Industrial output expanded so greatly that total energy use rose even as energy per unit fell.","Many factories adopted renewable energy sources.","Efficiency gains were measured per worker rather than per unit.","A number of older factories were shut down during the decade."],
      hint:"Energy per unit fell. Total energy is per-unit times units.",
      expl:"The puzzle \u2014 factories became markedly more efficient per unit of output, yet total industrial energy use rose.\nWhy (B) resolves it \u2014 total energy is energy per unit multiplied by the number of units. If output expanded enough, the total climbs even as each unit takes less energy.\n(A) Falling energy prices might encourage use, but the question is arithmetic: it is the volume of output that reconciles the two facts.\n(C) Renewable sources change where the energy comes from, not how much is used.\n(D) A different basis of measurement would mean the premise was misstated rather than explaining a real discrepancy.\n(E) Closing older factories would reduce total consumption, deepening the puzzle." }
  ]},

  { setId:"cr-inference", add:[
    { topic:"Inference / must be true", level:"medium", correct:"B", options:5,
      text:"Every student who passed the certification exam had completed the advanced course. Maria did not complete the advanced course. If the statements above are true, which of the following must also be true?",
      choices:["Maria failed the certification exam.","Maria did not pass the certification exam.","Maria did not take the certification exam.","The advanced course guarantees passing the exam.","Only students in the advanced course may take the exam."],
      hint:"Run the conditional backwards.",
      expl:"Given \u2014 every student who passed had completed the advanced course. Maria did not complete it.\nWhat follows \u2014 passing requires the course, and Maria lacks the course, so she did not pass. That is (B).\n(A) \"Failed\" implies she sat the exam. Not passing also covers never taking it.\n(C) Equally unsupported in the other direction: nothing says she stayed away.\n(D) Reverses the conditional. The course is necessary for passing, not sufficient.\n(E) Adds a restriction on who may take the exam that the premises never state." },
    { topic:"Inference / must be true", level:"medium", correct:"B", options:5,
      text:"In a certain library, every book on the third floor is a reference book, and no reference book may be borrowed. If these statements are true, which of the following must be true?",
      choices:["Every book that cannot be borrowed is on the third floor.","No book on the third floor may be borrowed.","All of the library's reference books are on the third floor.","Some books on the third floor may be borrowed.","All borrowable books are located on the first floor."],
      hint:"Chain the two statements.",
      expl:"Given \u2014 every book on the third floor is a reference book, and no reference book may be borrowed.\nWhat follows \u2014 third floor implies reference, and reference implies not borrowable, so nothing on the third floor may be borrowed. That is (B).\n(A) Reverses it. Unborrowable books may sit anywhere.\n(C) Also a reversal: reference books need not all be on the third floor.\n(D) Directly contradicts the chain.\n(E) Invents a first floor and a claim about it that no premise supports." },
    { topic:"Inference / must be true", level:"medium", correct:"B", options:5,
      text:"The company will hold its annual picnic only if at least 30 employees sign up. This year only 22 employees signed up. If the statements are true, which of the following must be true?",
      choices:["The picnic will be rescheduled for a later date.","The company will not hold the picnic this year.","More employees will sign up before the deadline.","The picnic was also canceled last year.","Most employees dislike the picnic."],
      hint:"\"Only if\" states a necessary condition. It was not met.",
      expl:"Given \u2014 the picnic will be held only if at least 30 employees sign up. Only 22 signed up.\nWhat follows \u2014 a necessary condition failed, so the picnic will not be held this year. That is (B).\n(A) Rescheduling is a possibility the premises neither state nor rule out.\n(C) Nothing indicates further sign-ups; the count given is the final one.\n(D) Last year is never mentioned.\n(E) Low sign-up is not evidence of dislike; people may simply be unavailable." }
  ]},

  /* ---------------- FROM DRIVE: GMAT Quant Live Session 1 (answers re-verified) ---------------- */
  { setId:"quant-sets-ages-ex", add:[
    { topic:"Overlapping sets (Venn)", level:"medium", correct:"E", options:5,
      text:"How many attendees are at a convention if 150 of the attendees are neither female nor students, one-sixth of the attendees are female students, two-thirds of the attendees are female, and one-third of the attendees are students?",
      choices:["300","450","600","800","900"],
      hint:"Use the two-set formula on fractions of the total, then read off what \"neither\" must equal.",
      expl:"Step 1 — Let the total be T. Then \\(F = \\tfrac{2T}{3}\\), \\(S = \\tfrac{T}{3}\\) and \\(F \\cap S = \\tfrac{T}{6}\\).\nStep 2 — \\(F \\cup S = \\tfrac{2T}{3} + \\tfrac{T}{3} - \\tfrac{T}{6} = \\tfrac{5T}{6}\\).\nStep 3 — \"Neither\" is \\(T - \\tfrac{5T}{6} = \\tfrac{T}{6} = 150\\), so \\(T = 900\\).\nAnswer: E." },
    { topic:"Overlapping sets (Venn)", level:"medium", correct:"B", options:5,
      text:"In a group of 68 students, each student is registered for at least one of three classes — History, Math and English. 25 are registered for History, 25 for Math and 34 for English. If only 3 students are registered for all three classes, how many are registered for exactly two classes?",
      choices:["13","10","9","8","7"],
      hint:"The sum of the three group sizes counts doubles twice and triples three times.",
      expl:"Step 1 — \\(25 + 25 + 34 = 84\\), while only 68 distinct students exist.\nStep 2 — The identity is: sum of groups \\(=\\) total \\(+\\) (exactly two) \\(+\\ 2\\times\\) (exactly three).\nStep 3 — \\(84 = 68 + x + 2(3)\\), so \\(x = 10\\).\nAnswer: B." }
  ]},
  { setId:"quant-percentage-ex", add:[
    { topic:"Percentages & percent change", level:"medium", correct:"A", options:5,
      text:"A school's annual budget for student computers increased by 60% this year over last year. If the price of a student computer increased by 20% this year, then the number of computers it can purchase this year is what percent greater than the number it purchased last year?",
      choices:["33⅓%","40%","42%","48%","60%"],
      hint:"Quantity is budget divided by price — so divide the two multipliers.",
      expl:"Step 1 — New quantity \\(= \\dfrac{1.6 \\times \\text{budget}}{1.2 \\times \\text{price}} = \\dfrac{1.6}{1.2}\\) of the old quantity.\nStep 2 — \\(\\dfrac{1.6}{1.2} = \\dfrac43\\), an increase of \\(\\tfrac13\\).\nStep 3 — That is 33.33%.\nAnswer: A." },
    { topic:"Percentages & percent change", level:"hard", correct:"D", options:5,
      text:"A corporation's annual report stated that profits were up 10 percent over the previous year, although profits as a percent of sales were down 10 percent. Total sales that year were approximately what percent of sales for the previous year?",
      choices:["78%","90%","110%","122%","190%"],
      hint:"Sales is profit divided by the profit margin — so divide the two multipliers.",
      expl:"Step 1 — Profit multiplier: 1.1. Margin multiplier: 0.9.\nStep 2 — Since \\(S = \\dfrac{P}{P/S}\\), the sales multiplier is \\(\\dfrac{1.1}{0.9} \\approx 1.222\\).\nStep 3 — About 122%.\nAnswer: D." },
    { topic:"Percentages & percent change", level:"hard", correct:"A", options:5,
      text:"A driver paid n dollars for auto insurance in 1997. The premium rose by p percent for 1998; for each of 1999 and 2000 the premium was decreased by 1/6 from the previous year's figure. If the 2000 premium was again n dollars, what is the value of p?",
      choices:["44","12","40","36","50"],
      hint:"Chain the three multipliers and set the product equal to 1.",
      expl:"Step 1 — \\(n\\left(1 + \\tfrac{p}{100}\\right)\\left(\\tfrac56\\right)^{2} = n\\).\nStep 2 — \\(1 + \\tfrac{p}{100} = \\left(\\tfrac65\\right)^{2} = \\tfrac{36}{25} = 1.44\\).\nStep 3 — \\(p = 44\\).\nAnswer: A." }
  ]},
  { setId:"quant-mixture-ex", add:[
    { topic:"Mixtures & solutions", level:"medium", correct:"A", options:5,
      text:"Grapes are 92% water and raisins are 20% water. A quantity of raisins currently weighs 10 pounds. How much did it weigh when it was all grapes? (Only water evaporates; the solid content is unchanged.)",
      choices:["100 pounds","25 pounds","46 pounds","92 pounds","146 pounds"],
      hint:"Track the part that never changes — the solid.",
      expl:"Step 1 — The 10 pounds of raisins are 20% water, so the solid weighs \\(0.8 \\times 10 = 8\\) pounds.\nStep 2 — As grapes, that same 8 pounds of solid made up \\(100\\% - 92\\% = 8\\%\\) of the weight.\nStep 3 — \\(\\dfrac{8}{0.08} = 100\\) pounds.\nAnswer: A." },
    { topic:"Mixtures & solutions", level:"medium", correct:"A", options:5,
      text:"A portion of a 50% alcohol solution is replaced with an equal amount of a 25% alcohol solution. If the result is a 30% alcohol solution, what portion of the original solution was replaced?",
      choices:["80%","75%","66%","20%","3%"],
      hint:"Let p be the fraction replaced and write the alcohol balance for one unit of solution.",
      expl:"Step 1 — After replacing a fraction p: alcohol \\(= 0.50(1 - p) + 0.25p = 0.30\\).\nStep 2 — \\(0.50 - 0.25p = 0.30\\), so \\(0.25p = 0.20\\) and \\(p = 0.8\\).\nStep 3 — 80% of the original was replaced.\nAnswer: A." }
  ]},
  { setId:"quant-profitloss-ex", add:[
    { topic:"Profit, loss & discount", level:"medium", correct:"C", options:5,
      text:"A merchant bought a jacket for $60 and set a selling price equal to the purchase price plus a markup that was 25 percent of the selling price. During a sale the merchant discounted the selling price by 20 percent and sold the jacket. What was the merchant's gross profit?",
      choices:["$0","$3","$4","$12","$15"],
      hint:"The markup is a percentage of the selling price, not of the cost — set up an equation rather than multiplying.",
      expl:"Step 1 — \\(S = 60 + 0.25S\\), so \\(0.75S = 60\\) and \\(S = 80\\).\nStep 2 — Discounted price: \\(0.80 \\times 80 = 64\\).\nStep 3 — Gross profit \\(= 64 - 60 = \\$4\\).\nAnswer: C." }
  ]},
  { setId:"quant-ratio-ex", add:[
    { topic:"Ratios & proportions", level:"medium", correct:"A", options:5,
      text:"According to the directions on a can of frozen orange-juice concentrate, 1 can of concentrate is mixed with 3 cans of water. How many 12-ounce cans of concentrate are required to prepare two hundred 6-ounce servings of orange juice?",
      choices:["25","34","50","67","100"],
      hint:"Find the total volume of juice first, then the fraction of it that is concentrate.",
      expl:"Step 1 — Juice needed: \\(200 \\times 6 = 1200\\) ounces.\nStep 2 — Concentrate is 1 part in 4, so \\(1200 \\div 4 = 300\\) ounces of concentrate.\nStep 3 — \\(300 \\div 12 = 25\\) cans.\nAnswer: A." }
  ]},
  { setId:"quant-quadratic-ex", add:[
    { topic:"Quadratic equations", level:"hard", correct:"A", options:5,
      text:"A merchant paid $300 for a shipment of x identical calculators. She used 2 of them as demonstrators and sold each of the rest for $5 more than the average cost of the x calculators. If total revenue was $120 more than the cost of the shipment, how many calculators were in the shipment?",
      choices:["30","28","26","25","24"],
      hint:"Average cost is \\(300/x\\) — build the revenue equation and clear the fraction.",
      expl:"Step 1 — \\((x - 2)\\left(\\dfrac{300}{x} + 5\\right) = 420\\).\nStep 2 — Expanding: \\(300 + 5x - \\dfrac{600}{x} - 10 = 420\\), so \\(5x - \\dfrac{600}{x} = 130\\).\nStep 3 — Multiplying by x: \\(5x^{2} - 130x - 600 = 0\\), i.e. \\(x^{2} - 26x - 120 = 0\\), i.e. \\((x - 30)(x + 4) = 0\\).\nStep 4 — \\(x = 30\\).\nAnswer: A." }
  ]},
  { setId:"quant-interest-ex", add:[
    { topic:"Simple & compound interest", level:"hard", correct:"B", options:5,
      text:"A certain investment grows at an annual interest rate of 8%, compounded quarterly. Which of the following equations can be solved to find the number of years, x, for the investment to increase by a factor of 16?",
      choices:["\\(16=(1.02)^{x/4}\\)","\\(2=(1.02)^{x}\\)","\\(16=(1.08)^{4x}\\)","\\(2=(1.02)^{x/4}\\)","\\(\\tfrac1{16}=(1.02)^{4x}\\)"],
      hint:"Quarterly compounding at 8% a year means 2% per quarter and 4x quarters — then look for the equivalent form.",
      expl:"Step 1 — The growth condition is \\((1.02)^{4x} = 16\\).\nStep 2 — Since \\(16 = 2^{4}\\), take the fourth root of both sides: \\((1.02)^{x} = 2\\).\nStep 3 — That is exactly choice B; none of the others is equivalent.\nAnswer: B." }
  ]},
  { setId:"di-datasufficiency-ex", add:[
    { topic:"Value questions", level:"medium", correct:"B", options:5, choices:DS,
      text:"Joanna bought only $0.15 stamps and $0.29 stamps. How many $0.15 stamps did she buy?\n(1) She bought an equal number of $0.15 stamps and $0.29 stamps.\n(2) She bought $4.40 worth of stamps.",
      hint:"A single linear equation in two non-negative integers often has exactly one solution — check before assuming otherwise.",
      expl:"Step 1 — (1) gives only that the two counts match, with no total — insufficient.\nStep 2 — (2) \\(15a + 29b = 440\\). Reducing mod 15: \\(14b \\equiv 5\\), i.e. \\(b \\equiv 10 \\pmod{15}\\). \\(b = 10\\) gives \\(a = 10\\), and \\(b = 25\\) already overshoots 440.\nStep 3 — So the only solution is \\(a = b = 10\\) — sufficient on its own.\nAnswer: B." },
    { topic:"Value questions", level:"medium", correct:"B", options:5, choices:DS,
      text:"Marta bought several pencils, each either a 23-cent pencil or a 21-cent pencil. How many 23-cent pencils did she buy?\n(1) Marta bought a total of 6 pencils.\n(2) The total value of the pencils was 130 cents.",
      hint:"Try every possible count of 23-cent pencils against statement (2) — there are only a handful.",
      expl:"Step 1 — (1) With 6 pencils the split could be 0/6, 1/5, and so on — insufficient.\nStep 2 — (2) \\(23a + 21b = 130\\) with a, b non-negative integers. Testing \\(a = 0\\) through 5, only \\(a = 2\\) leaves \\(130 - 46 = 84 = 21 \\times 4\\) — sufficient.\nAnswer: B." },
    { topic:"Value questions", level:"hard", correct:"C", options:5, choices:DS,
      text:"A construction company was paid $500,000 for a project whose only costs were labor and materials. Was the company's profit greater than $150,000?\n(1) The company's total cost was three times its cost for materials.\n(2) The company's profit was greater than its cost for labor.",
      hint:"Write everything in terms of the materials cost, then turn statement (2) into an inequality.",
      expl:"Step 1 — (1) says total cost \\(= 3M\\), so labour \\(= 2M\\) — but M is unknown, so profit is unknown. Insufficient.\nStep 2 — (2) alone gives no absolute figures. Insufficient.\nStep 3 — Together, profit \\(= 500{,}000 - 3M\\) and the condition profit \\(> 2M\\) gives \\(500{,}000 > 5M\\), i.e. \\(M < 100{,}000\\).\nStep 4 — Then profit \\(= 500{,}000 - 3M > 500{,}000 - 300{,}000 = 200{,}000 > 150{,}000\\) — a definite yes.\nAnswer: C." },
    { topic:"Value questions", level:"medium", correct:"C", options:5, choices:DS,
      text:"Of the 60 animals on a certain farm, 2/3 are either cows or pigs. How many of the animals are cows?\n(1) The farm has more than twice as many cows as pigs.\n(2) The farm has more than 12 pigs.",
      hint:"The two inequalities squeeze the pig count from both sides.",
      expl:"Step 1 — Cows plus pigs \\(= \\tfrac23 \\times 60 = 40\\).\nStep 2 — (1) \\(C > 2P\\) with \\(C = 40 - P\\) gives \\(40 - P > 2P\\), i.e. \\(P < 13.33\\) — a range, insufficient alone.\nStep 3 — (2) \\(P > 12\\) — insufficient alone.\nStep 4 — Together \\(12 < P < 13.33\\) forces \\(P = 13\\), so \\(C = 27\\).\nAnswer: C." }
  ]},

  /* ---- Boldface CR (from the Drive "RC + CR Session 6" doc; answer key from that doc).
          [[...]] marks the boldface portions the question asks about. ---- */
  { setId:"cr-boldface", add:[
    { topic:"Boldface & method of reasoning", level:"medium", correct:"E", options:5,
      text:"Researcher: [[The rate of psychological problems is higher among children of divorced parents than among other children.]] But it would be a mistake to conclude that these problems are caused by the difficulty the children have adjusting to divorce. It is just as reasonable to infer that certain behaviours that increase the likelihood of divorce — hostility, distrust, lack of empathy — are learned by children from their parents, and that it is these learned behaviours that cause the children's psychological problems.\nThe boldface portion plays which one of the following roles?",
      choices:["It is the conclusion of the argument.","It is the claim that the argument tries to refute.","It is offered as evidence for the claim that divorce is harmful to the children of the divorcing parents.","It is offered as evidence for the claim that certain behaviours are often responsible for divorce.","It is cited as an established finding for which the argument proposes an explanation."],
      hint:"Ask whether the researcher disputes the boldface fact or only disputes what explains it.",
      expl:"The finding \u2014 the boldface reports a higher rate of psychological problems among children of divorced parents. The researcher never questions it.\nWhat is disputed \u2014 the word \"But\" attacks the [[causal reading]] of the finding: that the problems come from difficulty adjusting to the divorce.\nThe rival account \u2014 children learn hostility, distrust and lack of empathy from their parents; those learned behaviours cause both the divorce and the children's problems.\nSo \u2014 the boldface is an accepted finding for which the argument proposes a different explanation, which is (E).\n(A) The conclusion is that the causal inference would be a mistake. The statistic is where the argument starts, not where it ends.\n(B) The classic trap. What the argument refutes is an [[explanation of]] the finding, not the finding itself, which it relies on throughout.\n(C) It is not offered as evidence for anything. It is the thing being explained.\n(D) Same error. The claim about behaviours causing divorce is part of the researcher's proposed explanation, not something the statistic is used to prove.\nAnswer: E." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"C", options:5,
      text:"It is primarily by raising interest rates that central bankers curb inflation, but [[an increase in interest rates takes up to two years to affect inflation]]. Accordingly, central bankers usually try to raise interest rates before inflation becomes excessive, at which time inflation is not yet readily apparent either. But unless inflation is readily apparent, interest-rate hikes generally will be perceived as needlessly restraining a growing economy. Thus, central bankers' success in temporarily restraining inflation may make it harder for them to ward off future inflation without incurring the public's wrath.\nThe boldface portion plays which one of the following roles?",
      choices:["It is presented as a complete explanation of the final claim.","It is a description of a phenomenon for which the rest of the argument offers an explanation.","It is a premise offered in support of the conclusion that central bankers' success may make it harder to ward off future inflation.","It is a conclusion supported by the claim that rate rises take two years to work.","It is a premise supporting the claim that hikes will be perceived as needlessly restraining the economy."],
      hint:"Trace the chain: which link does the two-year lag start, and where does the chain end?",
      expl:"The conclusion \u2014 signalled by \"Thus\": central bankers' success at temporarily restraining inflation may make it harder to ward off future inflation without public anger.\nThe chain to it \u2014 rate rises take up to two years to bite, so bankers must act before inflation is visible; but while inflation is invisible, hikes look like needless restraint on a growing economy; hence the public's wrath.\nThe boldface \u2014 the two-year lag, which is the first link in that chain and is given as a fact rather than derived from anything.\nSo \u2014 it is a premise supporting the final conclusion, which is (C).\n(A) It is one step among several, not a complete explanation. Remove any other link and the conclusion no longer follows.\n(B) Backwards. The lag is what does the explaining here; it is not the phenomenon being explained.\n(D) Nothing in the argument supports the lag \u2014 it is asserted, so it cannot be a conclusion. The choice also has it supporting itself.\n(E) Wrong endpoint. The lag feeds the whole chain, not merely the claim about how hikes are perceived.\nAnswer: C." },
    { topic:"Boldface & method of reasoning", level:"medium", correct:"C", options:5,
      text:"After an area has been hit by a natural disaster, there is often a great demand for plywood. Retailers raise prices on new shipments, and some people denounce them for profiteering. In fact, however, these retailers do not make more money on each sheet of plywood than before the disaster, because [[transporting the plywood into devastated areas is difficult and expensive, and therefore the plywood's cost to retailers is higher than it was before the disaster]].\nThe boldface portion plays which of the following roles?",
      choices:["a counterexample to a claim","the main conclusion toward which the argument as a whole is directed","a subsidiary conclusion used to support the main conclusion of the argument","an example used to illustrate the implausibility of the position argued against","background information used to provide a context for the argument"],
      hint:"A claim can be both supported by something earlier and used to support something later.",
      expl:"The main conclusion \u2014 retailers do not make more money on each sheet of plywood than they did before the disaster. It is stated before the word \"because.\"\nThe boldface, part one \u2014 transporting plywood into devastated areas is difficult and expensive.\nThe boldface, part two \u2014 \"and therefore the plywood's cost to retailers is higher than before.\" That is drawn from part one, and it is in turn the reason the main conclusion holds.\nSo \u2014 supported by something and supporting something else: a subsidiary conclusion, which is (C).\n(A) It is not a counterexample to anything. It is the argument's own support for its own conclusion.\n(B) The standard trap. The main conclusion is the sentence about retailers not making more money, which comes before \"because.\"\n(D) It is a reason, not an illustration. The argument would collapse without it, which is not true of an example.\n(E) Background does not carry a \"therefore.\" This passage draws an inference inside the boldface itself.\nAnswer: C." },
    { topic:"Boldface & method of reasoning", level:"medium", correct:"A", options:5,
      text:"Some biologists believe that the capacity for flight first developed in marine reptiles, claiming that feathers clearly developed from scales. Other biologists rightly reject this suggestion, pointing out that [[bats have no scales and that non-marine reptiles also have scales]]. Those who believe that flight first developed in tree-dwelling reptiles reject the claim that the limbs of land-dwelling reptiles might have developed into wings.\nThe boldface portion plays which of the following roles?",
      choices:["It is cited as evidence against the claim that the capacity for flight first developed in marine reptiles.","It is cited as evidence against the claim that the capacity for flight first developed in land-dwelling animals.","It is cited as evidence against the claim that the capacity for flight first developed in tree-dwelling reptiles.","It weakens the claim that tree-dwelling reptiles were the first to develop flight.","It corroborates the observation that some mammals without scales developed the capacity to fly."],
      hint:"Identify which of the several claims in this passage the boldface is aimed at.",
      expl:"The first camp \u2014 flight first developed in marine reptiles, on the grounds that feathers clearly developed from scales.\nThe boldface \u2014 what the [[other]] biologists point out in rejecting that: bats have no scales, and non-marine reptiles have scales too.\nHow it bites \u2014 bats fly without scales, so scales are not required for flight; and scales are not peculiar to marine reptiles, so they cannot single those reptiles out.\nSo \u2014 the boldface is evidence against the marine-reptile claim, which is (A).\n(B) Land-dwelling origins come up only in the final sentence, which the boldface never touches.\n(C) Same problem. The tree-dwelling camp is mentioned last and is not the boldface's target.\n(D) Backwards. Undercutting the marine-reptile claim, if anything, leaves the tree-dwelling camp better off.\n(E) True enough about bats, but it ignores the second half of the boldface and describes an observation rather than the job the boldface does in the argument.\nAnswer: A." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"B", options:5,
      text:"Pedigreed dogs must conform to standards set by pedigree organizations. Those standards specify physical appearance but stipulate nothing about other genetic traits, such as those that let working breeds do their work. Since breeders try to maintain only the traits pedigree organizations specify, and [[traits that breeders do not try to maintain risk being lost, certain traits like herding ability risk being lost among pedigreed dogs]]. Therefore, pedigree organizations should set standards requiring working ability in pedigreed dogs classified as working dogs.\nThe boldface portion plays which one of the following roles?",
      choices:["It is a claim on which the argument depends but for which no support is given.","It is a subsidiary conclusion used in support of the main conclusion.","It acknowledges a possible objection to the proposal put forth in the argument.","It summarizes the position the argument is directed toward discrediting.","It provides evidence necessary to support a claim stated earlier."],
      hint:"The word \u201cTherefore\u201d comes after the boldface \u2014 so the boldface is not the endpoint.",
      expl:"The main conclusion \u2014 the recommendation after \"Therefore\": pedigree organizations should set standards requiring working ability in working breeds.\nWhat comes before the boldface \u2014 standards specify appearance only, and breeders maintain only what the standards specify.\nThe boldface \u2014 from those premises it concludes that traits like herding ability risk being lost. That conclusion is then the reason the recommendation is needed.\nSo \u2014 supported by what precedes it and supporting what follows: a subsidiary conclusion, which is (B).\n(A) Support [[is]] given for it \u2014 the two preceding claims are exactly that support.\n(C) It motivates the proposal rather than objecting to it. An objection would have to cut against the recommendation.\n(D) Nothing here is being discredited. The argument has no opposing position to knock down.\n(E) It points forward, not backward. The claims before it support it, not the other way round.\nAnswer: B." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"D", options:5,
      text:"Economist: Tropicorp has been clearing tropical forest for cattle ranching, although pastures there become useless after a few years. It has not gone into rubber tapping, even though greater profits can be made from rubber tapping, which leaves the forest intact. Thus, some environmentalists argue that [[Tropicorp's actions do not serve even its own economic interest]]. However, the initial investment for rubber tapping is larger, there is a shortage of workers employable in rubber tapping, and taxes are higher on rubber-tapping profits. Consequently, [[the environmentalists' conclusion is probably wrong]].\nIn the economist's argument, the two boldface portions play which of the following roles?",
      choices:["The first supports the economist's conclusion; the second calls it into question.","The first states the economist's conclusion; the second supports it.","The first supports the environmentalists' conclusion; the second states that conclusion.","The first states the environmentalists' conclusion; the second states the economist's conclusion.","Each supports the economist's conclusion."],
      hint:"Two speakers, two conclusions \u2014 work out whose each boldface belongs to.",
      expl:"First boldface \u2014 introduced by \"some environmentalists argue that,\" so it is the [[environmentalists']] conclusion, reported by the economist rather than endorsed.\nWhat the economist adds \u2014 three costs the environmentalists overlooked: a larger initial investment, a shortage of workers employable in rubber tapping, and higher taxes on rubber-tapping profits.\nSecond boldface \u2014 introduced by \"Consequently,\" so it is the economist's own conclusion: the environmentalists are probably wrong.\nSo \u2014 the first states their conclusion and the second states his, which is (D).\n(A) The first does not support the economist. He spends the rest of the passage arguing against it.\n(B) The first is not the economist's conclusion; the passage attributes it to the environmentalists in so many words.\n(C) Reverses which one is stated and which is supported \u2014 and the second is the economist's conclusion, not the environmentalists'.\n(E) Neither boldface is support. Both are conclusions, and they belong to opposing sides.\nAnswer: D." },
    { topic:"Boldface & method of reasoning", level:"medium", correct:"B", options:5,
      text:"Boreal owls range over a much larger area than do other owls of similar size. Scientists have hypothesized that [[it is scarcity of prey that leads the owls to range so widely]]. This hypothesis would be hard to confirm directly, since it is not possible to count the small mammals in the forests where boreal owls live. Careful study has shown that [[boreal owls do range over larger areas when they live in regions where food of the sort eaten by small mammals is comparatively sparse]]. This indicates that the scientists' hypothesis is not sheer speculation.\nThe two boldface portions play which of the following roles?",
      choices:["The first presents an explanatory hypothesis; the second states the main conclusion of the argument.","The first presents an explanatory hypothesis; the second presents evidence tending to support this hypothesis.","The first presents an explanatory hypothesis; the second presents evidence to support an alternative explanation.","The first describes a position the argument opposes; the second undermines support for that position.","The first describes a position the argument opposes; the second states the main conclusion."],
      hint:"The last sentence is the conclusion \u2014 so neither boldface can be it.",
      expl:"The main conclusion \u2014 the final sentence: the scientists' hypothesis is not sheer speculation.\nFirst boldface \u2014 the hypothesis itself, offered to explain why boreal owls range so much further than owls of similar size.\nSecond boldface \u2014 what careful study found: the owls do range further where food for small mammals is comparatively sparse. Since the prey cannot be counted directly, this is the indirect confirmation the argument needs.\nSo \u2014 a hypothesis, then evidence tending to support it, which is (B).\n(A) The conclusion is the last sentence, not the second boldface. The study finding is what the conclusion rests on.\n(C) The evidence supports [[this]] hypothesis. No alternative explanation appears anywhere in the passage.\n(D) The argument defends the hypothesis rather than opposing it \u2014 that is the point of the final sentence.\n(E) Wrong on both counts: the first is not opposed, and the second is not the conclusion.\nAnswer: B." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"A", options:5,
      text:"A prominent investor claims the Burton Tool Company is mismanaged, citing its failure to slow production after a rise in inventory of finished products. It is doubtful whether an investor's sniping at management can ever be productive, but in this case it is clearly not justified. It is true that [[an increased inventory of finished products often indicates that production is outstripping demand]], but in Burton's case it indicates no such thing. Rather, [[the increase in inventory is entirely attributable to products that have already been assigned to orders received from customers]].\nThe two boldface portions play which of the following roles?",
      choices:["The first states a generalization underlying the position the argument opposes; the second provides evidence that the generalization does not apply in this case.","The first states a generalization underlying the opposed position; the second clarifies the meaning of a phrase in that generalization.","The first supports the argument's conclusion; the second is evidence used to support the opposed position.","The first supports the argument's conclusion; the second states that conclusion.","Each provides evidence against the opposed position."],
      hint:"The word \u201coften\u201d marks a general rule. Ask what the second boldface does to that rule here.",
      expl:"The opposed position \u2014 the investor's charge that Burton is mismanaged for not slowing production as inventory rose.\nFirst boldface \u2014 the general rule that charge rests on: rising inventory of finished products often means production is outstripping demand. The author grants it (\"It is true that\u2026\").\nSecond boldface \u2014 why the rule does not reach Burton: the extra inventory is entirely assigned to orders already received, so it is not unsold surplus at all.\nSo \u2014 the generalization behind the opposed position, then evidence that it does not apply in this case, which is (A).\n(B) The second does far more than clarify a phrase. It supplies a fact that takes Burton out of the rule's scope.\n(C) The first belongs to the investor's side, not the author's. The author concedes it before turning it aside.\n(D) Same error about the first, and the conclusion is the earlier claim that the sniping is not justified, not the inventory fact.\n(E) The first supports the opposed position rather than arguing against it \u2014 the author accepts it as generally true.\nAnswer: A." },
    { topic:"Boldface & method of reasoning", level:"medium", correct:"E", options:5,
      text:"Letter to the editor: Proposition Q would prohibit handgun ownership in the city. Proponents argue that [[fewer handguns on the streets would lead to less violent crime]]. Unfortunately, the ban would actually have the opposite effect. Since only law-abiding citizens would honour the ban, [[armed criminals would not only keep their weapons but would also have the confidence to act with impunity on a population that could no longer defend itself]].\nThe two boldface portions play which of the following roles?",
      choices:["The first is an observation the author uses to support a position; the second is that position.","The first is a pattern of cause and effect the author believes true; the second offers evidence to contradict it.","The first is a position the author argues will not hold; the second is the author's position.","The first is a prediction the author believes untrue; the second undermines the author's position.","The first is a direct relationship the author believes will not hold in this case; the second offers evidence in support of the author's position."],
      hint:"\u201cUnfortunately, the ban would actually have the opposite effect\u201d tells you what the author does with the first boldface.",
      expl:"First boldface \u2014 the proponents' claimed cause and effect: fewer handguns on the streets means less violent crime. The author denies it will hold in this case.\nThe author's position \u2014 the sentence between the boldfaces: the ban would have the opposite effect.\nSecond boldface \u2014 why: only law-abiding citizens would honour the ban, so armed criminals would keep their weapons and face a population that could no longer defend itself. That is support for the author's position, not the position itself.\nSo \u2014 a relationship the author says will not hold, then evidence for the author's view, which is (E).\n(A) The author rejects the first rather than using it, and the second is support rather than the position.\n(B) The author does not believe the first pattern will hold here \u2014 that is precisely what \"the opposite effect\" denies.\n(C) Right about the first, wrong about the second: the author's position was stated separately, between the two boldfaces.\n(D) The second supports the author's position; it does not undermine it.\nAnswer: E." },
    { topic:"Boldface & method of reasoning", level:"medium", correct:"B", options:5,
      text:"Traditionally, video-game manufacturers have been most strongly influenced by serious gamers. Because devoted gamers have historically purchased most games, [[most manufacturers continue to produce games with faster chips and flashier graphics]]. Unfortunately, faster chips and flashier graphics are no longer in the industry's best interest. The devoted gaming market is stagnant and won't soon expand. To infuse new life into the market, manufacturers must simplify the functionality of their games, because [[current non-gamers will then be attracted to join the ranks of video-game fans]].\nThe two boldface portions play which of the following roles?",
      choices:["The first is a situation the author believes true; the second explains it.","The first is a situation the author argues should not continue; the second supports the author's position.","The first is a fact that contradicts the author's position; the second is the author's position.","The first supports the author's position; the second weighs against it.","The first is a prediction the author rejects; the second is an assumption against the author's position."],
      hint:"\u201cNo longer in the industry's best interest\u201d tells you how the author regards the first boldface.",
      expl:"First boldface \u2014 what manufacturers currently do: keep producing games with faster chips and flashier graphics. The very next sentence calls this no longer in the industry's interest, so it is a practice the author wants stopped.\nThe author's recommendation \u2014 simplify the functionality of games to bring in new players.\nSecond boldface \u2014 current non-gamers would then be attracted in. That is the reason the recommendation would work.\nSo \u2014 a practice the author argues should not continue, then support for the author's position, which is (B).\n(A) The second explains why the [[recommendation]] would succeed, not why the current practice exists.\n(C) The author's position is the recommendation to simplify, not the claim about attracting non-gamers, which is its support.\n(D) Reverses both. The first works against the author's proposal and the second works for it.\n(E) The first is a description of current practice, not a prediction; and the second is the author's own support, not an assumption against him.\nAnswer: B." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"D", options:5,
      text:"Marketing analyst: [[Traditionally, introducing a new consumer product contributes to the diversity of a company's product mix and results in an overall increase in revenues and profits.]] However, our launch of Cool Breeze will almost certainly reduce rather than increase profits. Since we already offer a line of chilled refreshments very similar to Cool Breeze, [[the launch is likely to cannibalize our current sales rather than attract new customers]].\nThe two boldface portions play which of the following roles?",
      choices:["The first is a pattern the analyst predicts will be repeated here; the second acknowledges a circumstance in which it would not hold.","The first is a generalization the analyst accepts as true; the second is a consequence that follows from it.","The first acknowledges a consideration against the analyst's conclusion; the second is that conclusion.","The first is a pattern of cause and effect the analyst predicts will not hold in this case; the second offers a consideration in support of that prediction.","The first is evidence for a prediction; the second is that prediction."],
      hint:"\u201cHowever\u201d right after the first boldface is the signal \u2014 the usual pattern is about to be denied.",
      expl:"First boldface \u2014 the traditional pattern: a new product diversifies the mix and lifts revenue and profit.\nThe turn \u2014 \"However\" reverses it. The analyst predicts the Cool Breeze launch will [[reduce]] profits, so the traditional pattern will not hold here.\nSecond boldface \u2014 the reason: an existing line of very similar chilled refreshments means the launch will cannibalize current sales rather than attract new customers.\nSo \u2014 a pattern predicted not to hold, then a consideration supporting that prediction, which is (D).\n(A) Reversed. The analyst denies the pattern will be repeated, and the second boldface backs that denial rather than qualifying it.\n(B) The analyst accepts the generalization as a rule of thumb but denies it applies here, so the second is not a consequence flowing from it.\n(C) The conclusion is that profits will fall. The cannibalization claim is the support for it.\n(E) The first cuts against the prediction rather than supporting it, and the second is not the prediction.\nAnswer: D." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"B", options:5,
      text:"Editorial: An arrest in Midville is provisional until a watch commander approves it. A government efficiency expert found that almost all provisional arrests meet the evidence standards commanders enforce. [[The expert therefore recommends that the watch commander's approval should no longer be required, since the officers' time spent obtaining approval is largely wasted.]] [[This recommendation should be rejected as dangerous]], since there is no assurance that the commanders' standards will continue to be observed once approval is no longer required.\nThe two boldface portions play which of the following roles?",
      choices:["The first is a recommendation made by the editorial; the second acknowledges a potential objection to it.","The first is a proposal against which the editorial is directed; the second is a judgment reached by the editorial about that proposal.","The first provides evidence for a recommendation the editorial supports; the second is the editorial's conclusion.","The first is a position the editorial challenges; the second is a judgment made in support of that challenged position.","The first is a recommendation the editorial questions; the second provides evidence against it."],
      hint:"\u201cThis recommendation should be rejected\u201d is the editorial speaking \u2014 so the recommendation is not the editorial's own.",
      expl:"First boldface \u2014 the efficiency expert's recommendation: drop the watch commander's approval requirement, since the officers' time is largely wasted.\nSecond boldface \u2014 the editorial's verdict on it: the recommendation should be rejected as dangerous.\nThe editorial's reason \u2014 after \"since\": nothing guarantees that commanders' standards would still be observed once approval is no longer required.\nSo \u2014 a proposal the editorial is directed against, then the editorial's judgment about that proposal, which is (B).\n(A) The recommendation belongs to the expert. The editorial's own words are \"This recommendation should be rejected.\"\n(C) The editorial opposes the proposal rather than supporting it.\n(D) Right about the first, wrong about the second: the editorial's judgment attacks the challenged position, it does not support it.\n(E) The second is the editorial's conclusion, not evidence. The evidence is the clause after \"since.\"\nAnswer: B." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"B", options:5,
      text:"[[During the past year, Pro-Tect Insurance's total payout on car-theft claims has been larger than the company can afford to sustain.]] Pro-Tect cannot reduce the number of car-theft policies it carries. Therefore it has decided to offer a discount to policyholders whose cars have antitheft devices. Many policyholders will install such devices, since the discount will typically more than cover the cost within two years. Thus, because cars with antitheft devices are rarely stolen, [[Pro-Tect's plan is likely to reduce its annual payouts]].\nThe two boldface portions play which of the following roles?",
      choices:["Each is evidence offered in support of the main conclusion.","The first presents a problem a response to which the argument assesses; the second is the judgment reached by that assessment.","The first is the position the argument seeks to establish; the second supports that position.","The first is a development the argument seeks to explain; the second is a prediction supporting that explanation.","The first presents a development whose outcome is at issue; the second is a judgment used in support of the conclusion."],
      hint:"The first boldface is the situation that prompts the plan; ask what the argument then does about the plan.",
      expl:"First boldface \u2014 the problem: payouts on car-theft claims are larger than Pro-Tect can afford to sustain.\nThe response \u2014 since the number of policies cannot be cut, the company offers a discount to policyholders who install antitheft devices, which will pay for itself within about two years.\nSecond boldface \u2014 the argument's verdict on that response: the plan is likely to reduce annual payouts.\nSo \u2014 a problem, then the judgment reached about the response to it, which is (B).\n(A) The second is the conclusion, so it cannot be evidence for one. Everything else in the passage is aimed at it.\n(C) Reversed. The first is the situation the plan addresses; the conclusion comes at the end.\n(D) The argument never explains why payouts rose. It takes the problem as given and evaluates a fix.\n(E) Right about the first, wrong about the second \u2014 it is the conclusion itself, not support for one.\nAnswer: B." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"C", options:5,
      text:"Rain-soaked soil contains less oxygen than drier soil. Melon roots perform less efficiently in low-oxygen conditions, and then do not supply enough nutrients for photosynthesis at the usual level. [[It follows that melon plants have a lower-than-usual rate of photosynthesis when their roots are in rain-soaked soil.]] When photosynthesis slows, sugar stored in the fruits is drawn off to supply the plants with energy. Therefore, [[ripe melons harvested after a prolonged period of heavy rain should be less sweet than other ripe melons]].\nThe two boldface portions play which of the following roles?",
      choices:["The first states the conclusion of the argument as a whole; the second supports it.","The first supports the overall conclusion; the second supports an objection to it.","The first is an intermediate conclusion that supports a further conclusion; the second states that further conclusion.","The first is an intermediate conclusion supporting a further conclusion; the second states the position the argument opposes.","The first states the position the argument opposes; the second supports the conclusion."],
      hint:"\u201cIt follows that\u201d and \u201cTherefore\u201d each mark a conclusion \u2014 so this argument has two.",
      expl:"First boldface \u2014 introduced by \"It follows that,\" and drawn from the two preceding facts: rain-soaked soil holds less oxygen, and roots in low-oxygen conditions cannot supply enough nutrients. The conclusion is a lower-than-usual rate of photosynthesis.\nWhat follows it \u2014 slowed photosynthesis draws stored sugar out of the fruit to supply energy.\nSecond boldface \u2014 introduced by \"Therefore,\" and it is where the argument stops: melons harvested after prolonged heavy rain should be less sweet.\nSo \u2014 an intermediate conclusion supporting a further conclusion, then that further conclusion, which is (C).\n(A) The first is not the overall conclusion. The argument keeps going, and \"Therefore\" arrives later.\n(B) No objection is raised anywhere. Both boldfaces sit on the same side.\n(D) Right about the first, wrong about the second \u2014 the argument asserts the sweetness claim rather than opposing it.\n(E) Reverses the argument entirely. The first is derived, not opposed.\nAnswer: C." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"B", options:5,
      text:"Plant scientists have used genetic engineering on seeds to produce crop plants highly resistant to insect damage. [[Unfortunately, the seeds are expensive, and the plants require more fertilizer and water.]] Consequently, for most farmers the savings on pesticides cannot compensate for the higher costs. However, since [[consumer demand for produce grown without pesticides continues to rise]], the use of these genetically engineered seeds is likely to become widespread.\nThe two boldface portions play which of the following roles?",
      choices:["The first provides evidence supporting the argument's main conclusion; the second states that conclusion.","The first supports an intermediate conclusion that weighs against the argument's final prediction; the second supports that prediction.","The first states the argument's main conclusion; the second provides evidence for it.","The first describes a development the argument predicts; the second acknowledges an objection to that prediction.","Each provides evidence supporting the argument's main conclusion."],
      hint:"The two boldfaces pull in opposite directions \u2014 sort out which one the final prediction rests on.",
      expl:"The main conclusion \u2014 the final clause: use of these genetically engineered seeds is likely to become widespread.\nFirst boldface \u2014 the seeds are expensive and the plants need more fertilizer and water. This supports the claim that follows it: for most farmers the savings on pesticides will not compensate. That intermediate claim cuts [[against]] the final prediction.\nSecond boldface \u2014 after \"However,\" the argument turns: consumer demand for produce grown without pesticides keeps rising. That is why the prediction holds anyway.\nSo \u2014 the first supports something weighing against the prediction, and the second supports the prediction, which is (B).\n(A) The first works against the conclusion, not for it, and the second is support rather than the conclusion.\n(C) The first is a cost detail feeding an intermediate claim; the conclusion is the last clause.\n(D) The argument predicts widespread use, not high costs, and the second boldface is the reason for the prediction rather than an objection to it.\n(E) Only one of them supports the conclusion. Treating both the same way misses the \"However.\"\nAnswer: B." }
  ]}

  ];
})();
