/* GMAT Prep — new Reading-Comprehension passage sets, transcribed from the
   user's Drive "GMAT RC + CR Session" documents (Sessions 1-6). Each object is
   a complete practice set (passage + questions) and is appended to
   window.GMAT_SETS at load time via the merge in index.html. Answer keys are
   taken from the source answer keys and checked against the passage.
   Set shape matches sets.js: { id, title, section, source, passage:{title,paras[]}, questions:[...] } */
(function () {
  var Q = function (n, topic, correct, text, choices, hint, expl, level) {
    return { n: n, topic: topic, correct: correct, options: choices.length, level: level || "medium", text: text, choices: choices, hint: hint, expl: expl };
  };

  window.GMAT_SETS_NEW = [

  { id:"rc-ss-downsizing", title:"Passage — Downsizing as Business Myth", section:"rc", source:"RC+CR Session 1",
    passage:{ title:"Downsizing as Business Myth", paras:[
      "Firms traditionally claim that they downsize (i.e., make permanent personnel cuts) for economic reasons, laying off supposedly unnecessary staff in an attempt to become more efficient and competitive. Recent research has shown that the actual economic effects of downsizing are often negative for firms; to this effect, organization theory, the economic explanation traditionally offered for downsizing, cannot adequately explain downsizing; one non-economic explanation must also be considered; that non-economic explanation is the evolution of downsizing into a powerful business myth: managers simply believe that downsizing is efficacious.",
      "Moreover, downsizing nowadays is greeted favorably by the business press; the press often refers to soaring stock prices of downsizing firms. Once viewed as a sign of desperation, downsizing is now viewed as a signal that firms are serious about competing in the global marketplace; such signals are received positively by key actors—financial analysts, consultants, and shareholders—who supply firms with vital organizing resources. Thus, even if downsizing is not economically more efficient, downsizing's mythic properties have, over many decades, continued to give it added prestige in the business community and continued to enhance the survival prospects of firms engaging in downsizing." ]},
    questions:[
      Q(1,"Main idea / primary purpose","C","The primary purpose of the passage is to",
        ["criticize firms for engaging in the practice of downsizing","analyze the negative economic impact of downsizing on firms","offer an alternative to a traditional explanation for the occurrence of downsizing","chronicle how perceptions of downsizing have changed over time","provide evidence disputing the prevalence of downsizing"],
        "The passage says the economic explanation is inadequate and adds a non-economic one.",
        "The author argues that the traditional economic explanation is insufficient and offers a non-economic alternative — downsizing as a business myth. Answer: C.","medium") ]},

  { id:"rc-ss-corp-sanctions", title:"Passage — Criminal Sanctions on Corporations", section:"rc", source:"RC+CR Session 1",
    passage:{ title:"Criminal vs. Civil Liability for Corporations", paras:[
      "The use of criminal sanctions against corporations is well established, but the practice has recently come under fire from legal theorists who maintain that corporations should be held civilly, rather than criminally, liable for wrongdoing. They claim civil liability is better able to determine appropriate levels of damages.",
      "Criminal liability is a much stronger deterrent, however. The considerable enforcement powers involved, including the ability to detain and question corporate officials, are themselves significant deterrents. Furthermore, the fact that private civil litigation requires an identifiable victim with the necessary resources to commence litigation weakens its deterrent impact. Most importantly, the main function of criminal law is to censure wrongdoing and to emphasize that society forcefully rejects such conduct. Civil liability is ill-suited for this purpose.",
      "Other legal theorists who do not object to criminal sanctions per se argue that individuals within corporations, rather than corporations themselves, are the appropriate target of criminal prosecution in cases involving corporate wrongdoing. They maintain that individuals within corporations are more responsive to deterrence because they generally fear prosecution and the loss of employment that can result from it.",
      "However, this approach is also misguided. Corporations often bury responsibility within complex hierarchies, with the result that no specific individual responsible for corporate misdeeds can ever be identified. The more effective way to ensure that corporations improve their practices is to hold corporations themselves criminally liable for their conduct." ]},
    questions:[
      Q(1,"Main idea / primary purpose","E","Which one of the following most accurately expresses the main point of the passage?",
        ["While civil sanctions against corporations would be more cost-effective than criminal sanctions, it is difficult to identify victims of corporate wrongdoing who have the resources to file civil suits.","Neither criminal sanctions against corporations nor criminal sanctions against individuals within corporations are capable of deterring corporate wrongdoing.","The best way to ensure that corporations improve their practices is to use civil sanctions against both corporations and individuals within corporations.","The use of criminal sanctions against individuals within corporations is preferable to the use of civil sanctions because the latter fails to censure wrongdoing adequately.","Although the use of criminal sanctions against corporations has recently faced criticism, it remains a more effective way of deterring corporate wrongdoing."],
        "Track the author's own position across the two rebuttals.",
        "The author rebuts both the civil-liability view and the target-individuals view, concluding that criminal sanctions against corporations remain the most effective deterrent. Answer: E.","medium") ]},

  { id:"rc-ss-birds", title:"Passage — Did Birds Evolve from Dinosaurs?", section:"rc", source:"RC+CR Session 1",
    passage:{ title:"Birds and Theropod Dinosaurs", paras:[
      "Many lines of evidence convincingly indicate that birds evolved from ground-dwelling theropod dinosaurs, but some scientists remain unconvinced. They argue that theropods appeared too late to have given rise to birds, noting that Archaeopteryx lithographica—the oldest known bird—appears in the fossil record about 150 million years ago, whereas the fossil remains of various non-avian maniraptor theropods—the closest known relatives of birds—date only to about 115 million years ago. But investigators have now uncovered bones that evidently belong to non-avian maniraptors dating to the time of Archaeopteryx. Some other skeptical scientists also argue that the fused clavicles (the \"wishbone\") of birds differ from the unfused clavicles of theropods, but fossilized theropod clavicles that look just like the wishbone of Archaeopteryx have been unearthed. Finally, some scientists argue that the complex lungs of birds could not have evolved from theropod lungs, but this assertion cannot be supported or falsified at the moment, because no fossil lungs are preserved in the paleontological record." ]},
    questions:[
      Q(1,"Main idea / primary purpose","E","The primary purpose of the passage is to",
        ["compare the development of three hypotheses concerning the evolutionary origin of birds","suggest revisions to the standard theories of the evolutionary history of birds","evaluate the usefulness of fossil evidence in determining the evolutionary history of birds","challenge the theory that birds evolved from ground-dwelling theropod dinosaurs","respond to the three categories of skeptics of the theory that birds evolved from ground-dwelling theropod dinosaurs"],
        "Notice the passage takes up three skeptics' arguments one by one.",
        "The author supports the bird–theropod theory and answers three skeptical objections in turn (timing, clavicles, lungs). Answer: E.","medium") ]},

  { id:"rc-ss-impressionism", title:"Passage — Impressionism and Light", section:"rc", source:"RC+CR Session 1",
    passage:{ title:"The Philosophy of Impressionism", paras:[
      "The Impressionist painters expressly disavowed any interest in philosophy, yet their new approach to art had far-reaching philosophical implications. The view of matter that the Impressionists assumed differed profoundly from the view that had previously prevailed among artists. This view helped to unify the artistic works created in the new style.",
      "The ancient Greeks had conceived of the world in concrete terms. This Greek view of matter persisted, so far as painting was concerned, into the nineteenth century. The Impressionists, on the other hand, viewed light, not matter, as the ultimate visual reality. The philosopher Taine expressed the Impressionist view of things when he said, \"The chief 'person' in a picture is the light in which everything is bathed.\"",
      "The Impressionist world was composed not of objects but of many surfaces on which light struck and was reflected with varying intensity to the eye through the atmosphere. \"Light becomes the sole subject of the picture,\" writes Mauclair. \"The object upon which it plays is immaterial. Painting thus becomes a purely optic art.\"",
      "From this profoundly revolutionary form of art, all ideas—religious, moral, psychological—were excluded, and so were all emotions. The people, places, and things depicted in an Impressionist picture do not matter, tell any story, or convey any special meaning; they are, instead, merely parts of a pattern of light drawn from nature and captured on canvas by the artist." ]},
    questions:[
      Q(1,"Main idea / primary purpose","B","The author of the passage is primarily concerned with",
        ["justifying how the Impressionists were influenced by scientific studies of light and color","discussing the philosophical implications of the Impressionist style of painting","validating the revolutionary artistic techniques developed by the Impressionist painters","evaluating the influence of thinkers like Taine and Mauclair on Impressionist painting","defending the importance of the Impressionist painters in the history of modern art"],
        "The opening sentence frames the whole passage.",
        "The passage explores the philosophical implications of Impressionism's view of matter and light, as previewed in the first sentence. Answer: B.","medium"),
      Q(2,"Function / purpose of detail","D","The author's quotation of a statement by Taine serves which of the following functions in the passage?",
        ["It furnishes a specific example of an Impressionist painting that features light as its chief subject.","It resolves an apparent contradiction in the philosophy of the Impressionists.","It challenges the statement that the ancient Greeks viewed the world in abstract terms.","It summarizes the perspective that the Impressionists brought to painting.","It provides a specific example of the far-reaching philosophical implications of Impressionism."],
        "What does the Taine quote actually say?",
        "Taine's line — light is the 'chief person' in a picture — encapsulates the Impressionist view the paragraph is describing. Answer: D.","medium"),
      Q(3,"Inference","C","The ideas attributed to the Impressionists in the passage suggest that an Impressionist painter would be most likely to agree with which of the following?",
        ["A picture is significant primarily as a manifestation of the artist's mental state.","The highest purpose of art is to teach religious truths.","Impressionism doesn't bother about the objects depicted in the painting, rather it bothers only about light and optics.","An artist should strive to recreate on canvas the inner nature of people from real life.","It is useful to attempt to paint pictures that aim to copy various religious teachings of the world."],
        "The final paragraph excludes ideas, emotions, and story.",
        "For the Impressionists the object is 'immaterial'; only light matters, and all ideas/emotions are excluded. Answer: C.","medium") ]},

  { id:"rc-ss-scavengers", title:"Passage — Were Early Hominids Scavengers?", section:"rc", source:"RC+CR Session 5",
    passage:{ title:"Darwin's Hunters vs. the Taphonomy Evidence", paras:[
      "Darwin's conception of early prehistoric humans as confident, clever hunter-gatherers has long dominated anthropology. His theory has been reinforced by an accident of history: the human fossil record has been found largely in reverse order. Remains of humans' most recent forebears, who lived 35,000 to 100,000 years ago, were discovered in 1856; over the next century, discoveries yielded fossils of hominids from progressively earlier eras. Because the first-discovered fossil hominids, the Neanderthals, genuinely resembled modern humans, anthropologists from Darwin on have confused the life-styles of today's nonindustrial peoples with those of our distant hominid forebears. These anthropologists have failed to consider both the sophistication of modern hunter-gatherer societies (including their use of fire, clothing, shelter, weapons, tools, language, and complex strategies) and the ways in which their environments differ from prehistoric ones (for example, in containing fewer large animal predators).",
      "Recent intellectual developments, such as the new field of taphonomy, have called into question the traditional hypothesis that early hominids outsmarted the predators with whom they competed for meat and that they mastered their world through hunting. Taphonomy investigates the transformation of skeletal remains into fossil—it asks, for example, whether bone piles have been deposited by predators, hunters, or floodwaters, and whether hyenas' teeth scar animal bones differently than do human tools. By comparing the microscopic features of linear grooves on the fossilized animal bones with similar grooves on modern bones, the researchers found that cut marks made by stone tools differed from the marks of other taphonomic agents, such as carnivores' teeth or sedimentary abrasion. They also found that the markings of stone tools on many of the fossilized animal bones did not occur systematically at the joints and that the toothmarks of animal carnivores often underlay rather than overlay the cut marks.",
      "The researchers hypothesized from this evidence that early hominids were scavengers of meat left from carnivore kills, rather than hunters of live prey. From patterns of wear on fossilized hominid teeth, the researchers further deduced that early hominids, like other scavengers, ate fruit primarily and meat only occasionally. Early hominids could have been well adapted for scavenging: agility in climbing trees helped them escape predators and gain superior vantage points, and an upright mode of walking enabled them to scan the ground for carcasses and to carry useful scavenging tools. According to these researchers Darwin's vision of early prehistoric hunters may be familiar and appealing, but the fossil record suggests a revised picture of less confident early hominids who often perched in trees and who foraged and scavenged alone or in small groups." ]},
    questions:[
      Q(1,"Main idea / primary purpose","D","The author's primary purpose in writing the passage is to",
        ["differentiate between outdated and contemporary research methods","expose the preconceptions behind previous research","present a narrative of how historical events might have unfolded","explain the basis for a revisionary approach to a subject","describe how a new theory has justified the traditional one"],
        "The passage explains why a new (scavenger) view is warranted.",
        "The passage lays out the evidence and reasoning behind a revised (scavenger) view of early hominids. Answer: D.","medium"),
      Q(2,"Inference","C","It can be inferred that the author would encourage the anthropologists mentioned to do which type of research on modern hunter-gatherer societies?",
        ["apply the methodologies of taphonomy to study these societies","investigate the similarities of life-styles and environments among the various societies","contrast the competition for food faced by these societies with the competition faced by prehistoric societies","examine the life-styles of hunter-gatherer societies who lived in the previous century","analyze how the world's increasing industrialization is changing the survival strategies used by these societies"],
        "The criticism was that anthropologists ignored environmental differences such as predators.",
        "The anthropologists failed to note that modern environments contain fewer large predators; the author would have them contrast that competition with prehistoric conditions. Answer: C.","medium"),
      Q(3,"Supporting detail","D","In reaching their conclusions, the researchers interpreted the taphonomic analysis of marks on animal fossils in which way?",
        ["The fact that the marks of stone tools did not occur at the joints indicated that early hominids hunted and butchered less skillfully than later hominids.","The fact that the marks of stone tools did not occur systematically indicated that early hominids might have been working hastily before rivals arrived.","The fact that the marks of stone tools overlay those of animal carnivores indicated that early hominids did not move quickly enough to hunt animals.","The fact that the toothmarks of animal carnivores underlay the marks of stone tools indicated that early hominids came upon remains of an animal already killed by a predator.","The fact that the toothmarks of animal carnivores accompanied the marks of stone tools indicated that both predators and hominids preferred large prey."],
        "Which mark was on top — tool or tooth?",
        "Carnivore toothmarks underlay (came before) the tool marks, implying hominids reached the carcass after a predator had killed it — i.e., scavenging. Answer: D.","hard"),
      Q(4,"Function / purpose of detail","B","The author cites the early hominid's \"upright mode of walking\" primarily in order to",
        ["counter anthropologists' previous hypotheses about how early hominids walked","provide an example of how the hominids were suited to their method of gathering food","explain why early hominids subsisted on a diet that included more fruit than meat","increase the reader's appreciation for the resemblance between early hominids and modern humans","contrast early hominids and other mammals with whom they competed in hunting live prey"],
        "The sentence lists adaptations for scavenging.",
        "Upright walking let hominids scan for carcasses and carry tools — an adaptation suiting them to scavenging. Answer: B.","medium"),
      Q(5,"Supporting detail","C","Each of the following is mentioned as determinable by taphonomic investigation into the marks on fossilized bones EXCEPT the",
        ["order in which certain marks were placed","characteristic physical differences among the marks","approximate age of fossils on which the marks are found","agents that have left the marks","similarities to marks on modern bones"],
        "Age-dating of the fossils is not attributed to taphonomy in the passage.",
        "Taphonomy is described as distinguishing agents, ordering marks, comparing to modern bones, and noting physical differences — but not dating the fossils. Answer: C.","hard") ]},

  { id:"rc-ss-seals", title:"Passage — Maternal Strategies of Seals", section:"rc", source:"RC+CR Session 2",
    passage:{ title:"Harbor Seals and Pinniped Maternal Strategies", paras:[
      "Until recently, zoologists believed that all species of phocids (true seals), a pinniped family, use a different maternal strategy than do otariids (fur seals and sea lions), another pinniped family. Mother otariids use a foraging strategy. They acquire moderate energy stores in the form of blubber before arriving at breeding sites and then fast for 5 to 11 days after birth. Throughout the rest of the lactation (milk production) period, which lasts from 4 months to 3 years depending on the species, mother otariids alternately forage at sea, where they replenish their fat stores, and nurse their young at breeding sites. Zoologists had assumed that females of all phocids species, by contrast, use a fasting strategy in which mother phocids, having accumulated large energy stores before they arrive at breeding sites, fast throughout the entire lactation period, which lasts from 4 to 50 days depending on the species. Recent studies on harbor seals, a phocid species, surprisingly found that lactating females commenced foraging approximately 6 days after giving birth and on average made 7 foraging trips during the remainder of their 24-day lactation period.",
      "The maternal strategy evolved by harbor seals may, however, have to do with their small size and the large proportion of their fat stores depleted in lactation. Harbor seals are small compared with other phocid species such as grey seals, northern elephant seals, and hooded seals, all of which are known to fast for the entire lactation period. Mother seals of these species use respectively 84 percent, 58 percent, and 33 percent of their fat stores during lactation. By comparison, harbor seals use 80 percent of their fat stores in just the first 19 days of lactation, even though they occasionally feed during this period. Since such a large proportion of their fat stores is exhausted despite feeding, mother harbor seals clearly cannot support all of lactation using only energy stored before giving birth. Though smaller than many other phocids, harbor seals are similar in size to most otariids." ]},
    questions:[
      Q(1,"Main idea / primary purpose","D","The primary purpose of the passage is to",
        ["present evidence that several phocid species use the maternal fasting strategy","explain why the maternal strategy typically used by phocids is different from the maternal strategy used by otariids","argue that zoologists' current understanding of harbor seals' maternal strategy is complete","describe an unexpected behavior observed in harbor seals and offer a probable explanation for that behavior","present evidence concerning the maternal strategy of the harbor seal and suggest that the harbor seal belongs to the otariid rather than to the phocid family"],
        "Paragraph 1 gives the surprising finding; paragraph 2 explains it.",
        "The passage reports a surprising foraging behavior in harbor seals and then offers a size/fat-depletion explanation. Answer: D.","medium") ]},

  { id:"rc-ss-blackhole", title:"Passage — Black Hole at the Galaxy's Center", section:"rc", source:"RC+CR Session 2",
    passage:{ title:"The Milky Way's Missing Energy", paras:[
      "This passage is excerpted from material published in 1997. Is there a massive black hole at the center of our galaxy, the Milky Way? Well, all the available evidence is dynamical, and hence inconclusive. This dynamical evidence argues for an extremely compact object with a mass three million times the mass of our Sun. Seemingly this should be a black hole, but the relative lack of energy radiating from the galactic center presents a serious problem in confirming this hypothesis. A black hole's gravity attracts surrounding matter, which swirls around the black hole, emitting energy as the matter is engulfed (the energy equivalent of its mass according to the equation E=mc2). But when the energy coming from the galactic center is measured and compared to the expected value of how much matter energy should be coming out as per the assumed mass that is being engulfed by the center of the dense object, there is a discrepancy (lack of energy) by a factor of a thousand, thus presenting us with the serious problem." ]},
    questions:[
      Q(1,"Main idea / primary purpose","D","The primary purpose of the passage is to",
        ["present several theories that could account for a particular phenomenon","argue that a certain question needs to be reframed in light of new evidence","resolve an apparent inconsistency between two lines of evidence","explain why a certain issue remains unresolved because of inconclusive evidence","present conclusive evidence that calls into question certain fundamentals of a current theory"],
        "Note the words 'inconclusive' and 'serious problem'.",
        "The passage explains why the black-hole hypothesis is unconfirmed: the evidence is inconclusive and there is an energy discrepancy. Answer: D.","medium"),
      Q(2,"Inference","A","The \"serious problem\" referred to could be solved if which of the following were true?",
        ["Current assumptions about how much matter a black hole would engulf proved to be a thousand times too high.","Current assumptions about how much matter a black hole would engulf proved to be a thousand times too low.","The object at the center of the Milky Way turned out to be far denser than it is currently estimated to be.","The object at the center of the Milky Way turned out to be far more massive than it is currently estimated to be.","Matter being engulfed by a black hole radiated far more energy than is currently assumed."],
        "The measured energy is 1,000× lower than expected — how could expectation fall to match it?",
        "If far less matter is being engulfed than assumed (a thousand times too high an estimate), the expected energy drops to match the low measured energy, resolving the discrepancy. Answer: A.","hard") ]},

  { id:"rc-ss-14thamend", title:"Passage — The Fourteenth Amendment", section:"rc", source:"RC+CR Session 2",
    passage:{ title:"Civil Rights and the Fourteenth Amendment", paras:[
      "The Fourteenth Amendment to the United States Constitution, passed in 1868, prohibits the American government from denying citizens the \"equal protection of the laws.\" The Fourteenth Amendment thus provided a constitutional warrant for the Congressional Civil Rights Act of 1866, which guaranteed citizenship to all persons born in the United States. The Civil Rights Act, which was echoed in the text of the Fourteenth Amendment, was designed primarily to challenge the Supreme Court's ruling in Dred Scott v. Sandford that Black people in the United States could be denied citizenship. The Civil Rights Act was unjustifiably vetoed by President Andrew Johnson, an action that forced the Congress to put the contents of the Civil Rights Act into the Fourteenth Amendment, thus ensuring the constitutional foundations of the Act and also ensuring indemnity for the Act against any future President's whims." ]},
    questions:[
      Q(1,"Supporting detail","D","Which of the following most accurately indicates the sequence of these events: I. Civil Rights Act of 1866  II. Dred Scott v. Sandford Case  III. Fourteenth Amendment  IV. Veto by President Johnson?",
        ["I, II, III, IV","I, IV, II, III","I, IV, III, II","II, I, IV, III","III, II, I, IV"],
        "Dred Scott prompted the Act; the veto forced the Amendment.",
        "Dred Scott (II) came first, prompting the 1866 Civil Rights Act (I); Johnson's veto (IV) forced Congress to enact the Fourteenth Amendment (III). Order: II, I, IV, III. Answer: D.","medium"),
      Q(2,"Inference","A","The author implies that the Fourteenth Amendment might not have been enacted if",
        ["Congress' authority with regard to the Civil Rights Act had not been challenged by the president","the framers had annulled the Court's ruling in Dred Scott v. Sandford","the framers had believed that it would be used in deciding cases of discrimination involving non-racial groups","most state governments had been willing to protect citizens' civil rights","its essential elements had not been implicit in the Thirteenth Amendment"],
        "What 'forced' Congress to write the Amendment?",
        "The passage says Johnson's veto forced Congress to embed the Act in the Amendment; without that challenge, the Amendment might not have been enacted. Answer: A.","medium") ]},

  { id:"rc-ss-patents", title:"Passage — Early American Patent Law", section:"rc", source:"RC+CR Session 2",
    passage:{ title:"Were Early American Judges Antipatent?", paras:[
      "Because the framers of the United States Constitution (written in 1787) believed that protecting property rights relating to inventions would encourage the new nation's economic growth, they gave Congress—the national legislature—a constitutional mandate to grant patents for inventions. The resulting patent system has served as a model for those in other nations. Recently, however, scholars have questioned whether the American system helped achieve the framers' goals. These scholars have contended that from 1794 to roughly 1830, American inventors were unable to enforce property rights because judges were \"antipatent\" and routinely invalidated patents for arbitrary reasons. This argument is based on examination of court decisions in 'patent-granting' cases before 1830. In the 1820s, for instance, 75 percent of verdicts were decided against the patent-applicants. The proportion of verdicts in favor of the patent-applicants began to increase in the 1830s, suggesting to these scholars that judicial attitudes toward patent-granting began shifting then.",
      "However, the increase in the rate of verdicts in favor of patent-applicants cannot be used to gauge changes in judicial attitudes. If early judicial decisions were prejudiced against patent-applicants, one might expect that subsequent courts—clearly more supportive of patent rights—would reject the former legal precedents. But pre-1830 cases have been cited as frequently as later decisions, and in some cases even more frequently, and they continue to be cited today, clearly suggesting that the early decisions provided a lasting foundation for patent law. On the other hand, the proportion of judicial decisions in favor of patent-applicants began to increase during the 1830s because of a change in the underlying population of cases brought in front of the judges. This change was due to an 1836 revision to the patent system: an examination procedure, still in use today, was instituted in which each application is scrutinized for its adherence to patent law." ]},
    questions:[
      Q(1,"Inference","E","In the last sentence, the author implies that the reason the proportion of verdicts in favor of patent-applicants began to increase in the 1830s was that",
        ["the number of cases in favor of patent-applicants began to increase after 1836","judges became less prejudiced against patent-applicants during the 1830s","patent laws enacted during the 1830s better defined patent rights","after 1836, litigated cases became less representative of the population of patent-granting cases","patent applications approved after 1836 were more likely to adhere closely to patent law"],
        "The 1836 examination screened applications before they reached court.",
        "After the 1836 examination procedure, only applications meeting patent law were approved, so litigated patents were stronger and more likely to win. Answer: E.","hard"),
      Q(2,"Inference","C","The scholars mentioned would agree with which criticism of the American patent system before 1830?",
        ["Its definition of property rights relating to inventions was too vague to be useful.","Its criteria for the granting of patents were not clear.","It failed to encourage national economic growth.","It made it excessively more difficult for inventors to receive patents compared to the previous era that existed before 1790.","It led to excessively large number of suits involving patent disputes."],
        "The scholars questioned whether the system met the framers' economic goal.",
        "The scholars 'questioned whether the American system helped achieve the framers' goals' — i.e., encourage economic growth. Answer: C.","hard"),
      Q(3,"Inference","D","The frequency with which pre-1830 cases have been cited is an indication that",
        ["judicial support for patent-granting was weaker in the period before 1830","judicial bias against patent-applicants didn't persist after 1830","the number of verdicts in favor of patent-applicants increased after 1830","judicial support for patent-granting did not increase after 1830","courts have not returned to judicial standards that prevailed before 1830"],
        "The author uses the citations to argue attitudes did NOT shift.",
        "The author argues that if attitudes had shifted, later courts would reject the old precedents; their continued citation shows judicial support did not actually increase. Answer: D.","hard"),
      Q(4,"Inference","D","The author and the scholars disagree about which aspect of the patent-granting suits before 1830?",
        ["Whether the patents were granted for inventions that were genuinely useful","Whether the patents were actually relevant to the growth of the United States economy","Whether the patents that were granted were likely to be annulled by judges in the future","Whether the patents were routinely invalidated for reasons that were arbitrary","Whether the number of patents granted was significantly lower than the number in later suits"],
        "The scholars said judges invalidated patents 'for arbitrary reasons'; the author explains the verdicts differently.",
        "The scholars claim judges arbitrarily invalidated patents; the author attributes verdicts to the weakness of the applications, so they disagree on the 'arbitrary' point. Answer: D.","hard"),
      Q(5,"Supporting detail","C","The author cites which of the following as evidence challenging the scholars' argument?",
        ["The number of cases that were decided against patent-applicants in the 1820s","The total number of patent cases that were brought to trial from 1794 to 1830","The fact that later courts drew upon the legal precedents from pre-1830 patent cases","The fact that the number of judicial decisions in favor of patent-applicants began to increase during the 1830s","The constitutional rationale for the 1836 revision of the patent system on part of the legislators"],
        "Which fact does the author use against the 'antipatent judges' claim?",
        "The author notes later courts kept citing pre-1830 cases as a lasting foundation — evidence against the claim that those decisions were biased. Answer: C.","medium") ]},

  { id:"rc-ss-warfilms", title:"Passage — Hollywood's Cycle of War Films", section:"rc", source:"RC+CR Session 3",
    passage:{ title:"The Cyclical Portrayal of War in Film", paras:[
      "Film scholars agree that Hollywood's portrayals of America at war follow a cyclical pattern. During and immediately after a war, Hollywood war films trumpet the glory of sacrifice and unquestioning patriotism. Ten to fifteen years later, however, morally fraught and pacifistic movies about the conflict dominate, movies that question everything, depicting moral ambiguities and confusions about the war, layered depictions of reality, and the horrors of combat. Audiences, in general, find these complex, ambiguous, and ambivalent visions of the war way less palatable than the one-sided, chest-thumping depictions of unbounded glory, sacrifice, and patriotism.",
      "Throughout the majority of the last century, evidence of the cyclical portrayal of war in film abounds. After America declared war against Germany during World War I, the still infant film industry glorified the fight against \"the Hun.\" By the early 1930's, major releases had changed their tone; for example, All Quiet on the Western Front put forth an anti-war message by displaying the horrors of combat. After World War II began, important movies again portrayed glories and courage without the ambiguities or despair. For example, Guadalcanal Diary, produced during the war, showed \"the ultimate sacrifice\" as a noble and undoubted good. Once again, though, by 1957, films such as The Bridge on the River Kwai won awards for depicting the moral confusion of war.",
      "In the late 1960's, \"the raging bulls\" of Hollywood proclaimed that this cyclical pattern had become obsolete. However, the passage of time has demonstrated this pattern to be more resilient than it seemed in the late 1960s. The production of, and then subsequent removal (before release) of a particular footage from the originally shot reel of Apocalypse Now further vindicated this pattern. Ten years later, the producers released the full movie and named it Apocalypse Now Redux; the new movie had the full 'originally-removed' footage; the producers had originally thought that the additional footage would, as usual, repel the audiences." ]},
    questions:[
      Q(1,"Supporting detail","B","According to the passage, Apocalypse Now Redux differed from Apocalypse Now in which way?",
        ["The removed footage in Apocalypse Now Redux made it less appealing to a more culturally diverse audience.","The added footage in Apocalypse Now Redux made its portrayal of war less glorified and more ambiguous.","The added footage in Apocalypse Now Redux made its portrayal of war more glorified.","The added footage in Apocalypse Now Redux made it more similar in tone to all the other war movies.","The added footage in Apocalypse Now made its portrayal of war less glorified and less appealing."],
        "The footage was originally cut because producers feared it would repel audiences.",
        "The restored footage was the ambiguous, less-glorified material the producers had feared would repel audiences. Answer: B.","medium"),
      Q(2,"Inference","E","The passage implies that the combat depicted in All Quiet on the Western Front least resembles the depiction of combat in which of the following?",
        ["The Hun","Apocalypse Now","The Bridge on the River Kwai","Apocalypse Now Redux","Guadalcanal Diary"],
        "All Quiet is anti-war; which listed film is pro-glory?",
        "All Quiet is anti-war/ambiguous; Guadalcanal Diary glorifies sacrifice, so it is the least similar. Answer: E.","medium"),
      Q(3,"Inference","D","Which one of the following does the author believe is true about The Bridge on the River Kwai?",
        ["It deserved the awards that it won.","It is a more intelligent and well-crafted movie than The Green Berets.","It was the first movie to portray the moral confusion of war.","Its portrayal of war is more ambiguous than that in Guadalcanal Diary.","It was more financially successful than any war movie that came before it."],
        "The passage groups Kwai with the 'moral confusion' films and Guadalcanal with the glory films.",
        "Kwai depicts moral confusion, while Guadalcanal Diary glorifies sacrifice, so Kwai is more ambiguous. Answer: D.","medium"),
      Q(4,"Function / purpose of detail","A","What is the function of the last paragraph of the passage?",
        ["It shows that the cyclical pattern discussed in the passage still continues.","It points out that the film industry never changes.","It shows that changes in the film industry and its audience have made the pattern previously discussed obsolete.","It discusses how Apocalypse Now and Apocalypse Now Redux were fundamentally different from all the other war movies that preceded them.","It demonstrates that war movies have changed dramatically to reflect the more culturally diverse audience."],
        "The paragraph rebuts the 1960s claim that the pattern was obsolete.",
        "The Apocalypse Now example shows the cycle persisted despite claims it was obsolete. Answer: A.","medium") ]},

  { id:"rc-ss-renaissance", title:"Passage — Did Women Have a Renaissance?", section:"rc", source:"RC+CR Session 3",
    passage:{ title:"Feminist Scholarship on Renaissance Women", paras:[
      "Jacob Burckhardt's view that Renaissance European women \"stood on a footing of perfect equality\" with Renaissance men has been rejected by feminist scholars, who wish to highlight an opposite notion: that of women's inequality with men during the aforementioned era. In striking contrast to Jacob Burckhardt, Joan Kelly in her famous 1977 essay, \"Did Women Have a Renaissance?\" argued that the Renaissance was a period of economic and social decline for women relative both to Renaissance men and to medieval women. Recently, however, a significant trend among feminist scholars has entailed a rejection of both Kelly's dark vision of the Renaissance and Jacob Burckhardt's rosy one. Many recent works by these scholars stress the ways in which differences among Renaissance women—especially in terms of social status and religion—work to complicate the kinds of generalizations both Jacob Burckhardt and Kelly made on the basis of their observations about upper-class Italian women.",
      "The trend is also evident, however, in works focusing on those middle- and upper-class European women whose ability to write gives them disproportionate representation in the historical record. Such women were, simply by virtue of their literacy, members of a tiny minority of the population, so it is risky to take their descriptions of their experiences as typical of \"female experience\" in any general sense. Tina Krontiris, for example, in her fascinating study of six Renaissance women writers, does tend at times to equate \"women\" and \"women writers,\" assuming that women's gender, irrespective of other social differences, including literacy, allows us to view women as a homogeneous social group and make that group an object of analysis. Nonetheless, Krontiris makes a significant contribution to the field and is representative of those authors who offer what might be called a cautiously optimistic assessment of Renaissance women's achievements, while also stressing the social obstacles Renaissance women faced whenever they wanted to raise their \"oppositional voices.\" Krontiris is concerned to show women wanting to, although unsuccessfully, negotiate some power for themselves against potentially constraining ideologies; in her concluding remarks, she suggests that such verbal opposition to cultural stereotypes was highly challenged; women could rarely attack the basic assumptions in the ideologies that oppressed them." ]},
    questions:[
      Q(1,"Supporting detail","C","Feminist scholars cite Burckhardt's view of Renaissance women primarily for which reason?",
        ["Burckhardt's view forms the basis for most arguments refuting Kelly's point of view.","Burckhardt's view has been discredited by Kelly.","Burckhardt's view is one that many feminist scholars wish to refute.","Burckhardt's work provides rich historical evidence of inequality between Renaissance women and men.","Burckhardt's work includes historical research supporting the arguments of most of the feminist scholars."],
        "See the first sentence.",
        "Feminist scholars cite Burckhardt's 'perfect equality' view as a position they wish to reject. Answer: C.","medium"),
      Q(2,"Inference","B","Both Burckhardt and Kelly have been criticized by the recent scholars for which of the following?",
        ["Assuming that women writers of the Renaissance are representative of Renaissance women in general","Drawing conclusions that are based on the study of an atypical group of women","Failing to describe clearly the relationship between social status and literacy among Renaissance women","Failing to acknowledge the role played by Renaissance women in opposing cultural stereotypes","Failing to acknowledge the ways in which social status affected the creative activities of Renaissance women"],
        "Both generalized from upper-class Italian women.",
        "Both based generalizations on observations of upper-class Italian women — an atypical group. Answer: B.","hard"),
      Q(3,"Inference","A","The author suggests that Krontiris incorrectly assumes that",
        ["social differences among Renaissance women are less important than the fact that they were women","literacy among Renaissance women was more prevalent than most scholars today acknowledge","during the Renaissance, women were able to successfully oppose cultural stereotypes relating to gender","Renaissance women did not face any social obstacles relating to their gender","in order to attain power, Renaissance women successfully attacked basic assumptions in the ideologies that oppressed them"],
        "Krontiris 'equates women and women writers'.",
        "The author faults Krontiris for treating gender as overriding other social differences — equating 'women' with 'women writers.' Answer: A.","hard"),
      Q(4,"Function / purpose of detail","C","The last paragraph in the passage serves primarily to",
        ["suggest that Krontiris's work is not representative of recent trends among feminist scholars","undermine the argument that literate women of the Renaissance wanted to oppose social constraints imposed on them","show a way in which Krontiris's work illustrates a \"cautiously optimistic\" assessment of Renaissance women's achievements","summarize Krontiris's view of the effect of literacy on the lives of upper- and middle-class Renaissance women","illustrate the way in which Krontiris's study differs from the studies done by Burckhardt and Kelly"],
        "Krontiris is called 'cautiously optimistic'.",
        "The paragraph uses Krontiris as an example of the cautiously optimistic assessment described. Answer: C.","medium"),
      Q(5,"Inference","D","The author implies that the women studied by Krontiris are unusual in which way?",
        ["They faced obstacles less formidable than those faced by all other Renaissance women.","They have been seen by historians as more interesting than all other Renaissance women.","They were more concerned about recording history accurately than were all other Renaissance women.","Their perceptions are more likely to be accessible to historians than are those of other Renaissance women.","Their concerns are likely to be of greater interest to feminist scholars than are the ideas of all other Renaissance women."],
        "Their literacy gives them 'disproportionate representation in the historical record.'",
        "Because these women could write, their experiences are disproportionately preserved and thus accessible to historians. Answer: D.","hard") ]},

  { id:"rc-ss-australopith", title:"Passage — Why Did Humans Walk Upright?", section:"rc", source:"RC+CR Session 3",
    passage:{ title:"Bipedalism and Australopithecus", paras:[
      "Anthropologists once thought that the ancestors of modern humans began to walk upright because it freed their hands to use stone tools, which they had begun to make as the species evolved a brain of increased size and mental capacity. But discoveries of the three-million-year-old fossilized remains of our hominid ancestor Australopithecus have yielded substantial anatomical evidence that upright walking appeared prior to the dramatic enlargement of the brain and the development of stone tools. Walking on two legs in an upright posture (bipedal locomotion) is a less efficient proposition than walking on all fours (quadrupedal locomotion) because several muscle groups that the quadruped uses for propulsion must instead be adapted to provide the biped with stability and control. The shape and configuration of various bones must likewise be modified to allow the muscles to perform these functions in upright walking.",
      "Reconstruction of the pelvis and femur of \"Lucy,\" a three-million-year-old skeleton that is the most complete fossilized skeleton from the Australopithecine era, has shown that they are much more like the corresponding bones of the modern human than like those of the most closely related living primate, the quadrupedal chimpanzee. Lucy's wide, shallow pelvis is actually better suited to bipedal walking than is the rounder, bowl-like pelvis of the modern human, which evolved to form the larger birth canal needed to accommodate the head of a large-brained human infant. By contrast, the head of Lucy's baby could have been no larger than that of a baby chimpanzee. If the small-brained australopithecines were not toolmakers, what evolutionary advantage did they gain by walking upright? One theory is that bipedality evolved in conjunction with the nuclear family: monogamous parents cooperating to care for their offspring. Walking upright permitted the father to use his hands to gather food and carry it to his mate from a distance, allowing the mother to devote more time and energy to nurturing and protecting their children. According to this view, the transition to bipedal walking may have occurred as long as ten million years ago." ]},
    questions:[
      Q(1,"Inference","C","The passage suggests that which of the following steps in human evolution occurred most recently?",
        ["Development of a nuclear family structure","Transition from walking on all fours to walking upright","Dramatic enlargement of the brain","Use of the hands to gather and carry food","Modification of propulsive muscles to provide stability and control in locomotion"],
        "Upright walking preceded the brain's enlargement.",
        "The passage states upright walking appeared before the brain's dramatic enlargement, making the enlargement the most recent of these steps. Answer: C.","medium"),
      Q(2,"Inference","E","The nuclear-family theory suggests that which of the following was true for the hominid ancestors before they made the transition to walking upright?",
        ["Their brains were smaller than the brains of present-day chimpanzees.","They competed rather than cooperated in searching for food.","Their mating patterns and family structure were closer to those of present-day chimpanzees than to those of modern humans.","Males played a more significant role in child rearing than they played after the transition to walking upright.","Females' ability to nurture and protect their offspring was limited by the need to find food for themselves."],
        "Bipedalism let the father carry food so the mother could focus on the young.",
        "The theory says upright walking freed the father to bring food so the mother could nurture; before that, females had to find their own food, limiting nurturing. Answer: E.","hard") ]},

  { id:"rc-ss-mooncore", title:"Passage — The Moon's Core", section:"rc", source:"RC+CR Session 4",
    passage:{ title:"Probing the Moon's Interior", paras:[
      "Before the age of space exploration, the size and composition of the Moon's core were astronomical mysteries. Astronomers assumed that the Moon's core was smaller than that of the Earth, in both relative and absolute terms—the radius of the Earth's core is 55 percent of the overall radius of the Earth and the core's mass is 32 percent of the Earth's overall mass—but they had no way to verify their assumption. However, data gathered by Lunar Prospector have now given astronomers the ability to determine that the Moon's core accounts for 20 percent of the Moon's radius and for a mere 2 percent of its overall mass.",
      "Two sets of data have been analyzed. As part of the Doppler Gravity Experiment, scientists measured minute, relatively rapid variations in the wavelength of radio signals from Lunar Prospector as the craft moved towards or away from the Earth. Just as shifts in the pitch of a siren can indicate the speed and direction of travel of a police car, so did these radio-signal variations reveal even the slightest changes in the craft's velocity while the craft orbited the Moon. These changes resulted from inconsistency in the gravitational pull of the Moon on the craft and permitted the creation of a \"gravity map\" of both near and far sides of the Moon, highlighting new details of the distribution of the Moon's internal mass. Through the analysis of lunar mass concentrations, scientists have been able to determine that the Moon has a small, metallic core, which, if composed mostly of iron, has a radius of approximately 350 kilometers. The second data set was gathered by capturing echoes of the faint magnetic field generated by electrical currents within the lunar core caused by the Moon's monthly passage through the Earth's magnetosphere. These magnetic data confirmed the results obtained through examination of the gravity map.",
      "The size and composition of the Moon's core are not academic concerns; they have serious implications for our understanding of the Moon's origins. For example, if the Moon and Earth developed as distinct entities, the sizes of their cores should be more comparable. In actuality, it seems that the Moon was once part of the Earth and broke away at an early stage in the Earth's evolution, perhaps as the result of a major asteroid impact. The impact could have loosened iron that had not already sunk to the core of the Earth, allowing it to form the core around which the Moon eventually accreted. Alternatively, according to fission theory, the early Earth may have been spinning so rapidly that it ejected a quantity of material by so-called centrifugal force, material that later coalesced into the Moon." ]},
    questions:[
      Q(1,"Function / purpose of detail","C","The author mentions \"gravity map\" in the second paragraph in order to",
        ["illustrate the method used to correct the Lunar Prospector's velocity","confirm the results obtained by examining the Moon's magnetic field","describe a step in the investigation of the composition of the Moon's mass","detail a step in the investigation of the effects of gravity on the Moon and the Earth","confirm a new hypothesis and discard an older theory"],
        "The gravity map is one of two methods used to probe the Moon's core.",
        "The gravity map is described as a step in determining the Moon's internal mass distribution and core. Answer: C.","medium"),
      Q(2,"Inference","C","If the wavelength of radio signals from a second Lunar Prospector changed only in a slowly oscillating fashion, which could most properly be inferred?",
        ["The velocity of the second spacecraft will appear to be constant over time.","The size and mass of the Moon's core may be more comparable to the size and mass of the Earth's core than is currently believed.","The gravitational pull of the Moon would seem to be more uniform than was measured by the first spacecraft.","The Earth and the Moon would seem to have originated independently.","It would be impossible to create a gravity map of the Moon."],
        "Rapid wavelength variations reflected uneven gravity; slow oscillation implies the opposite.",
        "Rapid variation revealed uneven gravitational pull; a slow, smooth oscillation would indicate a more uniform pull. Answer: C.","hard"),
      Q(3,"Supporting detail","B","According to the passage, electrical currents within the Moon's core",
        ["capture echoes of a faint electric field","are generated when the Moon moves through the Earth's magnetosphere","call the results of the radio signal analysis into question","permit the creation of a wavelength map corresponding to lunar mass concentrations","indicate the speed and direction of travel of the Moon"],
        "Reread the sentence describing the magnetic data.",
        "The currents are generated by the Moon's monthly passage through the Earth's magnetosphere. Answer: B.","medium"),
      Q(4,"Supporting detail","D","Scientists employed one research method that measured",
        ["changes in a spacecraft's velocity as it returned to Earth","changes in the gravitational pull on the Lunar Prospector as it orbited the moon","changes in the moon's gravity as it orbited the earth","changes in a spacecraft's radio signals' wavelength as it changed position relative to the earth","changes in the moon's gravitational pull over time"],
        "The Doppler experiment measured radio-signal wavelength shifts.",
        "The Doppler Gravity Experiment measured variations in the wavelength of radio signals as the craft moved toward/away from Earth. Answer: D.","medium"),
      Q(5,"Inference","A","It can be inferred from the passage that",
        ["the earth's core contributes a higher proportion of both the earth's total radius and its total mass than the core of the moon contributes to its own total radius and mass","a comparison of the earth's and moon's cores suggests that the earth did break away from the moon","scientists will eventually be able to use the gravity map to further prove that a major asteroid impact caused the earth and moon to separate","because the earth and moon were once joined, it is probable that scientists will eventually discover evidence on the moon that a major asteroid impact caused the extinction of the dinosaurs","the moon's core has a higher ratio of iron in its composition than does the earth's"],
        "Compare the given percentages: Earth 55%/32% vs Moon 20%/2%.",
        "Earth's core is 55% of radius and 32% of mass; the Moon's is 20% and 2% — a higher proportion on both counts for Earth. Answer: A.","medium") ]},

  { id:"rc-ss-bilingual", title:"Passage — Bilingual Education and Assimilation", section:"rc", source:"RC+CR Session 4",
    passage:{ title:"Language, Assimilation, and Bilingual Education", paras:[
      "Immigrants' adoption of English as their primary language is one measure of assimilation into the larger United States society. Languages define social groups and provide justification for social structures. Hence, a distinctive language sets a cultural group off from the dominant language group. Throughout United States history this pattern has resulted in one consistent, unhappy consequence, discrimination against members of the cultural minority. Language differences provide both a way to rationalize subordination and a ready means for achieving it.",
      "Traditionally, English has replaced the first language of immigrant groups by the second generation. Spanish-speaking population, however, paints a departure from this historical pattern. Many Hispanic families retain ties in Latin America and move back and forth between their present and former communities. This \"revolving door\" phenomenon ensures that large Spanish-speaking communities, with Spanish as their first language, are likely to exist in the United States for the indefinite future.",
      "This expectation underlies the call for national support for bilingual education in Spanish-speaking communities' public schools. Bilingual education can serve different purposes, however. In the 1960s, such programs were established to facilitate the learning of English so as to avoid disadvantaging children in their other subjects because of their limited English. More recently, many advocates have viewed bilingual education as a means to maintain children's native languages and cultures. The issue is important for people with different political agendas, from absorption at one pole to separatism at the other and everything in between.",
      "To date, the debates about bilingual education's impact on learning have been inconclusive. The issue of bilingual education has, nevertheless, served to unite the leadership of the nation's Hispanic communities. Grounded in concerns about status that are directly traceable to the United States history of discrimination against Hispanics, the demand for maintenance of the Spanish language in the schools is an assertion of the worth of a people and their culture. If the United States is truly a multicultural nation—that is, if it is one culture reflecting the contributions of many—this demand should be seen as a demand not for separation but for inclusion.",
      "More direct efforts to force inclusion can be misguided. For example, movements to declare English the official language do not truly advance the cohesion of a multicultural nation. They alienate the twenty million people who do not speak English as their mother tongue. They are unnecessary since the public's business is already conducted largely in English. Further, given the present state of understanding about the effects of bilingual education on learning, it would be unwise to require the universal use of English. Finally, it is for parents and local communities to choose the path they will follow, including how much of their culture they want to maintain for their children." ]},
    questions:[
      Q(1,"Inference","B","One of the characteristics of immigrant groups to the United States has traditionally been that, after immigration, relatively few members of the group",
        ["became politically active in their new communities","moved back and forth repeatedly between the United States and their former communities","used their native languages in their new communities","suffered discrimination in their new communities at the hands of the cultural majority","sought assimilation into the dominant culture of the new communities they were entering"],
        "The 'revolving door' is described as a departure from the historical pattern.",
        "The passage presents back-and-forth movement as a departure from tradition, implying few earlier immigrants did so. Answer: B.","hard"),
      Q(2,"Inference","D","One of the effects of the debate over bilingual education is that it has",
        ["given the Hispanic community a new-found pride in its culture","hampered the education of Spanish-speaking students","demonstrated the negative impact of imposing English as the official United States language","provided a common banner under which the leaders of the Spanish-speaking communities could rally","polarized the opinions of national Spanish-speaking community leaders"],
        "The issue 'served to unite the leadership.'",
        "The passage says the issue has 'served to unite the leadership of the nation's Hispanic communities.' Answer: D.","medium"),
      Q(3,"Supporting detail","E","The phrase \"different political agendas\" refers specifically to conflicting opinions regarding the",
        ["means of legislating the assimilation of minorities into United States society","methods of inducing Hispanics to adopt English as their primary language","means of achieving nondiscriminatory education for Hispanics","officials given responsibility for decisions regarding bilingual education","extent to which Hispanics should blend into the larger United States society"],
        "The agendas run 'from absorption at one pole to separatism at the other.'",
        "The agendas range from absorption to separatism — i.e., how much a group should blend into the larger society. Answer: E.","medium"),
      Q(4,"Supporting detail","A","One reason it would be unwise to require the universal use of English, according to the author, is that",
        ["it is not clear yet whether requiring the universal use of English would promote or hinder the education of children whose English is limited","the nation's Hispanic leaders have shown that bilingual education is most effective when it includes the maintenance of the Spanish language","requiring the universal use of English would reduce the cohesion of the nation's Hispanic communities and leadership","the question of language in the schools should be answered by those who evaluate bilingual education, not by people with political agendas","it has been shown that bilingual education is necessary to avoid disadvantaging children whose English is limited"],
        "The debates about learning impact are called 'inconclusive'.",
        "Because the effects of bilingual education on learning are still inconclusive, mandating universal English would be premature. Answer: A.","medium"),
      Q(5,"Function / purpose of detail","A","In the last paragraph, the author is primarily concerned with discussing",
        ["reasons against enacting a measure that would mandate the forced inclusion of immigrant groups within the dominant United States culture","the virtues and limitations of declaring English the official language of the United States","the history of attitudes within the Hispanic community toward bilingual education","the importance for immigrant groups of maintaining large segments of their culture to pass on to their children","the difference in cultures between Hispanics and other immigrant groups in the United States"],
        "The paragraph lists reasons that official-English movements are 'misguided'.",
        "The final paragraph argues against measures forcing inclusion (e.g., official-English laws). Answer: A.","medium") ]},

  { id:"rc-ss-morallicense", title:"Passage — Moral Licensing", section:"rc", source:"RC+CR Session 4",
    passage:{ title:"The Moral Licensing Effect", paras:[
      "It is common to assume that people who act morally are normally motivated to act so, while those who act immorally lack moral motivation. However, research carried out by Monin and Miller strongly points to the existence of a moral licensing effect, according to which performance of morally commendable actions in turn licenses subjects to later engage in dubious behavior. This work suggests that individuals are motivated to perform moral acts not by an innate goodness on their part, but by a desire to appear to be moral people, whether to themselves or others. Researchers continue to disagree whether licensing is best understood as involving moral credentials, in which subjects interpret their later, dubious activity in terms of the moral identity they have supposedly established for themselves in prior acts, or as involving moral credits, where subjects see themselves as having built up a surplus that they can then \"trade in\" by acting selfishly. The research strongly suggests, however, that individuals care about their moral self-image, and not merely about what others think of them. Khan and Dhar, for example, found that subjects who were asked to merely imagine performing a generous act, such as tutoring a student, were later less likely to donate a portion of their earnings to charity than those who were asked to imagine engaging in a morally neutral activity; that is, those who simply imagined their own generosity then gave themselves license to be selfish. If individuals are normally motivated to at least strive for a moral self-image in this way, we should not be too hasty to discount the common-sense assumption that moral motivation is typically behind moral action." ]},
    questions:[
      Q(1,"Function / purpose of detail","E","The author refers to a study by Khan and Dhar in order to demonstrate that",
        ["individuals can perform moral actions without giving themselves moral license","there is no correlation between individuals' giving themselves moral license and their moral behavior","there is no relation between individuals' moral self-image and their moral standards","individuals appear to take any kind of moral behavior to count toward or against their moral credits or credentials","individuals can give themselves moral license without performing any moral action"],
        "In the study, subjects only IMAGINED being generous.",
        "Subjects who merely imagined a generous act later acted more selfishly — so moral license can arise without any actual moral action. Answer: E.","hard") ]},

  { id:"rc-ss-dallasdiet", title:"Passage — Social Status and Diet", section:"rc", source:"RC+CR Session 6",
    passage:{ title:"Status and Nutrition in the Dallas Communities", paras:[
      "Historical documents have revealed that among the Timucua of Florida, a Native American people, the best from the hunt or the harvest was given to families of high social status, even in times of economic stress. Archaeological research suggests a similar relationship between social status and diet in the Dallas communities of eastern Tennessee, prehistoric Native American groups with a social organization and economy similar to that of the Timucua. The first real clue came when archaeologists discovered that skeletons of higher-status individuals tended to be several centimeters taller than those of people of lower status. In the largest Dallas communities, some individuals were buried in the earthen mounds that served as substructures for buildings important to civic and religious affairs. These burials included quantities of finely crafted items made of nonlocal material, denoting the high political standing of those interred. Burials of lower-status individuals contained primarily utilitarian items such as cooking vessels and chipped stone tools and are located in more remote sections of the settlements. The burials actually formed a pattern, the tallest skeletons being found in the mounds, and the heights declining as burials became more distant from the mounds.",
      "While it is possible that taller people were simply more successful in achieving high social standing, it is more likely that a number of stresses, including those resulting from a relatively poor diet, which could affect stature, were common among the lower-status groups. Excavations indicate that three food categories made up the bulk of the population's diet: agricultural crops cultivated in the fertile alluvial soils where the communities were located, game, and wild edible plants, primarily nuts. Information about dietary variation among community members is derived by analyzing trace elements in human bone. Higher than normal levels of manganese, strontium, and vanadium probably indicate a less nutritious diet heavily dependent on edible plants. Very low concentrations of vanadium, which is scarce in meats and somewhat lower in nuts than in other plant resources, are good evidence of meat consumption and thus a better balanced diet. As expected, vanadium was found in considerably greater quantities in skeletons in the burials of lower-status groups." ]},
    questions:[
      Q(1,"Supporting detail","C","According to the passage, which statement regarding earthen mounds in the Dallas communities is accurate?",
        ["They served primarily as burial grounds.","They were constructed in key locations on the perimeter of the village.","They were elements in important structures in the community.","They were used as storehouses for keeping valuable possessions safe.","They contained utilitarian items made of nonlocal materials."],
        "The mounds 'served as substructures for buildings important to civic and religious affairs.'",
        "The mounds were substructures for civically and religiously important buildings — i.e., elements of important structures. Answer: C.","medium"),
      Q(2,"Function / purpose of detail","C","The author raises the possibility that taller people achieved greater success most probably in order to",
        ["suggest that two explanations for a phenomenon are equally plausible","introduce empirical data supporting a position","anticipate an objection to an argument","question the usefulness of relying solely on physical evidence","point out a weakness in a traditional argument"],
        "The author immediately says the other explanation is 'more likely.'",
        "The author raises the alternative only to set it aside ('it is more likely that...'), anticipating an objection. Answer: C.","hard"),
      Q(3,"Supporting detail","B","The \"relationship\" between social status and diet was initially recognized when archaeologists",
        ["attempted to trace the ancestry of the Timucua of Florida","discovered a height differential among members of subgroups in the Dallas community","realized that the Dallas communities endured periods of nutritional deprivation","began to compare the social organization and economies of the Timucua with the Dallas communities","became curious about differences in trace elements found in the bones of Dallas community members"],
        "'The first real clue came when...'",
        "The first clue was the discovery that higher-status skeletons were taller — a height differential. Answer: B.","medium"),
      Q(4,"Inference","B","The passage suggests which of the following about the diet of the Dallas communities?",
        ["Wild edible plants were a relatively minor element in the diet.","Game was less likely to be available to lower-status individuals than were edible plants.","The diet was composed primarily of agricultural crops when game was scarce.","The diet was obtained entirely from local food sources.","The diet was well balanced, especially at harvest time."],
        "Lower-status bones had high vanadium (little meat); higher-status had more meat.",
        "Lower-status individuals showed high vanadium (a plant-heavy diet with little meat), implying game was less available to them. Answer: B.","hard") ]},

  { id:"rc-ss-cholera", title:"Passage — Where Does Cholera Hide?", section:"rc", source:"RC+CR Session 6",
    passage:{ title:"Colwell and the Dormant Cholera Bacterium", paras:[
      "For nearly a century after the discovery in the 1880s that a bacterium, Vibrio cholerae, causes cholera, scientists believed that it traveled to new geographic regions only via human hosts and that epidemics typically occurred when the bacteria spread through contamination, by human waste, of food and unchlorinated water supplies. But scientists wondered where the bacteria went during the many years between epidemics. How could the disease arise seemingly spontaneously around the world, often where it was thought to have been eradicated? In the 1970s, microbiologist Rita Colwell's claim that she had isolated V. cholerae from the Chesapeake Bay met with great skepticism, as no biologists believed V. cholerae could persist without a human host, and no cholera outbreaks were occurring anywhere near the Chesapeake. Indeed, there had been no cholera epidemics anywhere in the United States since 1911. But, noting that most historic cholera outbreaks have happened along seacoasts, Colwell suspected that V. cholerae could somehow survive in seawater and that perhaps the bacteria were not always detectable by traditional culture methods—that is, that they could not always be cultured (grown) in a petri dish.",
      "Later that decade, a small cholera outbreak near New Orleans allowed Colwell to test this hypothesis. She used a new detection method on water from the local bayous from which people with cholera had eaten crab. This method uses an antibody that latches onto a key component of the bacterium's cell membrane. Linked to that antibody is a molecule that fluoresces bright green under ultraviolet light if the V. cholerae bacterium is present. Her tests showed that the bacteria were in the bayous. Furthermore, in a study in Asia, Colwell's antibody test detected the bacteria in 51 of 52 suspect water samples, whereas culture techniques found them in only 7 of the same 52 samples. Colwell's further studies revealed that V. cholerae, like some other bacteria, goes into a dormant, spore-like state when environmental conditions do not favor reproduction; in this state, the bacterium's metabolic rate plummets and the bacterium shrinks some 15- to 300-fold. It stops reproducing and therefore cannot be cultured. This \"viable but nonculturable\" state, says Colwell, functions as a survival mechanism, enabling V. cholerae to persist in a wide range of conditions and habitats far from human hosts. Though no one knows exactly what conditions awaken V. cholerae from dormancy, Colwell notes that seasonal peaks in sea-surface temperatures in the Bay of Bengal correlate closely with peaks in that region's cholera cases. If, as Colwell believes, the bacteria are persisting in the water all along, it is possible that changes in seawater temperature or salinity are what enable them to spread among humans again." ]},
    questions:[
      Q(1,"Inference","E","If V. cholerae bacteria undetectable by traditional culture methods inevitably caused cholera in humans who ingested them, then which one is most likely to be true?",
        ["Human antibodies that usually latch onto V. cholerae's cell membrane were unable to do so in these cases.","The human body's temperature is the temperature the ocean must reach to awaken V. cholerae bacteria from their dormant state.","In their dormant state, V. cholerae bacteria are able to survive in chlorinated water systems.","The infected humans had been infected with cholera at some point earlier in their lives.","The human body is an environment in which dormant V. cholerae bacteria can awaken."],
        "Undetectable = dormant/nonculturable; yet they caused disease.",
        "If dormant (nonculturable) bacteria still caused cholera, the human body must be able to awaken them from dormancy. Answer: E.","hard"),
      Q(2,"Inference","A","Which one of the following is most strongly supported by the passage?",
        ["V. cholerae bacteria in the Bay of Bengal are more likely to be detectable by traditional culture methods when sea-surface temperatures there are at seasonal peaks.","When the salinity of seawater in the Bay of Bengal decreases, V. cholerae bacteria are likely to reproduce there and cause cholera outbreaks.","Although V. cholerae can persist in seawater, it still requires human hosts in order to spread along a seacoast.","Bacteria that are taken from a human host are harder to detect using traditional culture methods than are bacteria taken from seawater.","Antibodies are less likely to bond to the cell membrane of V. cholerae when the bacterium is in a dormant state."],
        "Warm temperatures correlate with cholera peaks; culturing requires reproduction.",
        "Since warm temperatures correlate with outbreaks (active, reproducing bacteria) and only reproducing bacteria can be cultured, they are more culturable at temperature peaks. Answer: A.","hard"),
      Q(3,"Inference","D","The passage suggests that Colwell most likely holds which view regarding V. cholerae?",
        ["In most cases, V. cholerae bacteria do not travel to new locations via human hosts, but rather move through the ocean.","In most cases, V. cholerae requires a human host in order to awaken and return from dormancy to a culturable state.","Cholera outbreaks are never caused by the introduction of active V. cholerae into a new location, but rather by V. cholerae awakening from dormancy.","Use of Colwell's new detection technique on the water samples she obtained from the Chesapeake Bay would have revealed the presence of V. cholerae.","Water samples from coastal regions throughout Asia, if subjected to Colwell's new detection technique, would reveal the presence of V. cholerae."],
        "Colwell claimed she had isolated the bacteria from the Chesapeake.",
        "Colwell believed V. cholerae persists in the Chesapeake water, so her sensitive test would detect it there. Answer: D.","hard"),
      Q(4,"Supporting detail","A","The passage provides information most helpful in answering which question?",
        ["Why did Colwell suspect that the ocean served as the environmental reservoir for V. cholerae?","What other bacteria are capable of entering a dormant state similar to that of V. cholerae?","Does ultraviolet light as used in Colwell's test have any effects on the reproduction of V. cholerae?","Is V. cholerae harmful to shellfish that transmit it?","How does Colwell intend to determine the conditions that awaken V. cholerae from dormancy?"],
        "The passage says most outbreaks happen along seacoasts.",
        "The passage explains her reasoning: most historic outbreaks occur along seacoasts, so she suspected seawater as the reservoir. Answer: A.","medium"),
      Q(5,"Supporting detail","B","Biologists were skeptical of Colwell's claim to have isolated V. cholerae from the Chesapeake Bay because they believed that",
        ["V. cholerae could not always be cultured in a petri dish","V. cholerae bacteria were unable to persist in seawater","V. cholerae bacteria were unculturable in their dormant state","Colwell's new method of detecting V. cholerae was flawed","the only V. cholerae bacteria in Chesapeake Bay were to be found in crabs"],
        "The skepticism was that the bacteria need a human host.",
        "Biologists thought V. cholerae could not persist without a human host — i.e., could not survive in seawater. Answer: B.","medium"),
      Q(6,"Inference","A","Which best explains the discrepancy in the last sentence of the second paragraph (51 of 52 vs 7 of 52)?",
        ["V. cholerae cannot always be grown in a petri dish.","V. cholerae's ability to bond with antibodies is limited.","V. cholerae responds primarily to changes in temperature and salinity.","V. cholerae cannot be cultured using samples taken from sources other than human tissue or waste.","V. cholerae's cell membrane normally contains a molecule that fluoresces under ultraviolet light."],
        "Culture methods found only 7; the antibody test found 51.",
        "The antibody test detects dormant bacteria that cannot be grown, so culturing missed most of them. Answer: A.","hard") ]}

  ];
})();
