/* GMAT Prep — additional practice questions that EXPAND existing sets.
   Merged into the matching window.GMAT_SETS entry at load time (see index.html):
   each question is appended to the set with id === setId, and its `n` is
   assigned automatically. Same question shape as sets.js:
     { topic, correct:"A".., options, text, choices[], hint, expl, level }
   Quant / Data-Insights answer keys here are compute-verified (verify script). */
(function () {
  var DS = ["(1) ALONE sufficient, (2) alone not","(2) ALONE sufficient, (1) alone not","BOTH together sufficient, neither alone","EACH alone sufficient","Together still NOT sufficient"];

  window.GMAT_SETS_EXTRA = [

  /* ---------------- QUANT ---------------- */
  { setId:"quant-percentage-ex", add:[
    { topic:"Percentages & percent change", level:"easy", correct:"B", options:4,
      text:"A shirt's price is first increased by 25% and then the new price is decreased by 20%. Compared with the original price, the final price is:",
      choices:["5% lower","the same","5% higher","4% higher"],
      hint:"Chain the factors: 1.25 then 0.80.",
      expl:"Final factor \\(=1.25\\times0.80=1.00\\), so the price returns to its original value — no net change.\nAnswer: B." },
    { topic:"Percentages & percent change", level:"easy", correct:"C", options:4,
      text:"If 40% of a number is 240, what is 75% of the same number?",
      choices:["360","420","450","480"],
      hint:"Find the whole first.",
      expl:"\\(0.40N=240\\Rightarrow N=600\\). Then \\(0.75\\times600=450\\).\nAnswer: C." },
    { topic:"Percentages & percent change", level:"medium", correct:"B", options:4,
      text:"In a class, 60% of the students are boys. If 20% of the boys and 40% of the girls wear glasses, what percent of the whole class wears glasses?",
      choices:["24%","28%","30%","32%"],
      hint:"Weight each group by its share of the class.",
      expl:"Boys: \\(0.60\\times0.20=0.12\\). Girls: \\(0.40\\times0.40=0.16\\). Total \\(=0.28=28\\%\\).\nAnswer: B." },
    { topic:"Percentages & percent change", level:"medium", correct:"A", options:4,
      text:"The price of sugar rises by 25%. By what percent must a family reduce its consumption so that its total spending on sugar stays the same?",
      choices:["20%","25%","15%","33⅓%"],
      hint:"Spending = price × quantity; keep the product fixed.",
      expl:"To offset a factor of \\(1.25\\), consumption must be multiplied by \\(1/1.25=0.8\\), a reduction of \\(20\\%\\). (In general a \\(+x\\%\\) price needs a \\(\\frac{x}{100+x}\\) cut.)\nAnswer: A." },
    { topic:"Percentages & percent change", level:"medium", correct:"B", options:4,
      text:"A town's population grew by 20% in 2023 and by a further 25% in 2024. Over the two years combined, the population increased by:",
      choices:["45%","50%","55%","22.5%"],
      hint:"Multiply the growth factors, don't add the percents.",
      expl:"\\(1.20\\times1.25=1.50\\), a \\(50\\%\\) increase overall.\nAnswer: B." }
  ]},

  { setId:"quant-ratio-ex", add:[
    { topic:"Ratios & proportions", level:"medium", correct:"A", options:4,
      text:"If \\(a:b = 2:3\\) and \\(b:c = 4:5\\), then \\(a:c\\) equals:",
      choices:["8 : 15","2 : 5","4 : 5","10 : 15"],
      hint:"Make b the same in both ratios.",
      expl:"Scale to a common b: \\(a:b=8:12\\) and \\(b:c=12:15\\), so \\(a:c=8:15\\).\nAnswer: A." },
    { topic:"Ratios & proportions", level:"easy", correct:"C", options:4,
      text:"$720 is divided among A, B and C in the ratio 2 : 3 : 4. C's share is:",
      choices:["$160","$240","$320","$360"],
      hint:"Total parts = 2+3+4.",
      expl:"9 parts \\(=\\$720\\Rightarrow\\) one part \\(=\\$80\\). C gets \\(4\\times80=\\$320\\).\nAnswer: C." },
    { topic:"Ratios & proportions", level:"medium", correct:"A", options:4,
      text:"Two numbers are in the ratio 5 : 8. When 9 is added to each, the ratio becomes 8 : 11. The smaller number is:",
      choices:["15","20","24","18"],
      hint:"Let the numbers be 5k and 8k and cross-multiply.",
      expl:"\\(\\frac{5k+9}{8k+9}=\\frac{8}{11}\\Rightarrow 11(5k+9)=8(8k+9)\\Rightarrow 55k+99=64k+72\\Rightarrow 9k=27,\\ k=3\\). Smaller \\(=5k=15\\).\nAnswer: A." },
    { topic:"Ratios & proportions", level:"medium", correct:"B", options:4,
      text:"A 60-litre mixture contains milk and water in the ratio 2 : 1. How much water must be added to make the ratio 1 : 1?",
      choices:["10 L","20 L","30 L","15 L"],
      hint:"The amount of milk doesn't change.",
      expl:"Milk \\(=40\\) L, water \\(=20\\) L. For 1 : 1 we need water \\(=40\\) L, so add \\(40-20=20\\) L.\nAnswer: B." },
    { topic:"Ratios & proportions", level:"easy", correct:"A", options:4,
      text:"If \\(\\dfrac{x}{3}=\\dfrac{y}{4}=\\dfrac{z}{7}\\), then \\(\\dfrac{x+y+z}{z}\\) equals:",
      choices:["2","\\(\\tfrac72\\)","14","1"],
      hint:"Let the common value be k.",
      expl:"\\(x=3k,\\ y=4k,\\ z=7k\\Rightarrow \\frac{x+y+z}{z}=\\frac{14k}{7k}=2\\).\nAnswer: A." }
  ]},

  { setId:"quant-interest-ex", add:[
    { topic:"Simple & compound interest", level:"easy", correct:"B", options:4,
      text:"Find the simple interest on $2,000 at 5% per annum for 3 years.",
      choices:["$250","$300","$315","$330"],
      hint:"SI = P·r·t.",
      expl:"\\(2000\\times0.05\\times3=\\$300\\).\nAnswer: B." },
    { topic:"Simple & compound interest", level:"medium", correct:"B", options:4,
      text:"A sum of money doubles itself in 8 years at simple interest. In how many years will it triple?",
      choices:["12","16","20","24"],
      hint:"Under SI the interest is a fixed amount per year.",
      expl:"Doubling means the interest earned equals the principal in 8 years. Tripling needs interest equal to twice the principal, i.e. \\(2\\times8=16\\) years.\nAnswer: B." },
    { topic:"Simple & compound interest", level:"easy", correct:"B", options:4,
      text:"What is the compound interest on $10,000 at 10% per annum, compounded annually, for 2 years?",
      choices:["$2,000","$2,100","$2,200","$1,100"],
      hint:"Amount = P(1+r)^t, then subtract P.",
      expl:"\\(10000\\times1.1^2=12100\\); interest \\(=12100-10000=\\$2100\\).\nAnswer: B." },
    { topic:"Simple & compound interest", level:"medium", correct:"A", options:4,
      text:"The difference between the compound interest and the simple interest on a certain sum for 2 years at 10% per annum is $50. The sum is:",
      choices:["$5,000","$2,500","$10,000","$4,000"],
      hint:"For 2 years the difference equals P·r².",
      expl:"Difference \\(=P\\left(\\frac{r}{100}\\right)^2=P(0.1)^2=0.01P=50\\Rightarrow P=\\$5000\\).\nAnswer: A." }
  ]},

  { setId:"quant-speed-ex", add:[
    { topic:"Speed, distance & time", level:"easy", correct:"B", options:4,
      text:"A car covers 150 km in 2 hours 30 minutes. Its average speed is:",
      choices:["55 km/h","60 km/h","62.5 km/h","75 km/h"],
      hint:"Convert the time to hours.",
      expl:"\\(2\\text{h }30\\text{m}=2.5\\) h; speed \\(=150/2.5=60\\) km/h.\nAnswer: B." },
    { topic:"Speed, distance & time", level:"medium", correct:"C", options:4,
      text:"A train 120 m long passes a stationary pole in 6 seconds. The train's speed is:",
      choices:["60 km/h","66 km/h","72 km/h","20 km/h"],
      hint:"To pass a pole, the train travels its own length.",
      expl:"Speed \\(=120/6=20\\) m/s \\(=20\\times\\frac{18}{5}=72\\) km/h.\nAnswer: C." },
    { topic:"Speed, distance & time", level:"medium", correct:"C", options:4,
      text:"Two trains, 100 m and 120 m long, run toward each other on parallel tracks at 40 km/h and 32 km/h. How long do they take to completely pass each other?",
      choices:["9 s","10 s","11 s","12 s"],
      hint:"Add the speeds (opposite directions) and the lengths.",
      expl:"Relative speed \\(=72\\) km/h \\(=20\\) m/s; combined length \\(=220\\) m; time \\(=220/20=11\\) s.\nAnswer: C." },
    { topic:"Speed, distance & time", level:"medium", correct:"B", options:4,
      text:"A boat travels 12 km downstream in 2 hours and returns the same 12 km upstream in 3 hours. The speed of the boat in still water is:",
      choices:["4 km/h","5 km/h","6 km/h","10 km/h"],
      hint:"Still-water speed is the average of downstream and upstream speeds.",
      expl:"Downstream \\(=6\\) km/h, upstream \\(=4\\) km/h; still water \\(=(6+4)/2=5\\) km/h.\nAnswer: B." },
    { topic:"Speed, distance & time", level:"medium", correct:"C", options:4,
      text:"Walking at \\(\\tfrac34\\) of his usual speed, a man reaches his office 20 minutes late. His usual travel time (in minutes) is:",
      choices:["40","45","60","80"],
      hint:"Speed and time are inversely proportional over a fixed distance.",
      expl:"At \\(\\frac34\\) speed the time is \\(\\frac43\\) of usual, i.e. \\(\\frac13\\) longer. That extra \\(\\frac13 T=20\\Rightarrow T=60\\) min.\nAnswer: C." }
  ]},

  { setId:"quant-timework-ex", add:[
    { topic:"Work & rate", level:"medium", correct:"B", options:4,
      text:"A can finish a job in 12 days and B in 18 days. Working together, they finish it in:",
      choices:["6 days","7.2 days","9 days","15 days"],
      hint:"Add the rates.",
      expl:"Combined rate \\(=\\frac1{12}+\\frac1{18}=\\frac{3+2}{36}=\\frac5{36}\\) per day, so time \\(=\\frac{36}{5}=7.2\\) days.\nAnswer: B." },
    { topic:"Work & rate", level:"easy", correct:"B", options:4,
      text:"15 workers build a wall in 8 days. Working at the same rate, how many days would 10 workers take?",
      choices:["10 days","12 days","5⅓ days","16 days"],
      hint:"Total work in worker-days is constant.",
      expl:"Work \\(=15\\times8=120\\) worker-days; with 10 workers, \\(120/10=12\\) days.\nAnswer: B." },
    { topic:"Work & rate", level:"medium", correct:"C", options:4,
      text:"A works twice as fast as B. Together they complete a task in 8 days. B working alone would take:",
      choices:["12 days","16 days","24 days","36 days"],
      hint:"Let B's rate be r; A's is 2r.",
      expl:"Combined rate \\(=3r=\\frac18\\Rightarrow r=\\frac1{24}\\), so B alone needs 24 days.\nAnswer: C." },
    { topic:"Work & rate", level:"medium", correct:"C", options:4,
      text:"An inlet pipe can fill a tank in 6 hours; an outlet pipe can empty the full tank in 9 hours. If both are open on an empty tank, the tank fills in:",
      choices:["12 hours","15 hours","18 hours","3.6 hours"],
      hint:"Net rate = fill rate − drain rate.",
      expl:"Net rate \\(=\\frac16-\\frac19=\\frac{3-2}{18}=\\frac1{18}\\) per hour, so 18 hours.\nAnswer: C." }
  ]},

  { setId:"quant-average-ex", add:[
    { topic:"Weighted averages", level:"easy", correct:"B", options:4,
      text:"The average of 5 numbers is 27. If the number 35 is removed, the average of the remaining four numbers is:",
      choices:["24","25","26","23"],
      hint:"Work with the total sum.",
      expl:"Sum \\(=5\\times27=135\\); after removing 35, sum \\(=100\\), average \\(=100/4=25\\).\nAnswer: B." },
    { topic:"Weighted averages", level:"medium", correct:"C", options:4,
      text:"The average age of 30 students is 12 years. When the teacher's age is included, the average rises to 13 years. The teacher's age is:",
      choices:["40","42","43","45"],
      hint:"Compare the two totals.",
      expl:"Students' total \\(=360\\). With teacher: \\(13\\times31=403\\). Teacher \\(=403-360=43\\).\nAnswer: C." },
    { topic:"Weighted averages", level:"medium", correct:"C", options:4,
      text:"A batsman's average after 10 innings is 40. What must he score in his 11th innings to raise his average to 42?",
      choices:["52","60","62","64"],
      hint:"Target total minus current total.",
      expl:"Needed total \\(=42\\times11=462\\); current \\(=400\\); required score \\(=62\\).\nAnswer: C." },
    { topic:"Weighted averages", level:"medium", correct:"B", options:4,
      text:"What is the average of the first 20 positive even integers (2, 4, …, 40)?",
      choices:["20","21","22","19"],
      hint:"For an evenly spaced list, average = (first + last)/2.",
      expl:"\\((2+40)/2=21\\).\nAnswer: B." }
  ]},

  { setId:"quant-statistics-ex", add:[
    { topic:"Mean, median & mode", level:"easy", correct:"B", options:4,
      text:"The mean of the five numbers 2, 5, 7, x, 10 is 6. The value of x is:",
      choices:["4","6","8","12"],
      hint:"Sum of the five = 5 × mean.",
      expl:"Sum \\(=30\\); the known four sum to 24, so \\(x=6\\).\nAnswer: B." },
    { topic:"Mean, median & mode", level:"medium", correct:"B", options:4,
      text:"A list contains 7 consecutive integers whose median is 20. The greatest of these integers is:",
      choices:["22","23","24","26"],
      hint:"For an odd count of consecutive integers, the median is the middle term.",
      expl:"The 4th term is 20, so the terms are 17…23; the greatest is 23.\nAnswer: B." },
    { topic:"Mean, median & mode", level:"medium", correct:"B", options:4,
      text:"Each number in the set {5, 8, 11, 14, 17} is multiplied by 3. The standard deviation of the new set is the old standard deviation multiplied by:",
      choices:["1","3","9","\\(\\sqrt3\\)"],
      hint:"Scaling every value scales the spread by the same factor.",
      expl:"Multiplying every element by a constant \\(k\\) multiplies the standard deviation by \\(|k|\\); here \\(k=3\\).\nAnswer: B." },
    { topic:"Mean, median & mode", level:"easy", correct:"C", options:4,
      text:"For the data set {4, 4, 6, 8, 8, 8, 10}, the mode is:",
      choices:["4","6","8","10"],
      hint:"The mode is the most frequent value.",
      expl:"8 appears three times, more than any other value.\nAnswer: C." }
  ]},

  { setId:"quant-probability-ex", add:[
    { topic:"Permutations & combinations", level:"medium", correct:"C", options:4,
      text:"How many distinct arrangements can be made from the letters of the word LEVEL?",
      choices:["20","24","30","120"],
      hint:"Divide by the factorials of repeated letters.",
      expl:"LEVEL has 5 letters with L twice and E twice: \\(\\frac{5!}{2!\\,2!}=\\frac{120}{4}=30\\).\nAnswer: C." },
    { topic:"Permutations & combinations", level:"easy", correct:"B", options:4,
      text:"In how many ways can a committee of 3 people be chosen from 8 people?",
      choices:["24","56","112","336"],
      hint:"Order doesn't matter — use a combination.",
      expl:"\\(\\binom{8}{3}=\\frac{8\\cdot7\\cdot6}{3\\cdot2\\cdot1}=56\\).\nAnswer: B." },
    { topic:"Permutations & combinations", level:"medium", correct:"B", options:4,
      text:"Two fair dice are rolled. What is the probability that the sum of the two faces is 8?",
      choices:["\\(\\tfrac16\\)","\\(\\tfrac{5}{36}\\)","\\(\\tfrac19\\)","\\(\\tfrac1{12}\\)"],
      hint:"Count the ordered pairs that total 8 out of 36.",
      expl:"Favorable: (2,6),(3,5),(4,4),(5,3),(6,2) — 5 outcomes. \\(P=5/36\\).\nAnswer: B." },
    { topic:"Permutations & combinations", level:"medium", correct:"A", options:4,
      text:"A bag holds 4 red and 6 blue marbles. Two are drawn at random without replacement. The probability that both are red is:",
      choices:["\\(\\tfrac{2}{15}\\)","\\(\\tfrac16\\)","\\(\\tfrac{4}{25}\\)","\\(\\tfrac15\\)"],
      hint:"Multiply the two conditional probabilities.",
      expl:"\\(\\frac{4}{10}\\times\\frac{3}{9}=\\frac{12}{90}=\\frac{2}{15}\\).\nAnswer: A." }
  ]},

  { setId:"quant-exponents-ex", add:[
    { topic:"Exponent rules", level:"easy", correct:"B", options:4,
      text:"\\(\\dfrac{2^{10}\\times 2^{5}}{2^{12}}\\) equals:",
      choices:["4","8","16","\\(2^{7}\\)"],
      hint:"Add exponents when multiplying, subtract when dividing.",
      expl:"\\(2^{10+5-12}=2^{3}=8\\).\nAnswer: B." },
    { topic:"Exponent rules", level:"easy", correct:"B", options:4,
      text:"If \\(3^{x}=81\\), then \\(3^{x-2}\\) equals:",
      choices:["3","9","27","1"],
      hint:"First find x.",
      expl:"\\(3^x=81=3^4\\Rightarrow x=4\\); \\(3^{4-2}=3^2=9\\).\nAnswer: B." },
    { topic:"Exponent rules", level:"medium", correct:"B", options:4,
      text:"\\((2^{3})^{2}\\times 2^{-4}\\) equals:",
      choices:["2","4","8","16"],
      hint:"Power of a power multiplies exponents.",
      expl:"\\((2^3)^2=2^6\\); \\(2^6\\times2^{-4}=2^{2}=4\\).\nAnswer: B." },
    { topic:"Exponent rules", level:"medium", correct:"B", options:4,
      text:"If \\(5^{2x}=100\\), then \\(5^{x}\\) equals:",
      choices:["5","10","25","50"],
      hint:"Note that \\(5^{2x}=(5^{x})^{2}\\).",
      expl:"\\((5^x)^2=100\\Rightarrow 5^x=10\\) (positive root).\nAnswer: B." }
  ]},

  { setId:"quant-linear-ex", add:[
    { topic:"Linear equations", level:"easy", correct:"C", options:4,
      text:"If \\(3x+5=20\\), then x equals:",
      choices:["3","4","5","15"],
      hint:"Isolate x.",
      expl:"\\(3x=15\\Rightarrow x=5\\).\nAnswer: C." },
    { topic:"Linear equations", level:"medium", correct:"B", options:4,
      text:"If \\(x+y=10\\) and \\(x-y=4\\), then \\(xy\\) equals:",
      choices:["16","21","24","25"],
      hint:"Solve for x and y first.",
      expl:"Adding: \\(2x=14,\\ x=7\\); then \\(y=3\\); \\(xy=21\\).\nAnswer: B." },
    { topic:"Linear equations", level:"easy", correct:"B", options:4,
      text:"A number added to twice itself equals 27. The number is:",
      choices:["8","9","10","13.5"],
      hint:"Translate to x + 2x.",
      expl:"\\(x+2x=3x=27\\Rightarrow x=9\\).\nAnswer: B." },
    { topic:"Linear equations", level:"medium", correct:"C", options:4,
      text:"At a fair, adult tickets cost $8 and child tickets cost $5. A group of 10 tickets cost $68 in total. How many child tickets were bought?",
      choices:["2","3","4","6"],
      hint:"Let c = child tickets; adults = 10 − c.",
      expl:"\\(8(10-c)+5c=68\\Rightarrow 80-3c=68\\Rightarrow c=4\\).\nAnswer: C." }
  ]},

  /* ---------------- DATA INSIGHTS ---------------- */
  { setId:"di-datasufficiency-ex", add:[
    { topic:"Value questions", level:"medium", correct:"B", options:5, choices:DS,
      text:"Is the number x positive?\n(1) \\(x^{2}=9\\)\n(2) \\(x^{3}=27\\)",
      hint:"An even power hides the sign; an odd power keeps it.",
      expl:"(1) \\(x=\\pm3\\) — sign unknown, not sufficient.\n(2) \\(x^3=27\\Rightarrow x=3>0\\) — sufficient.\nOnly (2) alone works.\nAnswer: B." },
    { topic:"Value questions", level:"medium", correct:"E", options:5, choices:DS,
      text:"What is the value of the integer n?\n(1) n is a prime number between 20 and 30.\n(2) n is odd.",
      hint:"List the candidates that satisfy each statement.",
      expl:"(1) primes in (20,30) are 23 and 29 — two values, not sufficient. (2) far too broad. Together, both 23 and 29 are odd primes in range, so n is still not pinned down.\nAnswer: E." },
    { topic:"Value questions", level:"easy", correct:"D", options:5, choices:DS,
      text:"If x and y are positive, is \\(x>y\\)?\n(1) \\(x/y = 1.2\\)\n(2) \\(x-y = 5\\)",
      hint:"Each statement is a yes/no test — you need a definite answer, not a value.",
      expl:"(1) \\(x=1.2y>y\\) (y>0) — definitely yes, sufficient. (2) \\(x=y+5>y\\) — definitely yes, sufficient.\nEach alone answers the question.\nAnswer: D." },
    { topic:"Value questions", level:"medium", correct:"C", options:5, choices:DS,
      text:"What is the area of rectangle R?\n(1) The length of R is 8.\n(2) The perimeter of R is 28.",
      hint:"Area needs both dimensions.",
      expl:"(1) gives length only — insufficient. (2) gives \\(l+w=14\\) — insufficient. Together: \\(w=14-8=6\\), area \\(=8\\times6=48\\) — sufficient.\nAnswer: C." },
    { topic:"Value questions", level:"medium", correct:"C", options:5, choices:DS,
      text:"Is the positive integer k divisible by 6?\n(1) k is divisible by 3.\n(2) k is divisible by 4.",
      hint:"Divisible by 6 means divisible by both 2 and 3.",
      expl:"(1) alone: divisible by 3 but maybe odd — not sufficient. (2) alone: divisible by 4 but maybe not by 3 — not sufficient. Together k is divisible by lcm(3,4)=12, hence by 6 — always yes.\nAnswer: C." }
  ]},

  { setId:"di-twopart-ex", add:[
    { topic:"Quantitative two-part", level:"medium", correct:"C", options:5,
      text:"A vendor sells apples at $2 each and mangoes at $3 each. A customer buys 12 pieces of fruit in total and pays $29. Which pair gives (number of apples, number of mangoes)?",
      choices:["(5, 7)","(6, 6)","(7, 5)","(8, 4)","(9, 3)"],
      hint:"Let a + m = 12 and 2a + 3m = 29.",
      expl:"\\(2a+3(12-a)=36-a=29\\Rightarrow a=7,\\ m=5\\) → (7, 5).\nAnswer: C." },
    { topic:"Quantitative two-part", level:"medium", correct:"B", options:5,
      text:"A factory makes chairs and tables. Each chair uses 3 kg of wood; each table uses 8 kg. One batch used 20 items and 95 kg of wood. Which pair gives (chairs, tables)?",
      choices:["(12, 8)","(13, 7)","(14, 6)","(15, 5)","(11, 9)"],
      hint:"c + t = 20 and 3c + 8t = 95.",
      expl:"\\(3c+8(20-c)=160-5c=95\\Rightarrow 5c=65,\\ c=13,\\ t=7\\) → (13, 7).\nAnswer: B." },
    { topic:"Quantitative two-part", level:"hard", correct:"D", options:5,
      text:"Two investments together total $10,000. One pays 6% annual interest and the other 9%, and the combined interest for one year is $750. Which pair gives (amount at 6%, amount at 9%)?",
      choices:["($3,000, $7,000)","($4,000, $6,000)","($4,500, $5,500)","($5,000, $5,000)","($6,000, $4,000)"],
      hint:"Let x be the amount at 6%; 0.06x + 0.09(10000 − x) = 750.",
      expl:"\\(0.06x+0.09(10000-x)=900-0.03x=750\\Rightarrow 0.03x=150,\\ x=5000\\); the other is $5,000 → ($5,000, $5,000).\nAnswer: D." }
  ]},

  /* ---------------- CRITICAL REASONING ---------------- */
  { setId:"cr-weaken", add:[
    { topic:"Weaken", level:"medium", correct:"B", options:5,
      text:"A city installed brighter streetlights along Main Street, and over the following year the number of traffic accidents there fell by 30%. City officials concluded that the brighter lighting caused the decline. Which of the following, if true, most weakens the officials' conclusion?",
      choices:["The brighter lights also coincided with a drop in street crime along Main Street.","In the same year, the city lowered the speed limit on Main Street and installed speed cameras.","Accidents on streets near Main Street remained unchanged over the year.","The new streetlights cost considerably more than the city had budgeted.","Most Main Street accidents had historically occurred after dark."],
      hint:"Look for another change that could explain the drop.",
      expl:"If the speed limit was lowered and cameras added at the same time (B), those changes could account for the fall in accidents, undercutting the claim that lighting caused it. (C) and (E) would if anything support the conclusion.\nAnswer: B." },
    { topic:"Weaken", level:"medium", correct:"B", options:5,
      text:"A supplement company observes that customers who take its daily vitamin report fewer colds per year than people who take no vitamin, and concludes that the vitamin prevents colds. Which of the following, if true, most weakens the conclusion?",
      choices:["The vitamin is inexpensive and widely available.","People who choose to take a daily vitamin also tend to exercise more and sleep more than those who do not.","Colds are caused by viruses rather than by nutrient deficiencies.","Some customers take the vitamin only during winter months.","The company based its claim on a survey of several thousand customers."],
      hint:"Is there a difference between the two groups other than the vitamin?",
      expl:"If vitamin-takers differ in other health habits (B), those habits — not the vitamin — could explain their fewer colds, a classic self-selection confound.\nAnswer: B." },
    { topic:"Weaken", level:"medium", correct:"B", options:5,
      text:"To cut costs, a hospital plans to replace its brand-name IV bags with a chemically identical generic that costs 40% less. An administrator argues the switch will save money with no downside. Which of the following, if true, most weakens the administrator's argument?",
      choices:["The generic bags are manufactured in the same country as the brand-name bags.","The generic bags come only in sizes that do not fit the hospital's existing infusion pumps, which would all have to be replaced.","The brand-name bags have been used at the hospital for over ten years.","Nurses are more familiar with the brand-name bags' labeling.","The generic manufacturer also supplies other hospital products."],
      hint:"'No downside' fails if the switch triggers a large hidden cost.",
      expl:"If adopting the generic forces the hospital to replace all its infusion pumps (B), that hidden expense could erase the savings — directly attacking the 'no downside' claim.\nAnswer: B." }
  ]},

  { setId:"cr-strengthen", add:[
    { topic:"Strengthen", level:"medium", correct:"B", options:5,
      text:"A researcher claims that a new math app improves scores, noting that students who used it scored higher on a year-end test than students who did not. Which of the following, if true, most strengthens the claim?",
      choices:["The app was designed by experienced classroom teachers.","Before the study, the two groups of students had scored equally on a comparable math pretest.","The app is popular and enjoyable to use.","The year-end test covered some topics the app did not teach.","A few students in the app group used it only occasionally."],
      hint:"Rule out that the groups already differed.",
      expl:"If both groups started equal (B), the later gap is more plausibly due to the app rather than pre-existing ability, strengthening the causal claim.\nAnswer: B." },
    { topic:"Strengthen", level:"medium", correct:"A", options:5,
      text:"A town credits its new curbside recycling program for a drop in landfill tonnage, which fell in the year after the program began. Which of the following, if true, most strengthens the town's conclusion?",
      choices:["Neighboring towns without such a program saw no change in their landfill tonnage over the same year.","The recycling program was more expensive to run than expected.","Residents initially found the sorting rules confusing.","The regional landfill is nearing its capacity.","Recycling participation has been rising nationwide."],
      hint:"Compare against a group that lacked the program.",
      expl:"If comparable towns without the program saw no drop (A), a general regional trend is ruled out and the program becomes the likely cause.\nAnswer: A." },
    { topic:"Strengthen", level:"medium", correct:"B", options:5,
      text:"A company switched to a four-day workweek and total weekly output rose. Management concludes the shorter week caused the increase. Which of the following, if true, most strengthens the claim that the schedule change—rather than another factor—was responsible?",
      choices:["Employees said they enjoyed the extra day off.","The company made no other changes—no new hires, equipment, or pay—when it adopted the four-day week.","Output is measured by the number of units shipped.","Four-day weeks are becoming common in the industry.","A few employees still answered email on their day off."],
      hint:"Eliminate competing explanations for the rise.",
      expl:"If nothing else changed (B), alternative causes for the output rise are removed, so the schedule change is the plausible driver.\nAnswer: B." }
  ]},

  { setId:"cr-assumption", add:[
    { topic:"Assumption", level:"medium", correct:"C", options:5,
      text:"Editorial: Our newspaper should stop printing horoscopes. Horoscopes have no scientific basis, and a serious newspaper should print only material that has scientific support. The argument depends on assuming which of the following?",
      choices:["Readers of the newspaper dislike horoscopes.","Horoscopes are expensive for the newspaper to produce.","The newspaper is, or aims to be, a serious newspaper.","No competing newspaper prints horoscopes.","Every horoscope prediction turns out to be inaccurate."],
      hint:"What links the general rule about 'a serious newspaper' to 'our newspaper'?",
      expl:"The conclusion applies the rule about serious newspapers to this paper, which only follows if this paper is (or means to be) a serious one (C). Negating C breaks the argument.\nAnswer: C." },
    { topic:"Assumption", level:"medium", correct:"B", options:5,
      text:"Company X's profits rose in the year after it relocated its factory overseas. A manager concludes that the relocation increased the company's profits. The argument assumes which of the following?",
      choices:["The overseas factory produces exactly the same products as before.","No other factor was chiefly responsible for the rise in profits during that year.","Overseas labor is less expensive than domestic labor.","The company's profits will keep rising in future years.","Shareholders approved of the relocation."],
      hint:"For a cause-and-effect claim, what must be true about other possible causes?",
      expl:"Concluding the move caused the profit rise assumes no other factor was the real cause (B); otherwise the correlation wouldn't establish causation.\nAnswer: B." },
    { topic:"Assumption", level:"medium", correct:"B", options:5,
      text:"A planner argues that the new bridge will reduce commute times because it offers a more direct route between the suburbs and downtown. The argument assumes which of the following?",
      choices:["The bridge was inexpensive to build.","A substantial number of commuters will actually use the new bridge instead of their current routes.","The old routes into downtown will be permanently closed.","Downtown has enough parking for additional commuters.","The suburbs will continue to grow in population."],
      hint:"A shorter route only helps if people take it.",
      expl:"The benefit depends on commuters actually using the bridge (B); if they keep their old routes, commute times won't fall.\nAnswer: B." }
  ]},

  { setId:"cr-paradox", add:[
    { topic:"Explain the paradox", level:"medium", correct:"B", options:5,
      text:"A retailer cut the price of its umbrellas by 20%, yet its total revenue from umbrella sales rose. Which of the following, if true, best explains this result?",
      choices:["The retailer simultaneously raised the price of its raincoats.","The lower price led to a more-than-proportional increase in the number of umbrellas sold.","Umbrella sales are highly seasonal.","The retailer advertised its raincoats heavily that month.","Several competitors also sell umbrellas."],
      hint:"Revenue = price per unit × units sold.",
      expl:"Revenue can rise despite a price cut if unit sales climb by a larger percentage than the price fell (B).\nAnswer: B." },
    { topic:"Explain the paradox", level:"medium", correct:"B", options:5,
      text:"After a company hired more customer-service agents, the average time customers spent waiting on hold increased. Which of the following, if true, best explains the increase?",
      choices:["The newly hired agents received thorough training.","A concurrent advertising campaign sharply increased the number of customers calling in.","The company uses an automated phone menu to route calls.","Agents are paid by the hour rather than per call.","Some customers prefer to contact the company by email."],
      hint:"Wait time depends on demand relative to capacity, not just on staffing.",
      expl:"If call volume surged at the same time (B), demand could outpace even the enlarged staff, raising wait times.\nAnswer: B." },
    { topic:"Explain the paradox", level:"medium", correct:"B", options:5,
      text:"Over the past decade a country's factories became markedly more energy-efficient per unit of output, yet the country's total industrial energy consumption rose. Which of the following, if true, best resolves this apparent discrepancy?",
      choices:["Energy prices fell steadily over the decade.","Industrial output expanded so greatly that total energy use rose even as energy per unit fell.","Many factories adopted renewable energy sources.","Efficiency gains were measured per worker rather than per unit.","A number of older factories were shut down during the decade."],
      hint:"Total energy = energy per unit × number of units.",
      expl:"If output grew enough (B), total energy use can rise despite lower energy per unit — the scale increase outweighs the efficiency gain.\nAnswer: B." }
  ]},

  { setId:"cr-inference", add:[
    { topic:"Inference / must be true", level:"medium", correct:"B", options:5,
      text:"Every student who passed the certification exam had completed the advanced course. Maria did not complete the advanced course. If the statements above are true, which of the following must also be true?",
      choices:["Maria failed the certification exam.","Maria did not pass the certification exam.","Maria did not take the certification exam.","The advanced course guarantees passing the exam.","Only students in the advanced course may take the exam."],
      hint:"Use the contrapositive; distinguish 'did not pass' from 'failed'.",
      expl:"Passed ⇒ completed the course. Maria didn't complete it, so she could not have passed (B). 'Failed' (A) is too strong — she may not have taken it at all.\nAnswer: B." },
    { topic:"Inference / must be true", level:"medium", correct:"B", options:5,
      text:"In a certain library, every book on the third floor is a reference book, and no reference book may be borrowed. If these statements are true, which of the following must be true?",
      choices:["Every book that cannot be borrowed is on the third floor.","No book on the third floor may be borrowed.","All of the library's reference books are on the third floor.","Some books on the third floor may be borrowed.","All borrowable books are located on the first floor."],
      hint:"Chain the two conditions.",
      expl:"Third-floor ⇒ reference ⇒ not borrowable, so no third-floor book may be borrowed (B). The others reverse or overreach the given conditions.\nAnswer: B." },
    { topic:"Inference / must be true", level:"medium", correct:"B", options:5,
      text:"The company will hold its annual picnic only if at least 30 employees sign up. This year only 22 employees signed up. If the statements are true, which of the following must be true?",
      choices:["The picnic will be rescheduled for a later date.","The company will not hold the picnic this year.","More employees will sign up before the deadline.","The picnic was also canceled last year.","Most employees dislike the picnic."],
      hint:"A necessary condition has not been met.",
      expl:"Holding the picnic requires ≥30 sign-ups; with only 22, that necessary condition fails, so the picnic will not be held (B).\nAnswer: B." }
  ]},

  /* ---------------- READING COMPREHENSION (use existing passages) ---------------- */
  { setId:"rc-science-lichen", add:[
    { topic:"Inference", level:"medium", correct:"B", options:5,
      text:"The passage suggests that the early 'lichen desert' mapping method was limited primarily because it:",
      choices:["required costly laboratory instruments to carry out","could not reveal which pollutants were responsible or how their levels changed over time","tended to exaggerate the severity of urban air pollution","depended on lichen species that were insensitive to sulfur dioxide","could not be used in the vicinity of industrial cities"],
      hint:"Re-read the description of what the crude method 'said little about.'",
      expl:"The passage states the method 'said little about which pollutants were responsible or how concentrations varied over time' (B). It was praised as inexpensive and instrument-free, ruling out (A).\nAnswer: B." },
    { topic:"Supporting detail", level:"medium", correct:"B", options:5,
      text:"According to the passage, analyzing the chemical composition of lichen tissue allows researchers to detect certain metal contaminants that:",
      choices:["are harmless to the lichen organism","leave no visible mark on the lichen","accumulate only in rooted plants","have no relation to atmospheric deposition","destroy the lichen's photosynthetic partner"],
      hint:"Find the sentence about metals and visible signs.",
      expl:"The passage says tissue analysis can 'detect contaminants, such as certain metals, that leave no visible mark on the organism' (B).\nAnswer: B." }
  ]},
  { setId:"rc-business-remote", add:[
    { topic:"Main idea / primary purpose", level:"medium", correct:"B", options:5,
      text:"The primary purpose of the passage is to:",
      choices:["prove that remote work raises employee productivity","explain why measures of remote-work productivity can point in opposite directions and weigh competing explanations","recommend that firms eliminate remote work entirely","describe methods for measuring output per hour","show that managers are universally biased against remote workers"],
      hint:"Track the passage's overall movement, not one detail.",
      expl:"The passage lays out the short-run/long-run divergence and then presents two competing explanations for it (B). It does not settle the debate or make a blanket recommendation.\nAnswer: B." },
    { topic:"Inference", level:"hard", correct:"B", options:5,
      text:"The two explanations discussed in the passage differ chiefly in whether they locate the source of remote workers' slower advancement in:",
      choices:["the workers' declining job skills versus their lack of ambition","the nature of the career-driving tasks themselves versus the way managers evaluate employees","short-run output versus long-run output","office employees versus home employees","the cost of remote work versus its benefits"],
      hint:"Contrast the 'invisible tasks' explanation with the 'management' explanation.",
      expl:"The first explanation blames the invisibility of the valuable tasks; the second blames managers who reward presence over performance (B). Neither claims workers become less capable.\nAnswer: B." }
  ]},
  { setId:"rc-social-commons", add:[
    { topic:"Main idea / primary purpose", level:"medium", correct:"C", options:5,
      text:"According to the passage, Ostrom's central point was that the depletion of a commonly owned resource is:",
      choices:["an inevitable consequence of common ownership","avoidable only through privatization of the resource","not automatic but contingent on whether users can govern themselves","impossible once trust among users has broken down","always avoided by long-established traditional communities"],
      hint:"She reframed an 'inevitable' outcome as something else.",
      expl:"The passage says she 'reframed a supposedly inevitable outcome as a contingent one,' depending on users' capacity to communicate, build trust, and enforce agreements (C). (E) is too strong — she noted many communities collapse.\nAnswer: C." },
    { topic:"Supporting detail", level:"medium", correct:"B", options:5,
      text:"The 'graduated sanctions' described in the passage are characterized by:",
      choices:["severe penalties applied equally to every violation","fines that begin small and increase for repeat offenders","punishments imposed by a central state authority","rewards given to users who harvest less than allowed","permanent expulsion of anyone who violates a rule once"],
      hint:"Look at the parenthetical describing the sanctions.",
      expl:"The passage describes 'graduated sanctions that began with small fines and escalated only for repeat offenders' (B).\nAnswer: B." }
  ]},
  { setId:"rc-humanities-jazz", add:[
    { topic:"Main idea / primary purpose", level:"medium", correct:"B", options:5,
      text:"The author's primary purpose in the passage is to:",
      choices:["argue that jazz improvisation requires less skill than is commonly believed","challenge the notion that jazz improvisation is pure spontaneity and recast it as the fluent recombination of practiced material","establish that jazz is superior to ordinary spoken language","demonstrate that artistic constraints eliminate genuine creativity","trace the historical development of jazz improvisation"],
      hint:"The opening calls a popular image 'largely misleading' — what replaces it?",
      expl:"The author rejects the 'pure spontaneity' image and reframes improvisation as rapid recombination of long-practiced elements (B), while insisting this 'does not diminish the achievement.'\nAnswer: B." },
    { topic:"Function / purpose of detail", level:"medium", correct:"B", options:5,
      text:"The author introduces the analogy to language chiefly in order to:",
      choices:["show that jazz is literally a form of spoken language","illustrate how fluency can consist of using constraints skillfully rather than escaping them","argue that grammar is more complex than musical harmony","claim that speakers improvise just as often as musicians do","suggest that jazz ought to be studied using the tools of linguistics"],
      hint:"What point about constraints does the speaker example make?",
      expl:"The language analogy shows a speaker is 'constrained by vocabulary and grammar' yet fluent — freedom lies in deploying constraints well, not escaping them (B), paralleling the soloist.\nAnswer: B." }
  ]},
  { setId:"rc-science-dwarf", add:[
    { topic:"Supporting detail", level:"medium", correct:"B", options:5,
      text:"According to the passage, the absence of large predators on an island contributes to dwarfism because it:",
      choices:["increases the total amount of vegetation available","removes a pressure that had favored large body size","directly reduces the amount of food a smaller body needs","causes prey populations to grow rapidly","eliminates competition among herbivores"],
      hint:"Why does big body size help on the mainland?",
      expl:"On the mainland large size protects against predators; removing predators 'relaxes' that pressure toward large size, letting the food-driven pressure toward small size prevail (B).\nAnswer: B." },
    { topic:"Inference", level:"hard", correct:"B", options:5,
      text:"The 'optimal intermediate size' account differs from the simple island rule in that it predicts that:",
      choices:["all mammals stranded on islands will eventually shrink","the direction of size change depends on a species' starting size, with small species growing and large ones shrinking","islands have essentially no effect on the body size of their animals","predators influence body size more strongly than food supply does","giant tortoises and oversized rodents are exceptions that cannot be explained"],
      hint:"The passage ties the direction of change to the animal's original size.",
      expl:"The intermediate-optimum view holds that very large species shrink and very small ones grow, both converging toward an optimal size (B) — unlike a single 'everything shrinks' rule.\nAnswer: B." }
  ]}

  ];
})();
