/* GMAT Prep — additional practice questions that EXPAND existing sets.
   Merged into the matching window.GMAT_SETS entry at load time (see index.html):
   each question is appended to the set with id === setId, and its `n` is
   assigned automatically. Same question shape as sets.js:
     { topic, correct:"A".., options, text, choices[], hint, expl, level }
   Quant / Data-Insights answer keys here are compute-verified (verify script). */
(function () {
  var DS = ["(1) ALONE sufficient, (2) alone not","(2) ALONE sufficient, (1) alone not","BOTH together sufficient, neither alone","EACH alone sufficient","Together still NOT sufficient"];

  window.GMAT_SETS_EXTRA = [

  /* ---------------- QUANT ---------------- */
  { setId:"quant-percentage-ex", add:[
    { topic:"Percentages & percent change", level:"easy", correct:"B", options:4,
      text:"A shirt's price is first increased by 25% and then the new price is decreased by 20%. Compared with the original price, the final price is:",
      choices:["5% lower","the same","5% higher","4% higher"],
      hint:"Chain the factors: 1.25 then 0.80.",
      expl:"Final factor \\(=1.25\\times0.80=1.00\\), so the price returns to its original value — no net change.\nAnswer: B." },
    { topic:"Percentages & percent change", level:"easy", correct:"C", options:4,
      text:"If 40% of a number is 240, what is 75% of the same number?",
      choices:["360","420","450","480"],
      hint:"Find the whole first.",
      expl:"\\(0.40N=240\\Rightarrow N=600\\). Then \\(0.75\\times600=450\\).\nAnswer: C." },
    { topic:"Percentages & percent change", level:"medium", correct:"B", options:4,
      text:"In a class, 60% of the students are boys. If 20% of the boys and 40% of the girls wear glasses, what percent of the whole class wears glasses?",
      choices:["24%","28%","30%","32%"],
      hint:"Weight each group by its share of the class.",
      expl:"Boys: \\(0.60\\times0.20=0.12\\). Girls: \\(0.40\\times0.40=0.16\\). Total \\(=0.28=28\\%\\).\nAnswer: B." },
    { topic:"Percentages & percent change", level:"medium", correct:"A", options:4,
      text:"The price of sugar rises by 25%. By what percent must a family reduce its consumption so that its total spending on sugar stays the same?",
      choices:["20%","25%","15%","33⅓%"],
      hint:"Spending = price × quantity; keep the product fixed.",
      expl:"To offset a factor of \\(1.25\\), consumption must be multiplied by \\(1/1.25=0.8\\), a reduction of \\(20\\%\\). (In general a \\(+x\\%\\) price needs a \\(\\frac{x}{100+x}\\) cut.)\nAnswer: A." },
    { topic:"Percentages & percent change", level:"medium", correct:"B", options:4,
      text:"A town's population grew by 20% in 2023 and by a further 25% in 2024. Over the two years combined, the population increased by:",
      choices:["45%","50%","55%","22.5%"],
      hint:"Multiply the growth factors, don't add the percents.",
      expl:"\\(1.20\\times1.25=1.50\\), a \\(50\\%\\) increase overall.\nAnswer: B." }
  ]},

  { setId:"quant-ratio-ex", add:[
    { topic:"Ratios & proportions", level:"medium", correct:"A", options:4,
      text:"If \\(a:b = 2:3\\) and \\(b:c = 4:5\\), then \\(a:c\\) equals:",
      choices:["8 : 15","2 : 5","4 : 5","10 : 15"],
      hint:"Make b the same in both ratios.",
      expl:"Scale to a common b: \\(a:b=8:12\\) and \\(b:c=12:15\\), so \\(a:c=8:15\\).\nAnswer: A." },
    { topic:"Ratios & proportions", level:"easy", correct:"C", options:4,
      text:"$720 is divided among A, B and C in the ratio 2 : 3 : 4. C's share is:",
      choices:["$160","$240","$320","$360"],
      hint:"Total parts = 2+3+4.",
      expl:"9 parts \\(=\\$720\\Rightarrow\\) one part \\(=\\$80\\). C gets \\(4\\times80=\\$320\\).\nAnswer: C." },
    { topic:"Ratios & proportions", level:"medium", correct:"A", options:4,
      text:"Two numbers are in the ratio 5 : 8. When 9 is added to each, the ratio becomes 8 : 11. The smaller number is:",
      choices:["15","20","24","18"],
      hint:"Let the numbers be 5k and 8k and cross-multiply.",
      expl:"\\(\\frac{5k+9}{8k+9}=\\frac{8}{11}\\Rightarrow 11(5k+9)=8(8k+9)\\Rightarrow 55k+99=64k+72\\Rightarrow 9k=27,\\ k=3\\). Smaller \\(=5k=15\\).\nAnswer: A." },
    { topic:"Ratios & proportions", level:"medium", correct:"B", options:4,
      text:"A 60-litre mixture contains milk and water in the ratio 2 : 1. How much water must be added to make the ratio 1 : 1?",
      choices:["10 L","20 L","30 L","15 L"],
      hint:"The amount of milk doesn't change.",
      expl:"Milk \\(=40\\) L, water \\(=20\\) L. For 1 : 1 we need water \\(=40\\) L, so add \\(40-20=20\\) L.\nAnswer: B." },
    { topic:"Ratios & proportions", level:"easy", correct:"A", options:4,
      text:"If \\(\\dfrac{x}{3}=\\dfrac{y}{4}=\\dfrac{z}{7}\\), then \\(\\dfrac{x+y+z}{z}\\) equals:",
      choices:["2","\\(\\tfrac72\\)","14","1"],
      hint:"Let the common value be k.",
      expl:"\\(x=3k,\\ y=4k,\\ z=7k\\Rightarrow \\frac{x+y+z}{z}=\\frac{14k}{7k}=2\\).\nAnswer: A." }
  ]},

  { setId:"quant-interest-ex", add:[
    { topic:"Simple & compound interest", level:"easy", correct:"B", options:4,
      text:"Find the simple interest on $2,000 at 5% per annum for 3 years.",
      choices:["$250","$300","$315","$330"],
      hint:"SI = P·r·t.",
      expl:"\\(2000\\times0.05\\times3=\\$300\\).\nAnswer: B." },
    { topic:"Simple & compound interest", level:"medium", correct:"B", options:4,
      text:"A sum of money doubles itself in 8 years at simple interest. In how many years will it triple?",
      choices:["12","16","20","24"],
      hint:"Under SI the interest is a fixed amount per year.",
      expl:"Doubling means the interest earned equals the principal in 8 years. Tripling needs interest equal to twice the principal, i.e. \\(2\\times8=16\\) years.\nAnswer: B." },
    { topic:"Simple & compound interest", level:"easy", correct:"B", options:4,
      text:"What is the compound interest on $10,000 at 10% per annum, compounded annually, for 2 years?",
      choices:["$2,000","$2,100","$2,200","$1,100"],
      hint:"Amount = P(1+r)^t, then subtract P.",
      expl:"\\(10000\\times1.1^2=12100\\); interest \\(=12100-10000=\\$2100\\).\nAnswer: B." },
    { topic:"Simple & compound interest", level:"medium", correct:"A", options:4,
      text:"The difference between the compound interest and the simple interest on a certain sum for 2 years at 10% per annum is $50. The sum is:",
      choices:["$5,000","$2,500","$10,000","$4,000"],
      hint:"For 2 years the difference equals P·r².",
      expl:"Difference \\(=P\\left(\\frac{r}{100}\\right)^2=P(0.1)^2=0.01P=50\\Rightarrow P=\\$5000\\).\nAnswer: A." }
  ]},

  { setId:"quant-speed-ex", add:[
    { topic:"Speed, distance & time", level:"easy", correct:"B", options:4,
      text:"A car covers 150 km in 2 hours 30 minutes. Its average speed is:",
      choices:["55 km/h","60 km/h","62.5 km/h","75 km/h"],
      hint:"Convert the time to hours.",
      expl:"\\(2\\text{h }30\\text{m}=2.5\\) h; speed \\(=150/2.5=60\\) km/h.\nAnswer: B." },
    { topic:"Speed, distance & time", level:"medium", correct:"C", options:4,
      text:"A train 120 m long passes a stationary pole in 6 seconds. The train's speed is:",
      choices:["60 km/h","66 km/h","72 km/h","20 km/h"],
      hint:"To pass a pole, the train travels its own length.",
      expl:"Speed \\(=120/6=20\\) m/s \\(=20\\times\\frac{18}{5}=72\\) km/h.\nAnswer: C." },
    { topic:"Speed, distance & time", level:"medium", correct:"C", options:4,
      text:"Two trains, 100 m and 120 m long, run toward each other on parallel tracks at 40 km/h and 32 km/h. How long do they take to completely pass each other?",
      choices:["9 s","10 s","11 s","12 s"],
      hint:"Add the speeds (opposite directions) and the lengths.",
      expl:"Relative speed \\(=72\\) km/h \\(=20\\) m/s; combined length \\(=220\\) m; time \\(=220/20=11\\) s.\nAnswer: C." },
    { topic:"Speed, distance & time", level:"medium", correct:"B", options:4,
      text:"A boat travels 12 km downstream in 2 hours and returns the same 12 km upstream in 3 hours. The speed of the boat in still water is:",
      choices:["4 km/h","5 km/h","6 km/h","10 km/h"],
      hint:"Still-water speed is the average of downstream and upstream speeds.",
      expl:"Downstream \\(=6\\) km/h, upstream \\(=4\\) km/h; still water \\(=(6+4)/2=5\\) km/h.\nAnswer: B." },
    { topic:"Speed, distance & time", level:"medium", correct:"C", options:4,
      text:"Walking at \\(\\tfrac34\\) of his usual speed, a man reaches his office 20 minutes late. His usual travel time (in minutes) is:",
      choices:["40","45","60","80"],
      hint:"Speed and time are inversely proportional over a fixed distance.",
      expl:"At \\(\\frac34\\) speed the time is \\(\\frac43\\) of usual, i.e. \\(\\frac13\\) longer. That extra \\(\\frac13 T=20\\Rightarrow T=60\\) min.\nAnswer: C." }
  ]},

  { setId:"quant-timework-ex", add:[
    { topic:"Work & rate", level:"medium", correct:"B", options:4,
      text:"A can finish a job in 12 days and B in 18 days. Working together, they finish it in:",
      choices:["6 days","7.2 days","9 days","15 days"],
      hint:"Add the rates.",
      expl:"Combined rate \\(=\\frac1{12}+\\frac1{18}=\\frac{3+2}{36}=\\frac5{36}\\) per day, so time \\(=\\frac{36}{5}=7.2\\) days.\nAnswer: B." },
    { topic:"Work & rate", level:"easy", correct:"B", options:4,
      text:"15 workers build a wall in 8 days. Working at the same rate, how many days would 10 workers take?",
      choices:["10 days","12 days","5⅓ days","16 days"],
      hint:"Total work in worker-days is constant.",
      expl:"Work \\(=15\\times8=120\\) worker-days; with 10 workers, \\(120/10=12\\) days.\nAnswer: B." },
    { topic:"Work & rate", level:"medium", correct:"C", options:4,
      text:"A works twice as fast as B. Together they complete a task in 8 days. B working alone would take:",
      choices:["12 days","16 days","24 days","36 days"],
      hint:"Let B's rate be r; A's is 2r.",
      expl:"Combined rate \\(=3r=\\frac18\\Rightarrow r=\\frac1{24}\\), so B alone needs 24 days.\nAnswer: C." },
    { topic:"Work & rate", level:"medium", correct:"C", options:4,
      text:"An inlet pipe can fill a tank in 6 hours; an outlet pipe can empty the full tank in 9 hours. If both are open on an empty tank, the tank fills in:",
      choices:["12 hours","15 hours","18 hours","3.6 hours"],
      hint:"Net rate = fill rate − drain rate.",
      expl:"Net rate \\(=\\frac16-\\frac19=\\frac{3-2}{18}=\\frac1{18}\\) per hour, so 18 hours.\nAnswer: C." }
  ]},

  { setId:"quant-average-ex", add:[
    { topic:"Weighted averages", level:"easy", correct:"B", options:4,
      text:"The average of 5 numbers is 27. If the number 35 is removed, the average of the remaining four numbers is:",
      choices:["24","25","26","23"],
      hint:"Work with the total sum.",
      expl:"Sum \\(=5\\times27=135\\); after removing 35, sum \\(=100\\), average \\(=100/4=25\\).\nAnswer: B." },
    { topic:"Weighted averages", level:"medium", correct:"C", options:4,
      text:"The average age of 30 students is 12 years. When the teacher's age is included, the average rises to 13 years. The teacher's age is:",
      choices:["40","42","43","45"],
      hint:"Compare the two totals.",
      expl:"Students' total \\(=360\\). With teacher: \\(13\\times31=403\\). Teacher \\(=403-360=43\\).\nAnswer: C." },
    { topic:"Weighted averages", level:"medium", correct:"C", options:4,
      text:"A batsman's average after 10 innings is 40. What must he score in his 11th innings to raise his average to 42?",
      choices:["52","60","62","64"],
      hint:"Target total minus current total.",
      expl:"Needed total \\(=42\\times11=462\\); current \\(=400\\); required score \\(=62\\).\nAnswer: C." },
    { topic:"Weighted averages", level:"medium", correct:"B", options:4,
      text:"What is the average of the first 20 positive even integers (2, 4, …, 40)?",
      choices:["20","21","22","19"],
      hint:"For an evenly spaced list, average = (first + last)/2.",
      expl:"\\((2+40)/2=21\\).\nAnswer: B." }
  ]},

  { setId:"quant-statistics-ex", add:[
    { topic:"Mean, median & mode", level:"easy", correct:"B", options:4,
      text:"The mean of the five numbers 2, 5, 7, x, 10 is 6. The value of x is:",
      choices:["4","6","8","12"],
      hint:"Sum of the five = 5 × mean.",
      expl:"Sum \\(=30\\); the known four sum to 24, so \\(x=6\\).\nAnswer: B." },
    { topic:"Mean, median & mode", level:"medium", correct:"B", options:4,
      text:"A list contains 7 consecutive integers whose median is 20. The greatest of these integers is:",
      choices:["22","23","24","26"],
      hint:"For an odd count of consecutive integers, the median is the middle term.",
      expl:"The 4th term is 20, so the terms are 17…23; the greatest is 23.\nAnswer: B." },
    { topic:"Mean, median & mode", level:"medium", correct:"B", options:4,
      text:"Each number in the set {5, 8, 11, 14, 17} is multiplied by 3. The standard deviation of the new set is the old standard deviation multiplied by:",
      choices:["1","3","9","\\(\\sqrt3\\)"],
      hint:"Scaling every value scales the spread by the same factor.",
      expl:"Multiplying every element by a constant \\(k\\) multiplies the standard deviation by \\(|k|\\); here \\(k=3\\).\nAnswer: B." },
    { topic:"Mean, median & mode", level:"easy", correct:"C", options:4,
      text:"For the data set {4, 4, 6, 8, 8, 8, 10}, the mode is:",
      choices:["4","6","8","10"],
      hint:"The mode is the most frequent value.",
      expl:"8 appears three times, more than any other value.\nAnswer: C." }
  ]},

  { setId:"quant-probability-ex", add:[
    { topic:"Permutations & combinations", level:"medium", correct:"C", options:4,
      text:"How many distinct arrangements can be made from the letters of the word LEVEL?",
      choices:["20","24","30","120"],
      hint:"Divide by the factorials of repeated letters.",
      expl:"LEVEL has 5 letters with L twice and E twice: \\(\\frac{5!}{2!\\,2!}=\\frac{120}{4}=30\\).\nAnswer: C." },
    { topic:"Permutations & combinations", level:"easy", correct:"B", options:4,
      text:"In how many ways can a committee of 3 people be chosen from 8 people?",
      choices:["24","56","112","336"],
      hint:"Order doesn't matter — use a combination.",
      expl:"\\(\\binom{8}{3}=\\frac{8\\cdot7\\cdot6}{3\\cdot2\\cdot1}=56\\).\nAnswer: B." },
    { topic:"Permutations & combinations", level:"medium", correct:"B", options:4,
      text:"Two fair dice are rolled. What is the probability that the sum of the two faces is 8?",
      choices:["\\(\\tfrac16\\)","\\(\\tfrac{5}{36}\\)","\\(\\tfrac19\\)","\\(\\tfrac1{12}\\)"],
      hint:"Count the ordered pairs that total 8 out of 36.",
      expl:"Favorable: (2,6),(3,5),(4,4),(5,3),(6,2) — 5 outcomes. \\(P=5/36\\).\nAnswer: B." },
    { topic:"Permutations & combinations", level:"medium", correct:"A", options:4,
      text:"A bag holds 4 red and 6 blue marbles. Two are drawn at random without replacement. The probability that both are red is:",
      choices:["\\(\\tfrac{2}{15}\\)","\\(\\tfrac16\\)","\\(\\tfrac{4}{25}\\)","\\(\\tfrac15\\)"],
      hint:"Multiply the two conditional probabilities.",
      expl:"\\(\\frac{4}{10}\\times\\frac{3}{9}=\\frac{12}{90}=\\frac{2}{15}\\).\nAnswer: A." }
  ]},

  { setId:"quant-exponents-ex", add:[
    { topic:"Exponent rules", level:"easy", correct:"B", options:4,
      text:"\\(\\dfrac{2^{10}\\times 2^{5}}{2^{12}}\\) equals:",
      choices:["4","8","16","\\(2^{7}\\)"],
      hint:"Add exponents when multiplying, subtract when dividing.",
      expl:"\\(2^{10+5-12}=2^{3}=8\\).\nAnswer: B." },
    { topic:"Exponent rules", level:"easy", correct:"B", options:4,
      text:"If \\(3^{x}=81\\), then \\(3^{x-2}\\) equals:",
      choices:["3","9","27","1"],
      hint:"First find x.",
      expl:"\\(3^x=81=3^4\\Rightarrow x=4\\); \\(3^{4-2}=3^2=9\\).\nAnswer: B." },
    { topic:"Exponent rules", level:"medium", correct:"B", options:4,
      text:"\\((2^{3})^{2}\\times 2^{-4}\\) equals:",
      choices:["2","4","8","16"],
      hint:"Power of a power multiplies exponents.",
      expl:"\\((2^3)^2=2^6\\); \\(2^6\\times2^{-4}=2^{2}=4\\).\nAnswer: B." },
    { topic:"Exponent rules", level:"medium", correct:"B", options:4,
      text:"If \\(5^{2x}=100\\), then \\(5^{x}\\) equals:",
      choices:["5","10","25","50"],
      hint:"Note that \\(5^{2x}=(5^{x})^{2}\\).",
      expl:"\\((5^x)^2=100\\Rightarrow 5^x=10\\) (positive root).\nAnswer: B." }
  ]},

  { setId:"quant-linear-ex", add:[
    { topic:"Linear equations", level:"easy", correct:"C", options:4,
      text:"If \\(3x+5=20\\), then x equals:",
      choices:["3","4","5","15"],
      hint:"Isolate x.",
      expl:"\\(3x=15\\Rightarrow x=5\\).\nAnswer: C." },
    { topic:"Linear equations", level:"medium", correct:"B", options:4,
      text:"If \\(x+y=10\\) and \\(x-y=4\\), then \\(xy\\) equals:",
      choices:["16","21","24","25"],
      hint:"Solve for x and y first.",
      expl:"Adding: \\(2x=14,\\ x=7\\); then \\(y=3\\); \\(xy=21\\).\nAnswer: B." },
    { topic:"Linear equations", level:"easy", correct:"B", options:4,
      text:"A number added to twice itself equals 27. The number is:",
      choices:["8","9","10","13.5"],
      hint:"Translate to x + 2x.",
      expl:"\\(x+2x=3x=27\\Rightarrow x=9\\).\nAnswer: B." },
    { topic:"Linear equations", level:"medium", correct:"C", options:4,
      text:"At a fair, adult tickets cost $8 and child tickets cost $5. A group of 10 tickets cost $68 in total. How many child tickets were bought?",
      choices:["2","3","4","6"],
      hint:"Let c = child tickets; adults = 10 − c.",
      expl:"\\(8(10-c)+5c=68\\Rightarrow 80-3c=68\\Rightarrow c=4\\).\nAnswer: C." }
  ]},

  /* ---------------- DATA INSIGHTS ---------------- */
  { setId:"di-datasufficiency-ex", add:[
    { topic:"Value questions", level:"medium", correct:"B", options:5, choices:DS,
      text:"Is the number x positive?\n(1) \\(x^{2}=9\\)\n(2) \\(x^{3}=27\\)",
      hint:"An even power hides the sign; an odd power keeps it.",
      expl:"(1) \\(x=\\pm3\\) — sign unknown, not sufficient.\n(2) \\(x^3=27\\Rightarrow x=3>0\\) — sufficient.\nOnly (2) alone works.\nAnswer: B." },
    { topic:"Value questions", level:"medium", correct:"E", options:5, choices:DS,
      text:"What is the value of the integer n?\n(1) n is a prime number between 20 and 30.\n(2) n is odd.",
      hint:"List the candidates that satisfy each statement.",
      expl:"(1) primes in (20,30) are 23 and 29 — two values, not sufficient. (2) far too broad. Together, both 23 and 29 are odd primes in range, so n is still not pinned down.\nAnswer: E." },
    { topic:"Value questions", level:"easy", correct:"D", options:5, choices:DS,
      text:"If x and y are positive, is \\(x>y\\)?\n(1) \\(x/y = 1.2\\)\n(2) \\(x-y = 5\\)",
      hint:"Each statement is a yes/no test — you need a definite answer, not a value.",
      expl:"(1) \\(x=1.2y>y\\) (y>0) — definitely yes, sufficient. (2) \\(x=y+5>y\\) — definitely yes, sufficient.\nEach alone answers the question.\nAnswer: D." },
    { topic:"Value questions", level:"medium", correct:"C", options:5, choices:DS,
      text:"What is the area of rectangle R?\n(1) The length of R is 8.\n(2) The perimeter of R is 28.",
      hint:"Area needs both dimensions.",
      expl:"(1) gives length only — insufficient. (2) gives \\(l+w=14\\) — insufficient. Together: \\(w=14-8=6\\), area \\(=8\\times6=48\\) — sufficient.\nAnswer: C." },
    { topic:"Value questions", level:"medium", correct:"C", options:5, choices:DS,
      text:"Is the positive integer k divisible by 6?\n(1) k is divisible by 3.\n(2) k is divisible by 4.",
      hint:"Divisible by 6 means divisible by both 2 and 3.",
      expl:"(1) alone: divisible by 3 but maybe odd — not sufficient. (2) alone: divisible by 4 but maybe not by 3 — not sufficient. Together k is divisible by lcm(3,4)=12, hence by 6 — always yes.\nAnswer: C." }
  ]},

  { setId:"di-twopart-ex", add:[
    { topic:"Quantitative two-part", level:"medium", correct:"C", options:5,
      text:"A vendor sells apples at $2 each and mangoes at $3 each. A customer buys 12 pieces of fruit in total and pays $29. Which pair gives (number of apples, number of mangoes)?",
      choices:["(5, 7)","(6, 6)","(7, 5)","(8, 4)","(9, 3)"],
      hint:"Let a + m = 12 and 2a + 3m = 29.",
      expl:"\\(2a+3(12-a)=36-a=29\\Rightarrow a=7,\\ m=5\\) → (7, 5).\nAnswer: C." },
    { topic:"Quantitative two-part", level:"medium", correct:"B", options:5,
      text:"A factory makes chairs and tables. Each chair uses 3 kg of wood; each table uses 8 kg. One batch used 20 items and 95 kg of wood. Which pair gives (chairs, tables)?",
      choices:["(12, 8)","(13, 7)","(14, 6)","(15, 5)","(11, 9)"],
      hint:"c + t = 20 and 3c + 8t = 95.",
      expl:"\\(3c+8(20-c)=160-5c=95\\Rightarrow 5c=65,\\ c=13,\\ t=7\\) → (13, 7).\nAnswer: B." },
    { topic:"Quantitative two-part", level:"hard", correct:"D", options:5,
      text:"Two investments together total $10,000. One pays 6% annual interest and the other 9%, and the combined interest for one year is $750. Which pair gives (amount at 6%, amount at 9%)?",
      choices:["($3,000, $7,000)","($4,000, $6,000)","($4,500, $5,500)","($5,000, $5,000)","($6,000, $4,000)"],
      hint:"Let x be the amount at 6%; 0.06x + 0.09(10000 − x) = 750.",
      expl:"\\(0.06x+0.09(10000-x)=900-0.03x=750\\Rightarrow 0.03x=150,\\ x=5000\\); the other is $5,000 → ($5,000, $5,000).\nAnswer: D." }
  ]},

  /* ---------------- CRITICAL REASONING ---------------- */
  { setId:"cr-weaken", add:[
    { topic:"Weaken", level:"medium", correct:"B", options:5,
      text:"A city installed brighter streetlights along Main Street, and over the following year the number of traffic accidents there fell by 30%. City officials concluded that the brighter lighting caused the decline. Which of the following, if true, most weakens the officials' conclusion?",
      choices:["The brighter lights also coincided with a drop in street crime along Main Street.","In the same year, the city lowered the speed limit on Main Street and installed speed cameras.","Accidents on streets near Main Street remained unchanged over the year.","The new streetlights cost considerably more than the city had budgeted.","Most Main Street accidents had historically occurred after dark."],
      hint:"Look for another change that could explain the drop.",
      expl:"If the speed limit was lowered and cameras added at the same time (B), those changes could account for the fall in accidents, undercutting the claim that lighting caused it. (C) and (E) would if anything support the conclusion.\nAnswer: B." },
    { topic:"Weaken", level:"medium", correct:"B", options:5,
      text:"A supplement company observes that customers who take its daily vitamin report fewer colds per year than people who take no vitamin, and concludes that the vitamin prevents colds. Which of the following, if true, most weakens the conclusion?",
      choices:["The vitamin is inexpensive and widely available.","People who choose to take a daily vitamin also tend to exercise more and sleep more than those who do not.","Colds are caused by viruses rather than by nutrient deficiencies.","Some customers take the vitamin only during winter months.","The company based its claim on a survey of several thousand customers."],
      hint:"Is there a difference between the two groups other than the vitamin?",
      expl:"If vitamin-takers differ in other health habits (B), those habits — not the vitamin — could explain their fewer colds, a classic self-selection confound.\nAnswer: B." },
    { topic:"Weaken", level:"medium", correct:"B", options:5,
      text:"To cut costs, a hospital plans to replace its brand-name IV bags with a chemically identical generic that costs 40% less. An administrator argues the switch will save money with no downside. Which of the following, if true, most weakens the administrator's argument?",
      choices:["The generic bags are manufactured in the same country as the brand-name bags.","The generic bags come only in sizes that do not fit the hospital's existing infusion pumps, which would all have to be replaced.","The brand-name bags have been used at the hospital for over ten years.","Nurses are more familiar with the brand-name bags' labeling.","The generic manufacturer also supplies other hospital products."],
      hint:"'No downside' fails if the switch triggers a large hidden cost.",
      expl:"If adopting the generic forces the hospital to replace all its infusion pumps (B), that hidden expense could erase the savings — directly attacking the 'no downside' claim.\nAnswer: B." }
  ]},

  { setId:"cr-strengthen", add:[
    { topic:"Strengthen", level:"medium", correct:"B", options:5,
      text:"A researcher claims that a new math app improves scores, noting that students who used it scored higher on a year-end test than students who did not. Which of the following, if true, most strengthens the claim?",
      choices:["The app was designed by experienced classroom teachers.","Before the study, the two groups of students had scored equally on a comparable math pretest.","The app is popular and enjoyable to use.","The year-end test covered some topics the app did not teach.","A few students in the app group used it only occasionally."],
      hint:"Rule out that the groups already differed.",
      expl:"If both groups started equal (B), the later gap is more plausibly due to the app rather than pre-existing ability, strengthening the causal claim.\nAnswer: B." },
    { topic:"Strengthen", level:"medium", correct:"A", options:5,
      text:"A town credits its new curbside recycling program for a drop in landfill tonnage, which fell in the year after the program began. Which of the following, if true, most strengthens the town's conclusion?",
      choices:["Neighboring towns without such a program saw no change in their landfill tonnage over the same year.","The recycling program was more expensive to run than expected.","Residents initially found the sorting rules confusing.","The regional landfill is nearing its capacity.","Recycling participation has been rising nationwide."],
      hint:"Compare against a group that lacked the program.",
      expl:"If comparable towns without the program saw no drop (A), a general regional trend is ruled out and the program becomes the likely cause.\nAnswer: A." },
    { topic:"Strengthen", level:"medium", correct:"B", options:5,
      text:"A company switched to a four-day workweek and total weekly output rose. Management concludes the shorter week caused the increase. Which of the following, if true, most strengthens the claim that the schedule change—rather than another factor—was responsible?",
      choices:["Employees said they enjoyed the extra day off.","The company made no other changes—no new hires, equipment, or pay—when it adopted the four-day week.","Output is measured by the number of units shipped.","Four-day weeks are becoming common in the industry.","A few employees still answered email on their day off."],
      hint:"Eliminate competing explanations for the rise.",
      expl:"If nothing else changed (B), alternative causes for the output rise are removed, so the schedule change is the plausible driver.\nAnswer: B." }
  ]},

  { setId:"cr-assumption", add:[
    { topic:"Assumption", level:"medium", correct:"C", options:5,
      text:"Editorial: Our newspaper should stop printing horoscopes. Horoscopes have no scientific basis, and a serious newspaper should print only material that has scientific support. The argument depends on assuming which of the following?",
      choices:["Readers of the newspaper dislike horoscopes.","Horoscopes are expensive for the newspaper to produce.","The newspaper is, or aims to be, a serious newspaper.","No competing newspaper prints horoscopes.","Every horoscope prediction turns out to be inaccurate."],
      hint:"What links the general rule about 'a serious newspaper' to 'our newspaper'?",
      expl:"The conclusion applies the rule about serious newspapers to this paper, which only follows if this paper is (or means to be) a serious one (C). Negating C breaks the argument.\nAnswer: C." },
    { topic:"Assumption", level:"medium", correct:"B", options:5,
      text:"Company X's profits rose in the year after it relocated its factory overseas. A manager concludes that the relocation increased the company's profits. The argument assumes which of the following?",
      choices:["The overseas factory produces exactly the same products as before.","No other factor was chiefly responsible for the rise in profits during that year.","Overseas labor is less expensive than domestic labor.","The company's profits will keep rising in future years.","Shareholders approved of the relocation."],
      hint:"For a cause-and-effect claim, what must be true about other possible causes?",
      expl:"Concluding the move caused the profit rise assumes no other factor was the real cause (B); otherwise the correlation wouldn't establish causation.\nAnswer: B." },
    { topic:"Assumption", level:"medium", correct:"B", options:5,
      text:"A planner argues that the new bridge will reduce commute times because it offers a more direct route between the suburbs and downtown. The argument assumes which of the following?",
      choices:["The bridge was inexpensive to build.","A substantial number of commuters will actually use the new bridge instead of their current routes.","The old routes into downtown will be permanently closed.","Downtown has enough parking for additional commuters.","The suburbs will continue to grow in population."],
      hint:"A shorter route only helps if people take it.",
      expl:"The benefit depends on commuters actually using the bridge (B); if they keep their old routes, commute times won't fall.\nAnswer: B." }
  ]},

  { setId:"cr-paradox", add:[
    { topic:"Explain the paradox", level:"medium", correct:"B", options:5,
      text:"A retailer cut the price of its umbrellas by 20%, yet its total revenue from umbrella sales rose. Which of the following, if true, best explains this result?",
      choices:["The retailer simultaneously raised the price of its raincoats.","The lower price led to a more-than-proportional increase in the number of umbrellas sold.","Umbrella sales are highly seasonal.","The retailer advertised its raincoats heavily that month.","Several competitors also sell umbrellas."],
      hint:"Revenue = price per unit × units sold.",
      expl:"Revenue can rise despite a price cut if unit sales climb by a larger percentage than the price fell (B).\nAnswer: B." },
    { topic:"Explain the paradox", level:"medium", correct:"B", options:5,
      text:"After a company hired more customer-service agents, the average time customers spent waiting on hold increased. Which of the following, if true, best explains the increase?",
      choices:["The newly hired agents received thorough training.","A concurrent advertising campaign sharply increased the number of customers calling in.","The company uses an automated phone menu to route calls.","Agents are paid by the hour rather than per call.","Some customers prefer to contact the company by email."],
      hint:"Wait time depends on demand relative to capacity, not just on staffing.",
      expl:"If call volume surged at the same time (B), demand could outpace even the enlarged staff, raising wait times.\nAnswer: B." },
    { topic:"Explain the paradox", level:"medium", correct:"B", options:5,
      text:"Over the past decade a country's factories became markedly more energy-efficient per unit of output, yet the country's total industrial energy consumption rose. Which of the following, if true, best resolves this apparent discrepancy?",
      choices:["Energy prices fell steadily over the decade.","Industrial output expanded so greatly that total energy use rose even as energy per unit fell.","Many factories adopted renewable energy sources.","Efficiency gains were measured per worker rather than per unit.","A number of older factories were shut down during the decade."],
      hint:"Total energy = energy per unit × number of units.",
      expl:"If output grew enough (B), total energy use can rise despite lower energy per unit — the scale increase outweighs the efficiency gain.\nAnswer: B." }
  ]},

  { setId:"cr-inference", add:[
    { topic:"Inference / must be true", level:"medium", correct:"B", options:5,
      text:"Every student who passed the certification exam had completed the advanced course. Maria did not complete the advanced course. If the statements above are true, which of the following must also be true?",
      choices:["Maria failed the certification exam.","Maria did not pass the certification exam.","Maria did not take the certification exam.","The advanced course guarantees passing the exam.","Only students in the advanced course may take the exam."],
      hint:"Use the contrapositive; distinguish 'did not pass' from 'failed'.",
      expl:"Passed ⇒ completed the course. Maria didn't complete it, so she could not have passed (B). 'Failed' (A) is too strong — she may not have taken it at all.\nAnswer: B." },
    { topic:"Inference / must be true", level:"medium", correct:"B", options:5,
      text:"In a certain library, every book on the third floor is a reference book, and no reference book may be borrowed. If these statements are true, which of the following must be true?",
      choices:["Every book that cannot be borrowed is on the third floor.","No book on the third floor may be borrowed.","All of the library's reference books are on the third floor.","Some books on the third floor may be borrowed.","All borrowable books are located on the first floor."],
      hint:"Chain the two conditions.",
      expl:"Third-floor ⇒ reference ⇒ not borrowable, so no third-floor book may be borrowed (B). The others reverse or overreach the given conditions.\nAnswer: B." },
    { topic:"Inference / must be true", level:"medium", correct:"B", options:5,
      text:"The company will hold its annual picnic only if at least 30 employees sign up. This year only 22 employees signed up. If the statements are true, which of the following must be true?",
      choices:["The picnic will be rescheduled for a later date.","The company will not hold the picnic this year.","More employees will sign up before the deadline.","The picnic was also canceled last year.","Most employees dislike the picnic."],
      hint:"A necessary condition has not been met.",
      expl:"Holding the picnic requires ≥30 sign-ups; with only 22, that necessary condition fails, so the picnic will not be held (B).\nAnswer: B." }
  ]},

  /* ---------------- FROM DRIVE: GMAT Quant Live Session 1 (answers re-verified) ---------------- */
  { setId:"quant-sets-ages-ex", add:[
    { topic:"Overlapping sets (Venn)", level:"medium", correct:"E", options:5,
      text:"How many attendees are at a convention if 150 of the attendees are neither female nor students, one-sixth of the attendees are female students, two-thirds of the attendees are female, and one-third of the attendees are students?",
      choices:["300","450","600","800","900"],
      hint:"‘Female or student’ = female + student − female-students; the rest are the 150.",
      expl:"\\(|F\\cup S| = \\tfrac23T + \\tfrac13T - \\tfrac16T = \\tfrac56T\\). The remaining \\(\\tfrac16T = 150\\), so \\(T = 900\\).\nAnswer: E." },
    { topic:"Overlapping sets (Venn)", level:"medium", correct:"B", options:5,
      text:"In a group of 68 students, each student is registered for at least one of three classes — History, Math and English. 25 are registered for History, 25 for Math and 34 for English. If only 3 students are registered for all three classes, how many are registered for exactly two classes?",
      choices:["13","10","9","8","7"],
      hint:"Sum of the three counts double-counts the exactly-two students and triple-counts the exactly-three.",
      expl:"Sum \\(=25+25+34=84 = (\\text{exactly 1}) + 2(\\text{exactly 2}) + 3(\\text{exactly 3})\\); total \\(=68=(\\text{ex1})+(\\text{ex2})+(\\text{ex3})\\). Subtract: \\(84-68=(\\text{ex2})+2(3)\\Rightarrow \\text{ex2}=16-6=10\\).\nAnswer: B." }
  ]},
  { setId:"quant-percentage-ex", add:[
    { topic:"Percentages & percent change", level:"medium", correct:"A", options:5,
      text:"A school's annual budget for student computers increased by 60% this year over last year. If the price of a student computer increased by 20% this year, then the number of computers it can purchase this year is what percent greater than the number it purchased last year?",
      choices:["33⅓%","40%","42%","48%","60%"],
      hint:"Quantity = budget ÷ price.",
      expl:"Number bought scales as \\(\\frac{1.60}{1.20}=\\frac{4}{3}\\approx1.333\\), i.e. \\(33\\tfrac13\\%\\) more.\nAnswer: A." },
    { topic:"Percentages & percent change", level:"hard", correct:"D", options:5,
      text:"A corporation's annual report stated that profits were up 10 percent over the previous year, although profits as a percent of sales were down 10 percent. Total sales that year were approximately what percent of sales for the previous year?",
      choices:["78%","90%","110%","122%","190%"],
      hint:"Profit = margin × sales.",
      expl:"\\(P_2=1.1P_1\\) and margin\\(_2=0.9\\,\\)margin\\(_1\\). Since \\(P=\\text{margin}\\times S\\): \\(1.1P_1 = 0.9\\,m_1 S_2\\) and \\(P_1=m_1S_1\\Rightarrow \\frac{S_2}{S_1}=\\frac{1.1}{0.9}\\approx1.22\\).\nAnswer: D." },
    { topic:"Percentages & percent change", level:"hard", correct:"A", options:5,
      text:"A driver paid n dollars for auto insurance in 1997. The premium rose by p percent for 1998; for each of 1999 and 2000 the premium was decreased by 1/6 from the previous year's figure. If the 2000 premium was again n dollars, what is the value of p?",
      choices:["44","12","40","36","50"],
      hint:"Two decreases of 1/6 multiply the premium by (5/6)² .",
      expl:"\\(n(1+\\tfrac{p}{100})(\\tfrac56)^2=n\\Rightarrow 1+\\tfrac{p}{100}=\\tfrac{36}{25}=1.44\\Rightarrow p=44\\).\nAnswer: A." }
  ]},
  { setId:"quant-mixture-ex", add:[
    { topic:"Mixtures & solutions", level:"medium", correct:"A", options:5,
      text:"Grapes are 92% water and raisins are 20% water. A quantity of raisins currently weighs 10 pounds. How much did it weigh when it was all grapes? (Only water evaporates; the solid content is unchanged.)",
      choices:["100 pounds","25 pounds","46 pounds","92 pounds","146 pounds"],
      hint:"The non-water solid stays constant.",
      expl:"Solid in raisins \\(=80\\%\\times10=8\\) lb. As grapes this solid was \\(8\\%\\) of the weight: \\(8/0.08=100\\) lb.\nAnswer: A." },
    { topic:"Mixtures & solutions", level:"medium", correct:"A", options:5,
      text:"A portion of a 50% alcohol solution is replaced with an equal amount of a 25% alcohol solution. If the result is a 30% alcohol solution, what portion of the original solution was replaced?",
      choices:["80%","75%","66%","20%","3%"],
      hint:"Let x be the fraction replaced and balance the alcohol.",
      expl:"\\(50(1-x)+25x=30\\Rightarrow 50-25x=30\\Rightarrow x=0.8\\), i.e. 80%.\nAnswer: A." }
  ]},
  { setId:"quant-profitloss-ex", add:[
    { topic:"Profit, loss & discount", level:"medium", correct:"C", options:5,
      text:"A merchant bought a jacket for $60 and set a selling price equal to the purchase price plus a markup that was 25 percent of the selling price. During a sale the merchant discounted the selling price by 20 percent and sold the jacket. What was the merchant's gross profit?",
      choices:["$0","$3","$4","$12","$15"],
      hint:"The markup is a fraction of the selling price, not the cost.",
      expl:"\\(SP=60+0.25\\,SP\\Rightarrow 0.75\\,SP=60\\Rightarrow SP=80\\). Sale price \\(=0.8\\times80=64\\); profit \\(=64-60=\\$4\\).\nAnswer: C." }
  ]},
  { setId:"quant-ratio-ex", add:[
    { topic:"Ratios & proportions", level:"medium", correct:"A", options:5,
      text:"According to the directions on a can of frozen orange-juice concentrate, 1 can of concentrate is mixed with 3 cans of water. How many 12-ounce cans of concentrate are required to prepare two hundred 6-ounce servings of orange juice?",
      choices:["25","34","50","67","100"],
      hint:"Concentrate is one-quarter of the finished juice by volume.",
      expl:"Total juice \\(=200\\times6=1200\\) oz; concentrate \\(=\\tfrac14\\times1200=300\\) oz \\(=300/12=25\\) cans.\nAnswer: A." }
  ]},
  { setId:"quant-quadratic-ex", add:[
    { topic:"Quadratic equations", level:"hard", correct:"A", options:5,
      text:"A merchant paid $300 for a shipment of x identical calculators. She used 2 of them as demonstrators and sold each of the rest for $5 more than the average cost of the x calculators. If total revenue was $120 more than the cost of the shipment, how many calculators were in the shipment?",
      choices:["30","28","26","25","24"],
      hint:"Average cost is 300/x; set revenue = 420 and clear the fraction.",
      expl:"\\((x-2)\\left(\\tfrac{300}{x}+5\\right)=420\\Rightarrow 5x-\\tfrac{600}{x}=130\\Rightarrow x^2-26x-120=0\\Rightarrow (x-30)(x+4)=0\\Rightarrow x=30\\).\nAnswer: A." }
  ]},
  { setId:"quant-interest-ex", add:[
    { topic:"Simple & compound interest", level:"hard", correct:"B", options:5,
      text:"A certain investment grows at an annual interest rate of 8%, compounded quarterly. Which of the following equations can be solved to find the number of years, x, for the investment to increase by a factor of 16?",
      choices:["\\(16=(1.02)^{x/4}\\)","\\(2=(1.02)^{x}\\)","\\(16=(1.08)^{4x}\\)","\\(2=(1.02)^{x/4}\\)","\\(\\tfrac1{16}=(1.02)^{4x}\\)"],
      hint:"Quarterly rate is 2% and there are 4x quarters; take the fourth root.",
      expl:"\\(16=(1.02)^{4x}\\). Taking the fourth root of both sides: \\(16^{1/4}=2=(1.02)^{x}\\).\nAnswer: B." }
  ]},
  { setId:"di-datasufficiency-ex", add:[
    { topic:"Value questions", level:"medium", correct:"B", options:5, choices:DS,
      text:"Joanna bought only $0.15 stamps and $0.29 stamps. How many $0.15 stamps did she buy?\n(1) She bought an equal number of $0.15 stamps and $0.29 stamps.\n(2) She bought $4.40 worth of stamps.",
      hint:"For (2), look for integer solutions of 15a + 29b = 440.",
      expl:"(1) equal counts give 0.44n for unknown n — not sufficient. (2) \\(15a+29b=440\\) has the unique non-negative solution \\(a=10, b=10\\) — sufficient.\nAnswer: B." },
    { topic:"Value questions", level:"medium", correct:"B", options:5, choices:DS,
      text:"Marta bought several pencils, each either a 23-cent pencil or a 21-cent pencil. How many 23-cent pencils did she buy?\n(1) Marta bought a total of 6 pencils.\n(2) The total value of the pencils was 130 cents.",
      hint:"Solve 23a + 21b = 130 in non-negative integers.",
      expl:"(1) 6 pencils allows many splits — not sufficient. (2) \\(23a+21b=130\\) has the unique solution \\(a=2, b=4\\) — sufficient.\nAnswer: B." },
    { topic:"Value questions", level:"hard", correct:"C", options:5, choices:DS,
      text:"A construction company was paid $500,000 for a project whose only costs were labor and materials. Was the company's profit greater than $150,000?\n(1) The company's total cost was three times its cost for materials.\n(2) The company's profit was greater than its cost for labor.",
      hint:"Let materials = m, labor = l; combine the two relations.",
      expl:"(1) cost \\(=3m\\Rightarrow l=2m\\); profit \\(=500-3m\\) (in $000s) — depends on m, not sufficient. (2) alone: not sufficient. Together: profit \\(>l\\Rightarrow 500-3m>2m\\Rightarrow m<100\\Rightarrow\\) profit \\(>200>150\\) — sufficient.\nAnswer: C." },
    { topic:"Value questions", level:"medium", correct:"C", options:5, choices:DS,
      text:"Of the 60 animals on a certain farm, 2/3 are either cows or pigs. How many of the animals are cows?\n(1) The farm has more than twice as many cows as pigs.\n(2) The farm has more than 12 pigs.",
      hint:"Cows + pigs = 40; find whether the two bounds pin down a single integer.",
      expl:"Cows + pigs \\(=40\\). (1) \\(c>2p\\) alone and (2) \\(p>12\\) alone are each insufficient. Together: \\(c=40-p>2p\\Rightarrow p<13.3\\), and \\(p>12\\Rightarrow p=13\\), so \\(c=27\\) — sufficient.\nAnswer: C." }
  ]},

  /* ---- Boldface CR (from the Drive "RC + CR Session 6" doc; answer key from that doc).
          [[...]] marks the boldface portions the question asks about. ---- */
  { setId:"cr-boldface", add:[
    { topic:"Boldface & method of reasoning", level:"medium", correct:"E", options:5,
      text:"Researcher: [[The rate of psychological problems is higher among children of divorced parents than among other children.]] But it would be a mistake to conclude that these problems are caused by the difficulty the children have adjusting to divorce. It is just as reasonable to infer that certain behaviours that increase the likelihood of divorce — hostility, distrust, lack of empathy — are learned by children from their parents, and that it is these learned behaviours that cause the children's psychological problems.\nThe boldface portion plays which one of the following roles?",
      choices:["It is the conclusion of the argument.","It is the claim that the argument tries to refute.","It is offered as evidence for the claim that divorce is harmful to the children of the divorcing parents.","It is offered as evidence for the claim that certain behaviours are often responsible for divorce.","It is cited as an established finding for which the argument proposes an explanation."],
      hint:"Is the boldface disputed, or is it the accepted fact being explained?",
      expl:"The researcher accepts the higher rate as established and then argues about what explains it — offering a rival explanation. Answer: E." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"C", options:5,
      text:"It is primarily by raising interest rates that central bankers curb inflation, but [[an increase in interest rates takes up to two years to affect inflation]]. Accordingly, central bankers usually try to raise interest rates before inflation becomes excessive, at which time inflation is not yet readily apparent either. But unless inflation is readily apparent, interest-rate hikes generally will be perceived as needlessly restraining a growing economy. Thus, central bankers' success in temporarily restraining inflation may make it harder for them to ward off future inflation without incurring the public's wrath.\nThe boldface portion plays which one of the following roles?",
      choices:["It is presented as a complete explanation of the final claim.","It is a description of a phenomenon for which the rest of the argument offers an explanation.","It is a premise offered in support of the conclusion that central bankers' success may make it harder to ward off future inflation.","It is a conclusion supported by the claim that rate rises take two years to work.","It is a premise supporting the claim that hikes will be perceived as needlessly restraining the economy."],
      hint:"Find the final conclusion, then ask whether the boldface supports it.",
      expl:"The lag is a premise in the chain leading to the final conclusion about future inflation and public wrath. Answer: C." },
    { topic:"Boldface & method of reasoning", level:"medium", correct:"C", options:5,
      text:"After an area has been hit by a natural disaster, there is often a great demand for plywood. Retailers raise prices on new shipments, and some people denounce them for profiteering. In fact, however, these retailers do not make more money on each sheet of plywood than before the disaster, because [[transporting the plywood into devastated areas is difficult and expensive, and therefore the plywood's cost to retailers is higher than it was before the disaster]].\nThe boldface portion plays which of the following roles?",
      choices:["a counterexample to a claim","the main conclusion toward which the argument as a whole is directed","a subsidiary conclusion used to support the main conclusion of the argument","an example used to illustrate the implausibility of the position argued against","background information used to provide a context for the argument"],
      hint:"The main conclusion is that retailers don't earn more per sheet — what does the boldface do for it?",
      expl:"Higher wholesale cost is itself concluded from the difficulty of transport, and then used to support the main conclusion — a subsidiary conclusion. Answer: C." },
    { topic:"Boldface & method of reasoning", level:"medium", correct:"A", options:5,
      text:"Some biologists believe that the capacity for flight first developed in marine reptiles, claiming that feathers clearly developed from scales. Other biologists rightly reject this suggestion, pointing out that [[bats have no scales and that non-marine reptiles also have scales]]. Those who believe that flight first developed in tree-dwelling reptiles reject the claim that the limbs of land-dwelling reptiles might have developed into wings.\nThe boldface portion plays which of the following roles?",
      choices:["It is cited as evidence against the claim that the capacity for flight first developed in marine reptiles.","It is cited as evidence against the claim that the capacity for flight first developed in land-dwelling animals.","It is cited as evidence against the claim that the capacity for flight first developed in tree-dwelling reptiles.","It weakens the claim that tree-dwelling reptiles were the first to develop flight.","It corroborates the observation that some mammals without scales developed the capacity to fly."],
      hint:"Which claim does the bats-and-scales point attack?",
      expl:"It rebuts the feathers-from-scales reasoning, i.e. the marine-reptile claim. Answer: A." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"B", options:5,
      text:"Pedigreed dogs must conform to standards set by pedigree organizations. Those standards specify physical appearance but stipulate nothing about other genetic traits, such as those that let working breeds do their work. Since breeders try to maintain only the traits pedigree organizations specify, and [[traits that breeders do not try to maintain risk being lost, certain traits like herding ability risk being lost among pedigreed dogs]]. Therefore, pedigree organizations should set standards requiring working ability in pedigreed dogs classified as working dogs.\nThe boldface portion plays which one of the following roles?",
      choices:["It is a claim on which the argument depends but for which no support is given.","It is a subsidiary conclusion used in support of the main conclusion.","It acknowledges a possible objection to the proposal put forth in the argument.","It summarizes the position the argument is directed toward discrediting.","It provides evidence necessary to support a claim stated earlier."],
      hint:"The final sentence is the main conclusion — what does the boldface do for it?",
      expl:"That herding ability risks being lost is itself concluded from the preceding premises, then used to support the recommendation. Answer: B." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"D", options:5,
      text:"Economist: Tropicorp has been clearing tropical forest for cattle ranching, although pastures there become useless after a few years. It has not gone into rubber tapping, even though greater profits can be made from rubber tapping, which leaves the forest intact. Thus, some environmentalists argue that [[Tropicorp's actions do not serve even its own economic interest]]. However, the initial investment for rubber tapping is larger, there is a shortage of workers employable in rubber tapping, and taxes are higher on rubber-tapping profits. Consequently, [[the environmentalists' conclusion is probably wrong]].\nIn the economist's argument, the two boldface portions play which of the following roles?",
      choices:["The first supports the economist's conclusion; the second calls it into question.","The first states the economist's conclusion; the second supports it.","The first supports the environmentalists' conclusion; the second states that conclusion.","The first states the environmentalists' conclusion; the second states the economist's conclusion.","Each supports the economist's conclusion."],
      hint:"Whose conclusion is each portion?",
      expl:"The first is the environmentalists' conclusion; the second is the economist's own conclusion rejecting it. Answer: D." },
    { topic:"Boldface & method of reasoning", level:"medium", correct:"B", options:5,
      text:"Boreal owls range over a much larger area than do other owls of similar size. Scientists have hypothesized that [[it is scarcity of prey that leads the owls to range so widely]]. This hypothesis would be hard to confirm directly, since it is not possible to count the small mammals in the forests where boreal owls live. Careful study has shown that [[boreal owls do range over larger areas when they live in regions where food of the sort eaten by small mammals is comparatively sparse]]. This indicates that the scientists' hypothesis is not sheer speculation.\nThe two boldface portions play which of the following roles?",
      choices:["The first presents an explanatory hypothesis; the second states the main conclusion of the argument.","The first presents an explanatory hypothesis; the second presents evidence tending to support this hypothesis.","The first presents an explanatory hypothesis; the second presents evidence to support an alternative explanation.","The first describes a position the argument opposes; the second undermines support for that position.","The first describes a position the argument opposes; the second states the main conclusion."],
      hint:"The last sentence is the conclusion — so what is the second boldface?",
      expl:"The first is the hypothesis; the second is the observed evidence supporting it (the conclusion is the final sentence). Answer: B." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"A", options:5,
      text:"A prominent investor claims the Burton Tool Company is mismanaged, citing its failure to slow production after a rise in inventory of finished products. It is doubtful whether an investor's sniping at management can ever be productive, but in this case it is clearly not justified. It is true that [[an increased inventory of finished products often indicates that production is outstripping demand]], but in Burton's case it indicates no such thing. Rather, [[the increase in inventory is entirely attributable to products that have already been assigned to orders received from customers]].\nThe two boldface portions play which of the following roles?",
      choices:["The first states a generalization underlying the position the argument opposes; the second provides evidence that the generalization does not apply in this case.","The first states a generalization underlying the opposed position; the second clarifies the meaning of a phrase in that generalization.","The first supports the argument's conclusion; the second is evidence used to support the opposed position.","The first supports the argument's conclusion; the second states that conclusion.","Each provides evidence against the opposed position."],
      hint:"The investor's case rests on a general rule — what does the second boldface do to it?",
      expl:"The first is the generalization the investor relies on; the second shows it doesn't apply here. Answer: A." },
    { topic:"Boldface & method of reasoning", level:"medium", correct:"E", options:5,
      text:"Letter to the editor: Proposition Q would prohibit handgun ownership in the city. Proponents argue that [[fewer handguns on the streets would lead to less violent crime]]. Unfortunately, the ban would actually have the opposite effect. Since only law-abiding citizens would honour the ban, [[armed criminals would not only keep their weapons but would also have the confidence to act with impunity on a population that could no longer defend itself]].\nThe two boldface portions play which of the following roles?",
      choices:["The first is an observation the author uses to support a position; the second is that position.","The first is a pattern of cause and effect the author believes true; the second offers evidence to contradict it.","The first is a position the author argues will not hold; the second is the author's position.","The first is a prediction the author believes untrue; the second undermines the author's position.","The first is a direct relationship the author believes will not hold in this case; the second offers evidence in support of the author's position."],
      hint:"The author rejects the first — and the second explains why.",
      expl:"The first is the proponents' claimed relationship, which the author denies; the second supports the author's opposing view. Answer: E." },
    { topic:"Boldface & method of reasoning", level:"medium", correct:"B", options:5,
      text:"Traditionally, video-game manufacturers have been most strongly influenced by serious gamers. Because devoted gamers have historically purchased most games, [[most manufacturers continue to produce games with faster chips and flashier graphics]]. Unfortunately, faster chips and flashier graphics are no longer in the industry's best interest. The devoted gaming market is stagnant and won't soon expand. To infuse new life into the market, manufacturers must simplify the functionality of their games, because [[current non-gamers will then be attracted to join the ranks of video-game fans]].\nThe two boldface portions play which of the following roles?",
      choices:["The first is a situation the author believes true; the second explains it.","The first is a situation the author argues should not continue; the second supports the author's position.","The first is a fact that contradicts the author's position; the second is the author's position.","The first supports the author's position; the second weighs against it.","The first is a prediction the author rejects; the second is an assumption against the author's position."],
      hint:"The author says the current practice is no longer in the industry's interest.",
      expl:"The first describes the practice the author says should stop; the second backs the author's proposed alternative. Answer: B." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"D", options:5,
      text:"Marketing analyst: [[Traditionally, introducing a new consumer product contributes to the diversity of a company's product mix and results in an overall increase in revenues and profits.]] However, our launch of Cool Breeze will almost certainly reduce rather than increase profits. Since we already offer a line of chilled refreshments very similar to Cool Breeze, [[the launch is likely to cannibalize our current sales rather than attract new customers]].\nThe two boldface portions play which of the following roles?",
      choices:["The first is a pattern the analyst predicts will be repeated here; the second acknowledges a circumstance in which it would not hold.","The first is a generalization the analyst accepts as true; the second is a consequence that follows from it.","The first acknowledges a consideration against the analyst's conclusion; the second is that conclusion.","The first is a pattern of cause and effect the analyst predicts will not hold in this case; the second offers a consideration in support of that prediction.","The first is evidence for a prediction; the second is that prediction."],
      hint:"Does the analyst think the usual pattern applies to Cool Breeze?",
      expl:"The analyst says the usual pattern will NOT hold here; the second supports that prediction. Answer: D." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"B", options:5,
      text:"Editorial: An arrest in Midville is provisional until a watch commander approves it. A government efficiency expert found that almost all provisional arrests meet the evidence standards commanders enforce. [[The expert therefore recommends that the watch commander's approval should no longer be required, since the officers' time spent obtaining approval is largely wasted.]] [[This recommendation should be rejected as dangerous]], since there is no assurance that the commanders' standards will continue to be observed once approval is no longer required.\nThe two boldface portions play which of the following roles?",
      choices:["The first is a recommendation made by the editorial; the second acknowledges a potential objection to it.","The first is a proposal against which the editorial is directed; the second is a judgment reached by the editorial about that proposal.","The first provides evidence for a recommendation the editorial supports; the second is the editorial's conclusion.","The first is a position the editorial challenges; the second is a judgment made in support of that challenged position.","The first is a recommendation the editorial questions; the second provides evidence against it."],
      hint:"Whose recommendation is the first — and what does the editorial do with it?",
      expl:"The first is the expert's proposal that the editorial opposes; the second is the editorial's verdict on it. Answer: B." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"B", options:5,
      text:"[[During the past year, Pro-Tect Insurance's total payout on car-theft claims has been larger than the company can afford to sustain.]] Pro-Tect cannot reduce the number of car-theft policies it carries. Therefore it has decided to offer a discount to policyholders whose cars have antitheft devices. Many policyholders will install such devices, since the discount will typically more than cover the cost within two years. Thus, because cars with antitheft devices are rarely stolen, [[Pro-Tect's plan is likely to reduce its annual payouts]].\nThe two boldface portions play which of the following roles?",
      choices:["Each is evidence offered in support of the main conclusion.","The first presents a problem a response to which the argument assesses; the second is the judgment reached by that assessment.","The first is the position the argument seeks to establish; the second supports that position.","The first is a development the argument seeks to explain; the second is a prediction supporting that explanation.","The first presents a development whose outcome is at issue; the second is a judgment used in support of the conclusion."],
      hint:"The first sets up the problem; the second is the verdict on the proposed fix.",
      expl:"The first states the problem prompting the plan; the second is the argument's conclusion assessing that plan. Answer: B." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"C", options:5,
      text:"Rain-soaked soil contains less oxygen than drier soil. Melon roots perform less efficiently in low-oxygen conditions, and then do not supply enough nutrients for photosynthesis at the usual level. [[It follows that melon plants have a lower-than-usual rate of photosynthesis when their roots are in rain-soaked soil.]] When photosynthesis slows, sugar stored in the fruits is drawn off to supply the plants with energy. Therefore, [[ripe melons harvested after a prolonged period of heavy rain should be less sweet than other ripe melons]].\nThe two boldface portions play which of the following roles?",
      choices:["The first states the conclusion of the argument as a whole; the second supports it.","The first supports the overall conclusion; the second supports an objection to it.","The first supports an intermediate conclusion that supports a further conclusion; the second states that further conclusion.","The first is an intermediate conclusion supporting a further conclusion; the second states the position the argument opposes.","The first states the position the argument opposes; the second supports the conclusion."],
      hint:"Two conclusions in a chain — which is final?",
      expl:"The first is an intermediate conclusion; the second (melons less sweet) is the final conclusion. Note the wording: the intermediate supports the further conclusion stated second. Answer: C." },
    { topic:"Boldface & method of reasoning", level:"hard", correct:"C", options:5,
      text:"Plant scientists have used genetic engineering on seeds to produce crop plants highly resistant to insect damage. [[Unfortunately, the seeds are expensive, and the plants require more fertilizer and water.]] Consequently, for most farmers the savings on pesticides cannot compensate for the higher costs. However, since [[consumer demand for produce grown without pesticides continues to rise]], the use of these genetically engineered seeds is likely to become widespread.\nThe two boldface portions play which of the following roles?",
      choices:["The first supplies a context for the argument; the second is the argument's main conclusion.","The first introduces a development the argument predicts will have a certain outcome; the second contributes to bringing about that outcome.","The first presents a development the argument predicts will have a certain outcome; the second acknowledges a consideration weighing against that prediction.","The first provides evidence supporting a prediction the argument defends; the second is that prediction.","Each provides evidence supporting the argument's main conclusion."],
      hint:"Which portion pushes against the final prediction, and which supports it?",
      expl:"The first is the cost drawback weighing against widespread use; the second is the rising demand that nonetheless drives the predicted outcome. Per the source key, Answer: C." }
  ]}

  ];
})();
