/* GMAT Prep — Reading Comprehension 700-800.
   Source: "RC Latest 700-800 Level Questions" (Sandeep Gupta) in the user's
   Drive, 01. GMAT / 04. Study Content / 03. Verbal, with the answers taken from
   its companion solutions volume, which marks the credited choice CORRECT and
   explains every option. Fourteen passages, 48 questions.

   Three of these passages already appear in the bank in shorter form (as
   rc-ss-phocids/seals, rc-ss-downsizing and rc-ss-birds, one question each).
   The source's fuller text supports questions the condensed version cannot, so
   those passages are kept here in full and their one already-loaded question is
   omitted; the three overlapping answers agree with what the bank already
   stored. Every stored answer here matches the solutions volume AND was
   reasoned out independently before the question was accepted.

   One correction to the source: rc-700-labor-myths #4 (what the author suggests
   about the consulting firms' advice) was stored with key A, "It often fails to
   bring about the intended changes in companies' compensation systems." The
   passage says the opposite — the compensation changes do get made, and it is
   those changes that "create new problems". What the passage does support is E:
   the firms' mainstay is compensation work and recommending anything else is
   "contrary to the consultants' interests", so a less narrowly specialised firm
   would have no such reason to push pay changes. The key is corrected to E and
   the explanation rewritten.

   Questions that referred to "the highlighted text" or to a line number have
   the passage span marked in bold instead, since the app has no line numbers.
   Appends to window.GMAT_SETS_NEW, which index.html merges into GMAT_SETS. */
(function () {
  var Q = function (n, topic, correct, text, choices, hint, expl, level) {
    return { n: n, topic: topic, correct: correct, options: choices.length,
             level: level || "medium", text: text, choices: choices,
             hint: hint, expl: expl };
  };

  window.GMAT_SETS_NEW = (window.GMAT_SETS_NEW || []).concat([
  { id: "rc-700-housework", title: "Passage — Household Technology and Housework", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "Did Modern Appliances Save Labor?", paras: [
      "[[The idea that equipping homes with electrical appliances and other “modern” household technologies would eliminate drudgery, save labor time, and increase leisure for women who were full-time home workers]] remained largely unchallenged until the women’s movement of the 1970’s spawned the groundbreaking and influential works of sociologist Joann Vanek and historian Ruth Cowan. Vanek analyzed 40 years of time-use surveys conducted by home economists to argue that electrical appliances and other modern household technologies reduced the effort required to perform specific tasks, but ownership of these appliances did not correlate with less time spent on housework by full-time home workers. In fact, time spent by these workers remained remarkably constant—at about 52 to 54 hours per week—from the 1920’s to the 1960’s, a period of significant change in household technology. In surveying two centuries of household technology in the United States, Cowan argued that the “industrialization” of the home often resulted in more work for full-time home workers because the use of such devices as coal stoves, water pumps, and vacuum cleaners tended to reduce the workload of married-women’s helpers (husbands, sons, daughters, and servants) while promoting a more rigorous standard of housework. The full-time home worker’s duties also shifted to include more household management, child care, and the post-Second World War phenomenon of being “Mom’s taxi.”" ] },
    questions: [
      Q(1, "Supporting detail", "A", "According to the passage, which of the following is true about the idea mentioned in the text in bold?",
        ["It has been undermined by data found in time-use surveys conducted by home economists.",
         "It was based on a definition of housework that was explicitly rejected by Vanek and Cowan.",
         "It is more valid for the time period studied by Cowan than for the time period studied by Vanek.",
         "It is based on an underestimation of the time that married women spent on housework prior to the industrialization of the household.",
         "It inaccurately suggested that new household technologies would reduce the effort required to perform housework."],
        "The bolded idea went unchallenged until Vanek and Cowan. Ask what Vanek actually used against it.",
        "Where to look — Vanek \"analyzed 40 years of time-use surveys conducted by home economists\" and found that owning the appliances did not correlate with less time on housework.\nWhy (A) — that is data from time-use surveys by home economists, used to undermine the bolded idea.\n(B) No definition of housework is stated, let alone rejected. Cowan in fact widens what counts as housework rather than disputing a definition.\n(C) Neither scholar's period is said to fit the idea better; both find against it.\n(D) The idea is about the future effect of appliances, not about an estimate of pre-industrial housework hours.\n(E) The passage grants that the technologies [[did]] reduce the effort per task. What they failed to reduce was the time.", "medium"),
      Q(2, "Main idea / primary purpose", "C", "The passage is primarily concerned with",
        ["analyzing a debate between two scholars",
         "challenging the evidence on which a new theory is based",
         "describing how certain scholars’ work countered a prevailing view",
         "presenting the research used to support a traditional theory",
         "evaluating the methodology used to study a particular issue"],
        "One sentence sets up a prevailing view; the rest reports what two scholars found.",
        "The shape of the passage — an idea that went unchallenged, then Vanek's time-use finding that hours held constant, then Cowan's finding that industrialization often meant more work for the full-time home worker.\nWhy (C) — describing how those scholars' work countered a prevailing view is exactly the structure.\n(A) Vanek and Cowan are not in dispute with each other; their findings point the same way.\n(B) The author reports their evidence without challenging it.\n(D) The traditional idea is the target here, not something the research supports.\n(E) Vanek's method is named but never assessed for soundness.", "easy"),
      Q(3, "Inference", "D", "The passage suggests that Vanek and Cowan would agree that modernizing household technology did not",
        ["reduce the workload of servants and other household helpers",
         "raise the standard of housework that women who were full-time home workers set for themselves",
         "decrease the effort required to perform household tasks",
         "reduce the time spent on housework by women who were full-time home workers",
         "result in a savings of money used for household maintenance"],
        "Find the claim both scholars are committed to denying.",
        "Where to look — Vanek: hours stayed at 52 to 54 a week through decades of technological change. Cowan: industrialization often produced [[more]] work for the full-time home worker.\nWhy (D) — both are committed to the view that modernization did not reduce the time such women spent on housework.\n(A) Cowan says the devices did reduce helpers' workloads; that is her point, not something she denies.\n(B) Cowan says standards became more rigorous, so this rose rather than stayed flat.\n(C) Vanek explicitly grants that effort per task fell.\n(E) Money spent on household maintenance is never discussed.", "medium")
    ] },

  { id: "rc-700-partnerships", title: "Passage — Japanese Firms and Strategic Partnerships", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "Strategic Partnerships and Market Exchange", paras: [
      "In recent years, Western business managers have been heeding [[the exhortations of business journalists and academics to move their companies toward long- term, collaborative “strategic partnerships” with their external business partners (e.g., suppliers)]]. The experts’ advice comes as a natural reaction to numerous studies conducted during the past decade that compared Japanese production and supply practices with those of the rest of the world. The link between the success of a certain well-known Japanese automaker and its effective management of its suppliers, for example, has led to an unquestioning belief within Western management circles in the value of strategic partnerships. Indeed, in the automobile sector all three United States manufacturers and most of their European competitors have launched programs to reduce their total number of suppliers and move toward having strategic partnerships with a few. However, new research concerning supplier relationships in various industries demonstrates that the widespread assumption of Western managers and business consultants that Japanese firms manage their suppliers primarily through strategic partnerships is unjustified. Not only do Japanese firms appear to conduct a far smaller proportion of their business through strategic partnerships than is commonly believed, but they also make extensive use of “market- exchange” relationships, in which either party can turn to the marketplace and shift to different business partners at will, a practice usually associated with Western manufacturers." ] },
    questions: [
      Q(1, "Main idea / primary purpose", "C", "The passage is primarily concerned with",
        ["examining economic factors that may have contributed to the success of certain Japanese companies",
         "discussing the relative merits of strategic partnerships as compared with those of market- exchange relationship",
         "challenging the validity of a widely held assumption about how Japanese firms operate",
         "explaining why Western companies have been slow to adopt a particular practice favored by Japanese companies",
         "pointing out certain differences between Japanese and Western supplier relationships"],
        "The pivot is \"However\". Whatever follows it is where the passage is going.",
        "The shape of the passage — Western managers are urged towards strategic partnerships because they believe Japanese firms work that way; \"However, new research ... demonstrates that the widespread assumption ... is unjustified.\"\nWhy (C) — challenging the validity of a widely held assumption about how Japanese firms operate.\n(A) The Japanese automaker's success is mentioned as the source of the belief, not analysed for its causes.\n(B) No merits are weighed; the passage disputes a factual claim about what Japanese firms do.\n(D) Western firms are described as adopting the practice enthusiastically, not slowly.\n(E) Differences are noted in passing, but the point is that the assumed difference is not real.", "easy"),
      Q(2, "Supporting detail", "E", "According to the passage, the advice referred to in the text in bold was a response to which of the following?",
        ["A recent decrease in the number of available suppliers within the United States automobile industry",
         "A debate within Western management circles during the past decade regarding the value of strategic partnerships",
         "The success of certain European automobile manufacturers that have adopted strategic partnerships",
         "An increase in demand over the past decade for automobiles made by Western manufacturers",
         "Research comparing Japanese business practices with those of other nations"],
        "The sentence right after the bolded advice says what it was a reaction to.",
        "Where to look — \"The experts' advice comes as a natural reaction to numerous studies conducted during the past decade that compared Japanese production and supply practices with those of the rest of the world.\"\nWhy (E) — research comparing Japanese business practices with those of other nations, which is that sentence in other words.\n(A) A decrease in available suppliers is not mentioned; Western firms are cutting supplier numbers themselves, which is a result of the advice.\n(B) The passage describes an \"unquestioning belief\", not a debate.\n(C) The European manufacturers are following the advice, not the reason for it.\n(D) Demand for Western cars is never discussed.", "easy"),
      Q(3, "Function / purpose of detail", "B", "The author mentions “the success of a certain well- known Japanese automaker” most probably in order to",
        ["demonstrate some of the possible reasons for the success of a certain business practice",
         "cite a specific case that has convinced Western business experts of the value of a certain business practice",
         "describe specific steps taken by Western automakers that have enabled them to compete more successfully in a global market",
         "introduce a paradox about the effect of a certain business practice in Japan",
         "indicate the need for Western managers to change their relationships with their external business partners"],
        "Read the sentence the phrase sits in and ask what it says the automaker's success has led to.",
        "Where to look — the link between that automaker's success and its supplier management \"has led to an unquestioning belief within Western management circles in the value of strategic partnerships.\"\nWhy (B) — a specific case that convinced Western business experts of the value of a certain practice.\n(A) The reasons for the automaker's success are never explored; only what Western managers concluded from it.\n(C) The example is Japanese, and the Western steps described come afterwards as a consequence.\n(D) Nothing paradoxical is introduced; the example is presented as straightforwardly persuasive.\n(E) The author is questioning the belief, not endorsing a call for Western managers to change.", "medium"),
      Q(4, "Inference", "E", "Which of the following is most clearly an example of the practice referred to in the last sentence of the passage?",
        ["A department store chain that employs a single buyer to procure all the small appliances to be sold in its stores",
         "An automobile manufacturer that has used the same supplier of a particular axle component for several years in a row",
         "A hospital that contracts only with union personnel to staff its nonmedical positions",
         "A municipal government that decides to cancel its contract with a waste disposal company and instead hire its own staff to perform that function",
         "A corporation that changes the food-service supplier for its corporate headquarters several times over a five-year period as part of a cost-cutting campaign."],
        "The last sentence describes market-exchange relationships. Look for the example that fits that definition.",
        "Where to look — market exchange is where \"either party can turn to the marketplace and shift to different business partners at will.\"\nWhy (E) — a corporation that changes its food-service supplier several times in five years is shifting partners at will, which is the practice described.\n(A) A single buyer procuring everything is about internal organisation, not about switching suppliers.\n(B) Using the same supplier for years is the opposite — a long-term relationship.\n(C) Contracting only with union personnel is a standing restriction, not free movement in the market.\n(D) Bringing the function in-house removes the supplier relationship altogether rather than exercising it.", "medium")
    ] },

  { id: "rc-700-skus", title: "Passage — Forecasting Demand Across SKUs", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "Why Production and Demand Keep Missing", paras: [
      "Companies that must determine well in advance of the selling season how many units of a new product to manufacture often under-produce products that sell well and have overstocks of others. The increased incidence in recent years of mismatches between production and demand seems ironic, since point-of- sale scanners have improved data on consumers’ buying patterns and since flexible manufacturing has enabled companies to produce, cost-effectively, small quantities of goods. This type of manufacturing has greatly increased the number of new products introduced annually in the United States. However, frequent introductions of new products have two problematic side effects. For one, they reduce the average lifetime of products; more of them are either at the beginning of their life (when prediction is difficult) or at the end of their life (when keeping inventory is expensive because the products will soon become obsolete). For another, as new products proliferate, demand is divided among a growing number of stock-keeping units (SKU’s). Even though manufacturers and retailers can forecast aggregate demand with some certainty, forecasting accurately how that demand will be distributed among the many SKU’s they sell is difficult. For example, a company may be able to estimate accurately the aggregate number of shoes it will sell, but it may be uncertain about which specific types of shoes will sell more than other types." ] },
    questions: [
      Q(1, "Function / purpose of detail", "C", "Which of the following most accurately describes the function of the last sentence in the passage?",
        ["To cite a situation in which the aggregate demand is more important than the distribution of demand among SKU’s",
         "To refute an assertion about the side effects of flexible manufacturing",
         "To illustrate an assertion about companies’ ability to forecast demand",
         "To provide an example of ways in which companies address the difficulties of forecasting demand",
         "To note an exception to the author’s assertion about distributing demand among SKU’s"],
        "The last sentence begins \"For example\". Example of what?",
        "Where to look — the sentence before it says forecasting aggregate demand is fairly reliable but forecasting its distribution across SKUs is difficult; then the shoe example says exactly that.\nWhy (C) — it illustrates that assertion about companies' ability to forecast demand.\n(A) It does not claim aggregate demand matters more; it contrasts what can and cannot be predicted.\n(B) Nothing is refuted; the example supports the point just made.\n(D) No method of addressing the difficulty is described.\n(E) It is an instance of the assertion, not an exception to it.", "easy"),
      Q(2, "Inference", "E", "The passage suggests which of the following about divided demand among a growing number of SKU’s?",
        ["It has increased the average lifetime of products.",
         "It has resulted from retailer’s attempts to predict demand more accurately and avoid both understocks and overstocks.",
         "It has decreased the use of flexible manufacturing by companies.",
         "It has not increased the expense of keeping inventory of certain products.",
         "It has not prevented companies from predicting aggregate demand with some certainty."],
        "The passage says what companies can still do even with demand split across many SKUs.",
        "Where to look — \"Even though manufacturers and retailers can forecast aggregate demand with some certainty, forecasting accurately how that demand will be distributed among the many SKU's they sell is difficult.\"\nWhy (E) — the split has not stopped companies predicting aggregate demand with some certainty.\n(A) Frequent new products [[reduce]] average product lifetime.\n(B) The division follows from the proliferation of new products, not from attempts to forecast better.\n(C) Flexible manufacturing is what enabled the proliferation; nothing says its use has fallen.\n(D) End-of-life products are stated to be expensive to hold, so inventory expense has risen.", "medium"),
      Q(3, "Supporting detail", "D", "According to the passage, which of the following has led to growth in the number of new products introduced in the United States each year?",
        ["Reduced average lifetime of products",
         "Increased ability to forecast aggregate demand",
         "More cost-effective ways of keeping inventory for products",
         "Cost-effective production of small quantities of goods",
         "Increased ability to divide demand among a number of SKU’s and to forecast how that demand will be distributed among those SKU’s"],
        "One sentence names the cause of the increase directly.",
        "Where to look — flexible manufacturing \"has enabled companies to produce, cost-effectively, small quantities of goods. This type of manufacturing has greatly increased the number of new products introduced annually.\"\nWhy (D) — cost-effective production of small quantities is named as the cause.\n(A) Reduced lifetime is a side effect of the proliferation, not its cause.\n(B) Better aggregate forecasting is mentioned as a reason the mismatches are ironic, not as a driver of new products.\n(C) Inventory for end-of-life products is described as expensive, not as newly cheap.\n(E) Forecasting the distribution across SKUs is precisely what the passage says remains difficult.", "easy")
    ] },

  { id: "rc-700-phocids", title: "Passage — Maternal Strategies in Seals", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "Fasting and Foraging Among Pinnipeds", paras: [
      "Until recently, zoologists believed that all species of phocids (true seals), a pinniped family, use a different maternal strategy than do otariids (fur seals and sea lions), another pinniped family. Mother otariids use a foraging strategy. They acquire moderate energy stores in the form of blubber before arriving at breeding sites and then fast for 5 to 11 days after birth. Throughout the rest of the lactation (milk production) period, which lasts from 4 months to 3 years depending on the species, mother otariids alternately forage at sea, where they replenish their fat stores, and nurse their young at breeding sites. Zoologists had assumed that females of all phocid species, by contrast, use a fasting strategy in which mother phocids, having accumulated large energy stores before they arrive at breeding sites, fast throughout the entire lactation period, which lasts from 4 to 50 days depending on the species. However, recent studies on harbor seals, a phocid species, found that lactating females commenced foraging approximately 6 days after giving birth and on average made 7 foraging trips during the remainder of their 24-day lactation period. The maternal strategy evolved by harbor seals may have to do with their small size and the large proportion of their fat stores depleted in lactation. Harbor seals are small compared with other phocid species such as grey seals, northern elephant seals, and hooded seals, all of which are known to fast for the entire lactation period. Studies show that mother seals of these species use respectively 84 percent, 58 percent, and 33 percent of their fat stores during lactation. By comparison, harbor seals use 80 percent of their fat stores in just the first 19 days of lactation, even though they occasionally feed during this period. Since such a large proportion of their fat stores is exhausted despite feeding, mother harbor seals clearly cannot support all of lactation using only energy stored before giving birth. Though smaller than many other phocids, harbor seals are similar in size to most otariids. In addition, there is already some evidence suggesting that the ringed seal, a phocid species that is similar in size to the harbor seal, may also use a maternal foraging strategy." ] },
    questions: [
      Q(1, "Inference", "A", "It can be inferred from the passage that the females of all phocid species differ from the females of all otariid species in that the female phocids",
        ["have shorter lactation periods",
         "consume more food during lactation",
         "consume a higher proportion of fat stores",
         "forage for food occasionally during their lactation periods",
         "deplete a smaller percentage of their fat stores during their lactation periods"],
        "Two numbers are given for each family: how long lactation lasts.",
        "Where to look — otariid lactation lasts \"from 4 months to 3 years depending on the species\"; phocid lactation lasts \"from 4 to 50 days depending on the species.\"\nWhy (A) — even the longest phocid lactation period is far shorter than the shortest otariid one, so this holds for all species of each family.\n(B) Only harbor seals among phocids are reported to feed during lactation, and no comparison of amounts is given.\n(C) Fat depletion varies widely among phocids (84, 58 and 33 percent), so no all-species claim follows.\n(D) Foraging during lactation is exactly what most phocids do [[not]] do.\n(E) Same problem as (C), and with the comparison the wrong way round.", "medium"),
      Q(2, "Supporting detail", "E", "According to the passage, until recently zoologists believed which of the following about all phocid mothers?",
        ["Their fasting periods after giving birth were typically shorter than those of otariids.",
         "Their lactation periods were generally as long as those of comparably sized otariids.",
         "They acquired only moderate energy stores in the form of blubber before arriving at breeding sites.",
         "They depleted less than a third of their stored body fat during lactation.",
         "The replenished their fat stores only after their lactation period ended."],
        "The old belief is the \"fasting strategy\". Spell out what fasting throughout lactation implies.",
        "Where to look — zoologists assumed mother phocids, \"having accumulated large energy stores before they arrive at breeding sites, fast throughout the entire lactation period.\"\nWhy (E) — fasting for the whole lactation period means the fat stores could only be replenished after it ended.\n(A) The comparison runs the other way: otariids fast only 5 to 11 days, phocids for their whole lactation.\n(B) Phocid lactation is described as much shorter, not comparable.\n(C) Moderate energy stores is the otariid pattern; phocids were assumed to accumulate large ones.\n(D) The one-third figure belongs to hooded seals specifically, and is a finding rather than part of the old belief.", "medium"),
      Q(3, "Function / purpose of detail", "E", "The author of the passage mentions ringed seals most probably in order to",
        ["provide an example of a phocid species that fasts throughout its entire lactation period",
         "provide an example of a phocid species whose maternal strategy is typical of phocid species",
         "provide an example of a phocid species that may deplete an even higher proportion of its fat stores during lactation than harbor seals do",
         "support the assertion that harbor seals are smaller than many other phocids",
         "support the assertion that harbor seals’ maternal strategy may be related to their small size"],
        "The ringed seal appears in the final sentence, right after a statement about size.",
        "Where to look — \"Though smaller than many other phocids, harbor seals are similar in size to most otariids. In addition, there is already some evidence suggesting that the ringed seal, a phocid species that is similar in size to the harbor seal, may also use a maternal foraging strategy.\"\nWhy (E) — a second small phocid that also seems to forage supports the idea that the strategy goes with small size.\n(A) The ringed seal is offered as a possible forager, not a faster.\n(B) It is presented as a second exception, not as typical.\n(C) No fat-depletion figure is given for ringed seals.\n(D) That harbor seals are small is stated directly; the ringed seal is brought in for the size-and-strategy link, not to prove the size claim.", "medium")
    ] },

  { id: "rc-700-sanandreas", title: "Passage — Heat in the San Andreas Fault", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "The Missing Frictional Heat", paras: [
      "Prior to 1965 geologists assumed that the two giant rock plates meeting at the San Andreas Fault generate heat through friction as they grind past each other, but in 1965 Henyey found that temperatures in drill holes near the fault were not as elevated as had been expected. Some geologists wondered whether the absence of friction-generated heat could be explained by the kinds of rock composing the fault. Geologists’ pre-1965 assumptions concerning heat generated in the fault were based on calculations about common varieties of rocks, such as limestone and granite; but “weaker” materials, such as clays, had already been identified in samples retrieved from the fault zone. Under normal conditions, rocks composed of clay produce far less friction than do other rock types. In 1992 Byerlee tested whether these materials would produce friction 10 to 15 kilometers below the Earth’s surface. Byerlee found that when clay samples were subjected to the thousands of atmospheres of pressure they would encounter deep inside the Earth, they produced as much friction as was produced by other rock types. The harder rocks push against each other, the hotter they become; in other words, pressure itself, not only the rocks’ properties, affects frictional heating. Geologists therefore wondered whether the friction between the plates was being reduced by pockets of pressurized water within the fault that push the plates away from each other." ] },
    questions: [
      Q(1, "Inference", "A", "The passage suggests which of the following regarding Henyey’s findings about temperature in the San Andreas Fault?",
        ["Scientists have yet to formulate a definitive explanation for Henyey’s findings.",
         "Recent research suggests that Henyey’s explanation for the findings should be modified.",
         "Henyey’s findings had to be recalculated in light of Byerlee’s 1992 experiment.",
         "Henyey’s findings provided support for an assumption long held by geologists.",
         "Scientists have been unable to duplicate Henyey’s findings using more recent experimental methods."],
        "Follow the chain of proposed explanations to where the passage leaves it.",
        "Where to look — the clay explanation was tested by Byerlee and failed, since clays under deep pressure produce as much friction as other rocks; the passage then ends with geologists still \"wondering\" whether pressurized water pockets are responsible.\nWhy (A) — no definitive explanation has been settled on.\n(B) The findings themselves are not being modified; the explanations for them are.\n(C) Nothing suggests Henyey's measurements were recalculated.\n(D) The findings contradicted the long-held assumption; that is why they were unexpected.\n(E) No failure to reproduce the findings is reported.", "medium"),
      Q(2, "Main idea / primary purpose", "B", "The passage is primarily concerned with",
        ["evaluating a method used to test a particular scientific hypothesis",
         "discussing explanations for an unexpected scientific finding",
         "examining the assumptions underlying a particular experiment",
         "questioning the validity of a scientific finding",
         "presenting evidence to support a recent scientific hypothesis"],
        "The passage opens with a surprise and then works through candidate causes.",
        "The shape of the passage — temperatures near the fault were lower than expected; perhaps the rock type explains it; Byerlee's test removed that possibility; perhaps pressurized water does.\nWhy (B) — discussing explanations for an unexpected scientific finding.\n(A) Byerlee's method is reported, not evaluated.\n(C) The assumptions behind the pre-1965 calculations are mentioned once, in passing.\n(D) Henyey's finding is taken as sound throughout.\n(E) No hypothesis is supported; the last one is still an open question.", "easy"),
      Q(3, "Inference", "D", "The passage most strongly suggests that Henyey’s findings about temperature in the San Andreas Fault made the greatest contribution in that they",
        ["revealed an error in previous measurements of temperature in the San Andreas Fault zone",
         "indicated the types of clay present in the rocks that form the San Andreas Fault",
         "established the superiority of a particular technique for evaluating data concerning friction in the San Andreas Fault",
         "suggested that geologists had inaccurately assumed that giant rock plates that meet at the San Andreas Fault generate heat through friction",
         "confirmed geologists’ assumptions about the amount of friction generated by common varieties of rocks, such as limestone and granite"],
        "Henyey measured temperature and found it low. What did that overturn?",
        "Where to look — \"Prior to 1965 geologists assumed that the two giant rock plates meeting at the San Andreas Fault generate heat through friction ... but in 1965 Henyey found that temperatures in drill holes near the fault were not as elevated as had been expected.\"\nWhy (D) — the contribution was to cast doubt on that assumption about frictional heating.\n(A) No earlier temperature measurements are mentioned to have been in error.\n(B) The clay in the fault zone had already been identified in retrieved samples.\n(C) No technique is compared with another.\n(E) The findings undercut the assumption rather than confirming it.", "medium")
    ] },

  { id: "rc-700-tawahka", title: "Passage — Rain-Forest Farming and New Technology", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "Who Adopts Agricultural Technology?", paras: [
      "One proposal for preserving rain forests is to promote the adoption of new agricultural technologies, such as improved plant varieties and use of chemical herbicides, which would increase productivity and slow deforestation by reducing demand for new cropland. Studies have shown that farmers in developing countries who have achieved certain levels of education, wealth, and security of land tenure are more likely to adopt such technologies. But these studies have focused on villages with limited land that are tied to a market economy rather than on the relatively isolated, self-sufficient communities with ample land characteristic of rain-forest regions. [[A recent study of the Tawahka people of the Honduran rain forest]] found that farmers with some formal education were more likely to adopt improved plant varieties but less likely to use chemical herbicides and that those who spoke Spanish (the language of the market economy) were more likely to adopt both technologies. Non-land wealth was also associated with more adoption of both technologies, but availability of uncultivated land reduced the incentive to employ the productivity-enhancing technologies. Researchers also measured land-tenure security: in Tawahka society, kinship ties are a more important indicator of this than are legal property rights, so researchers measured it by a household’s duration of residence in its village. They found that longer residence correlated with more adoption of improved plant varieties but less adoption of chemical herbicides." ] },
    questions: [
      Q(1, "Main idea / primary purpose", "D", "The primary purpose of the passage is to",
        ["evaluate the likelihood that a particular proposal, if implemented, would ultimately succeed in achieving its intended result",
         "question the assumption that certain technological innovations are the most effective means of realizing a particular environmental objective",
         "discuss the progress of efforts to encourage a particular traditional society to adopt certain modern agricultural methods",
         "present the results of new research suggesting that previous findings concerning one set of conditions may not be generalizable to another set of conditions",
         "weigh the relative importance of three factors in determining whether a particular strategy will be successful"],
        "Notice what the passage says about the earlier studies before it introduces the Tawahka one.",
        "The shape of the passage — a proposal; earlier studies linking adoption to education, wealth and land tenure; the objection that those studies looked at market-tied villages with limited land rather than isolated, land-rich rain-forest communities; then the Tawahka results, several of which run the other way.\nWhy (D) — new research suggesting the earlier findings may not generalise from one set of conditions to another.\n(A) Whether the proposal would succeed is never judged; only the assumptions behind it are tested.\n(B) The technologies' effectiveness is not questioned — only who will adopt them.\n(C) No programme of encouragement is under way; a study is reported.\n(E) The three factors are examined but never ranked.", "medium"),
      Q(2, "Supporting detail", "C", "According to the passage, the proposal mentioned in the opening sentence is aimed at preserving rain forests by encouraging farmers in rain-forest regions to do each of the following EXCEPT",
        ["adopt new agricultural technologies",
         "grow improved plant varieties",
         "decrease their use of chemical herbicides",
         "increase their productivity",
         "reduce their need to clear new land for cultivation"],
        "Read the opening sentence and list what the proposal actually calls for.",
        "Where to look — the proposal is to promote \"new agricultural technologies, such as improved plant varieties and use of chemical herbicides, which would increase productivity and slow deforestation by reducing demand for new cropland.\"\nWhy (C) — the proposal calls for [[more]] herbicide use, not less, so this is the exception.\n(A) Adopting new agricultural technologies is the proposal itself.\n(B) Improved plant varieties are named as one of the technologies.\n(D) Increased productivity is the stated mechanism.\n(E) Reducing demand for new cropland is the intended result.", "medium"),
      Q(3, "Inference", "A", "The passage suggests that in the study mentioned in the text in bold the method for gathering information about security of land tenure reflects which of the following pairs of assumptions about Tawahka society?",
        ["The security of a household’s land tenure depends on the strength of that household’s kinship ties, and the duration of a household’s residence in its village is an indication of the strength of that household’s kinship ties.",
         "The ample availability of land makes security of land tenure unimportant, and the lack of a need for secure land tenure has made the concept of legal property rights unnecessary.",
         "The strength of a household’s kinship ties is a more reliable indicator of that household’s receptivity to new agricultural technologies than is its quantity of nonland wealth, and the duration of a household’s residence in its village is a more reliable indicator of that household’s security of land tenure than is the strength of its kinship ties.",
         "Security of land tenure based on kinship ties tends to make farmers more receptive to the use of improved plant varieties, and security of land tenure based on long duration of residence in a village tends to make farmers more receptive to the use of chemical herbicides.",
         "A household is more likely to be receptive to the concept of land tenure based on legal property rights if it has easy access to uncultivated land, and a household is more likely to uphold the tradition of land tenure based on kinship ties if it possesses a significant degree of non-land wealth."],
        "The researchers measured land-tenure security by length of residence. Two steps are needed to justify that.",
        "Where to look — \"in Tawahka society, kinship ties are a more important indicator of this than are legal property rights, so researchers measured it by a household's duration of residence in its village.\"\nWhy (A) — the proxy works only if security depends on kinship ties [[and]] length of residence indicates the strength of those ties. Both assumptions are needed for the measurement to make sense.\n(B) The passage treats land-tenure security as important enough to measure, and says nothing about legal property rights being unnecessary.\n(C) This makes residence a better indicator than kinship, which reverses the reasoning: residence is used precisely as a stand-in for kinship.\n(D) These are findings about adoption, not assumptions behind the measurement.\n(E) Neither claim about receptivity to concepts of land tenure appears anywhere.", "hard"),
      Q(4, "Inference", "D", "The findings of the study mentioned in the text in bold, if valid for rain-forest regions in general, suggest that which of the following is an obstacle most likely to be faced by those wishing to promote rain-forest preservation by implementing the proposal mentioned in the opening sentence?",
        ["Lack of legal property rights tends to discourage local farmers from investing the time and resources required to successfully implement new agricultural technologies.",
         "The ability to evaluate the wider economic ramifications of adopting new agricultural technologies depends on a relatively high level of formal education.",
         "Isolation from the market economy tends to restrict local farmers’ access to new agricultural technologies that could help them to increase their productivity.",
         "Ready availability of uncultivated land tends to decrease local farmers’ incentive to adopt new agricultural technologies that would reduce their need to clear new land for cultivation.",
         "Traditions of self-sufficiency and reliance on kinship ties tend to diminish local farmers’ receptivity to new agricultural technologies introduced by people from outside the local community."],
        "The proposal's whole mechanism is reducing the demand for new cropland. Find the finding that clashes with it.",
        "Where to look — \"availability of uncultivated land reduced the incentive to employ the productivity-enhancing technologies.\"\nWhy (D) — rain-forest communities are described as having ample land, so exactly where the proposal is aimed, farmers have least reason to adopt the technologies.\n(A) The study found that kinship-based tenure, not legal rights, is what matters there.\n(B) Formal education raised adoption of improved varieties and lowered herbicide use; no claim about evaluating wider ramifications is made.\n(C) Access to the technologies is not what the study measured; willingness to adopt is.\n(E) Longer residence correlated with [[more]] adoption of improved varieties, so kinship ties do not simply diminish receptivity.", "medium")
    ] },

  { id: "rc-700-travel", title: "Passage — Globalizing a Travel Agency", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "An Alliance Instead of Acquisition", paras: [
      "This passage was excerpted from material published in 1993. Like many other industries, the travel industry is under increasing pressure to expand globally in order to keep pace with its corporate customers, who have globalized their operations in response to market pressure, competitor actions, and changing supplier relations. But it is difficult for service organizations to globalize. Global expansion through acquisition is usually expensive, and expansion through internal growth is time-consuming and sometimes impossible in markets that are not actively growing. Some service industry companies, in fact, regard these traditional routes to global expansion as inappropriate for service industries because of their special need to preserve local responsiveness through local presence and expertise. One travel agency has eschewed the traditional route altogether. A survivor of the changes that swept the travel industry as a result of the deregulation of the airlines in 1978—changes that included dramatic growth in the corporate demand for travel services, as well as extensive restructuring and consolidation within the travel industry—this agency adopted a unique structure for globalization. Rather than expand by attempting to develop its own offices abroad, which would require the development of local travel management expertise sufficient to capture foreign markets, the company solved its globalization dilemma effectively by forging alliances with the best foreign partners it could find. The resulting cooperative alliance of independent agencies now comprises 32 partners spanning 37 countries." ] },
    questions: [
      Q(1, "Inference", "E", "The passage suggests that one of the effects of the deregulation of the airlines was",
        ["a decline in the services available to noncommercial travelers",
         "a decrease in the size of the corporate travel market",
         "a sharp increase in the number of cooperative alliances among travel agencies",
         "increased competition in a number of different service industries",
         "the merging of some companies within the travel industry"],
        "One sentence lists what the 1978 deregulation set off.",
        "Where to look — deregulation brought \"changes that included dramatic growth in the corporate demand for travel services, as well as extensive restructuring and consolidation within the travel industry.\"\nWhy (E) — consolidation within an industry is companies merging.\n(A) Noncommercial travellers are never mentioned.\n(B) Corporate demand grew dramatically; it did not shrink.\n(C) The cooperative alliance described is one agency's novel response, not a general trend attributed to deregulation.\n(D) Only the travel industry is at issue here.", "medium"),
      Q(2, "Function / purpose of detail", "C", "The author discusses a particular travel agency in the passage most likely in order to",
        ["provide evidence of the pressures on the travel industry to globalize",
         "demonstrate the limitations of the traditional routes to global expansion",
         "illustrate an unusual approach to globalizing a service organization",
         "highlight the difficulties confronting travel agencies that attempt to globalize",
         "underscore the differences between the service industry and other industries"],
        "The agency is introduced with \"has eschewed the traditional route altogether\".",
        "Where to look — the agency \"adopted a unique structure for globalization\", forging alliances with foreign partners rather than opening its own offices.\nWhy (C) — it illustrates an unusual approach to globalising a service organisation.\n(A) The pressure to globalise is established before the example and does not need it.\n(B) The traditional routes' limitations are stated in their own right; the agency shows an alternative rather than proving those limits.\n(D) The difficulties are the setup; this agency is the one that overcame them.\n(E) The service-industry contrast is drawn earlier and generally, not through this case.", "easy"),
      Q(3, "Supporting detail", "D", "According to the passage, which of the following is true of the traditional routes to global expansion?",
        ["They have been supplanted in most service industries by alternative routes.",
         "They are less attractive to travel agencies since deregulation of the airlines.",
         "They may represent the most cost-effective means for a travel agency to globalize.",
         "They may be unsuitable for service agencies that are attempting to globalize.",
         "They are most likely to succeed in markets that are not actively growing."],
        "Look for what \"some service industry companies\" think of acquisition and internal growth.",
        "Where to look — some service companies \"regard these traditional routes to global expansion as inappropriate for service industries because of their special need to preserve local responsiveness through local presence and expertise.\"\nWhy (D) — they may be unsuitable for service organisations trying to globalise.\n(A) Nothing says they have been supplanted in most service industries; one agency avoided them.\n(B) Deregulation is not linked to how attractive those routes are.\n(C) Acquisition is called expensive, so cost-effectiveness is the opposite of what is claimed.\n(E) Internal growth is described as sometimes impossible in markets that are not actively growing.", "medium")
    ] },

  { id: "rc-700-downsizing", title: "Passage — Downsizing as a Business Myth", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "Why Firms Keep Downsizing", paras: [
      "Firms traditionally claim that they downsize (i.e., make permanent personnel cuts) for economic reasons, laying off supposedly unnecessary staff in an attempt to become more efficient and competitive. Organization theory would explain this reasoning as an example of the “economic rationality” that it assumes underlies all organizational activities. There is evidence that firms believe they are behaving rationally whenever they downsize; yet recent research has shown that the actual economic effects of downsizing are often negative for firms. Thus, organization theory cannot adequately explain downsizing; non-economic factors must also be considered. One such factor is the evolution of downsizing into a powerful business myth: managers simply believe that downsizing is efficacious. Moreover, downsizing nowadays is greeted favorably by the business press; the press often refers to soaring stock prices of downsizing firms (even though research shows that stocks usually rise only briefly after downsizing and then suffer a prolonged decline). Once viewed as a sign of desperation, downsizing is now viewed as a signal that firms are serious about competing in the global marketplace; such signals are received positively by key actors— financial analysts, consultants, shareholders—who supply firms with vital organizing resources. Thus, even if downsizers do not become economically more efficient, downsizing’s mythic properties give them added prestige in the business community, enhancing their survival prospects." ] },
    questions: [
      Q(1, "Supporting detail", "E", "According to the passage, the “key actors” view a firm’s downsizing activities as an indication of the firm’s",
        ["troubled financial condition",
         "inability to develop effective long-term strategies",
         "inability to retain vital organizational resources",
         "desire to boost its stock price",
         "desire to become more competitive"],
        "Find the sentence naming the key actors and say what signal they are receiving.",
        "Where to look — downsizing \"is now viewed as a signal that firms are serious about competing in the global marketplace; such signals are received positively by key actors.\"\nWhy (E) — the actors read downsizing as evidence of a desire to compete.\n(A) That is the older view the passage says has been left behind.\n(B) Long-term strategy is never mentioned.\n(C) The actors [[supply]] organizing resources; nothing says the firm cannot retain them.\n(D) The stock-price effect is reported by the business press, not offered as what the actors infer about motive.", "easy"),
      Q(2, "Inference", "D", "The passage suggests which of the following about the claim that a firm will become more efficient and competitive by downsizing?",
        ["Few firms actually believe this claim to be true.",
         "Fewer firms have been making this claim in recent years.",
         "This claim contradicts the basic assumption of organization theory.",
         "This claim is called into question by certain recent research.",
         "This claim is often treated with skepticism by the business press."],
        "The claim is the firms' own justification. What does the passage say about how it holds up?",
        "Where to look — \"recent research has shown that the actual economic effects of downsizing are often negative for firms.\"\nWhy (D) — that research calls the efficiency-and-competitiveness claim into question.\n(A) The passage says there is evidence firms believe they are behaving rationally.\n(B) No trend in how often the claim is made is described.\n(C) The claim fits organization theory's assumption of economic rationality; it is the [[results]] that do not.\n(E) The business press greets downsizing favourably.", "medium"),
      Q(3, "Inference", "B", "The passage suggests that downsizing’s mythic properties can be beneficial to a downsizing firm because these properties",
        ["allow the firm to achieve significant operating efficiencies",
         "provide the firm with access to important organizing resources",
         "encourage a long-term increase in the firm’s stock price",
         "make the firm less reliant on external figures such as financial analysts and consultants",
         "discourage the firm’s competitors from entering the global marketplace"],
        "Trace what the mythic properties actually get the firm.",
        "Where to look — positive signals \"are received positively by key actors—financial analysts, consultants, shareholders—who supply firms with vital organizing resources\", so downsizing's mythic properties give firms prestige and enhance their survival prospects.\nWhy (B) — the benefit runs through access to those organizing resources.\n(A) The passage says the economic effects are often negative, so operating efficiencies are precisely what is not delivered.\n(C) Stocks rise only briefly and then suffer a prolonged decline.\n(D) The mechanism makes the firm [[more]] dependent on analysts and consultants, not less.\n(E) Competitors' entry into the global marketplace is never discussed.", "medium")
    ] },

  { id: "rc-700-seamstresses", title: "Passage — The Parisian Seamstresses’ Guild", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "Guild Status and the Patriarchal Family", paras: [
      "In 1675, Louis XIV established the Parisian seamstresses’ guild, the first independent all-female guild created in over 200 years. Guild members could make and sell women’s and children’s clothing, but were prohibited from producing men’s clothing or dresses for court women. Tailors resented the ascension of seamstresses to guild status; seamstresses, meanwhile, were impatient with the remaining restrictions on their right to clothe women. The conflict between the guilds was not purely economic, however. A 1675 police report indicated that since so many seamstresses were already working illegally, the tailors were unlikely to suffer additional economic damage because of the seamstresses’ incorporation. Moreover, guild membership held very different meanings for tailors and seamstresses. To the tailors, their status as guild members overlapped with their role as heads of household, and entitled them to employ as seamstresses female family members who did not marry outside the trade. The seamstresses, however, viewed guild membership as a mark of independence from the patriarchal family. Their guild was composed not of family units but of individual women who enjoyed unusual legal and economic privileges. At the conflict’s center was the issue of whether tailors’ female relatives should be identified as family members protected by the tailors’ guild or as individuals under the jurisdiction of the seamstresses’ guild." ] },
    questions: [
      Q(1, "Main idea / primary purpose", "B", "The primary purpose of the passage is to",
        ["outline a scholarly debate over the impact of the Parisian seamstresses’ guild",
         "summarize sources of conflict between the newly created Parisian seamstresses’ guild and the tailors’ guild",
         "describe opposing views concerning the origins of the Parisian seamstresses’ guild",
         "explore the underlying reasons for establishing an exclusively female guild in seventeenth-century Paris",
         "correct a misconception about changes in seamstresses’ economic status that took place in Paris in the late seventeenth century"],
        "The passage names two kinds of grievance and then says the conflict was not purely economic.",
        "The shape of the passage — the guild is created; tailors resent it and seamstresses chafe at the remaining limits; the police report shows the economic damage was slight; the two groups understood guild membership quite differently; the dispute centred on how tailors' female relatives should be classified.\nWhy (B) — summarising the sources of conflict between the new guild and the tailors' guild.\n(A) No scholarly debate is reported; the passage speaks in its own voice.\n(C) The guild's origin is given in one clause and not disputed.\n(D) Louis XIV's reasons for creating it are never explored.\n(E) No misconception is corrected.", "easy"),
      Q(2, "Supporting detail", "A", "According to the passage, one source of dissatisfaction for Parisian seamstresses after the establishment of the seamstresses’ guild was that",
        ["seamstresses were not allowed to make and sell clothing for all women",
         "tailors continued to have the exclusive legal right to clothe men",
         "seamstresses who were relatives of tailors were prevented from becoming members of the seamstresses’ guild",
         "rivalry between individual seamstresses increased, thus hindering their ability to compete with the tailors for business",
         "seamstresses were not allowed to accept male tailors as members of the guild"],
        "The seamstresses were \"impatient with the remaining restrictions on their right to clothe women\".",
        "Where to look — guild members could make women's and children's clothing \"but were prohibited from producing men's clothing or dresses for court women.\"\nWhy (A) — court women were off limits, so seamstresses could not clothe all women.\n(B) The bar on men's clothing existed, but the passage locates the seamstresses' impatience in the limits on clothing [[women]].\n(C) Nothing says tailors' relatives were barred from the seamstresses' guild; the dispute was over which guild claimed them.\n(D) Rivalry among individual seamstresses is never mentioned.\n(E) Male membership of the seamstresses' guild is not discussed.", "easy"),
      Q(3, "Inference", "D", "It can be inferred from the passage that which of the following was true of seamstresses employed by relatives who were members of the tailors’ guild?",
        ["They were instrumental in convincing Louis XIV to establish the seamstresses’ guild.",
         "They were rarely allowed to assist master tailors in the production of men’s clothing.",
         "They were considered by some tailors to be a threat to the tailors’ monopoly.",
         "They did not enjoy the same economic and legal privileges that members of the seamstresses’ guild enjoyed.",
         "They felt their status as working women gave them a certain degree of independence from the patriarchal family."],
        "Compare what guild membership gave the seamstresses with the position of a tailor's employed relative.",
        "Where to look — the seamstresses' guild \"was composed not of family units but of individual women who enjoyed unusual legal and economic privileges\", while tailors were entitled to employ their unmarried female relatives as seamstresses under their own guild status.\nWhy (D) — a relative working under the tailors' guild was covered as a family member, not as an individual with those privileges.\n(A) No role in the guild's creation is attributed to them.\n(B) What work they did for master tailors is not described.\n(C) The tailors saw them as family members to protect, not as a threat.\n(E) Independence from the patriarchal family is the seamstress guild members' view, and these women were inside that family structure.", "medium"),
      Q(4, "Function / purpose of detail", "A", "The author mentions the seamstresses’ view of guild membership as a “mark of independence from the patriarchal family” primarily in order to",
        ["emphasize that the establishment of the seamstresses’ guild had implications that were not solely economic",
         "illustrate the conflict that existed between tailors and their female family members over membership in the tailors’ guild",
         "imply that the establishment of the seamstresses’ guild ushered in a period of increased economic and social freedom for women in France",
         "provide an explanation for the dramatic increase in the number of women working as seamstresses after 1675",
         "indicate that members of the seamstresses’ guild were financially more successful than were tailors’ female relatives protected by the tailors’ guild"],
        "The phrase appears right after \"The conflict between the guilds was not purely economic, however.\"",
        "Where to look — the police report shows little economic damage, and the passage then contrasts what guild membership meant to each side, quoting the seamstresses' view of it as a mark of independence from the patriarchal family.\nWhy (A) — it supports the point that the significance of the guild was not solely economic.\n(B) The conflict described is between the two guilds over how to classify these women, not between tailors and their relatives.\n(C) No broader gain in freedom for French women is claimed.\n(D) No increase in the number of seamstresses after 1675 is reported.\n(E) Relative financial success of the two groups is never compared.", "medium")
    ] },

  { id: "rc-700-hopi", title: "Passage — Hopi Social Flexibility", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "Why Hopi Society Held Together", paras: [
      "Anthropologists studying the Hopi people of the southwestern United States often characterize Hopi society between 1680 and 1880 as surprisingly stable, considering that it was a period of diminution in population and pressure from contact with outside groups, factors that might be expected to cause significant changes in Hopi social arrangements. [[The Hopis’ retention of their distinctive socio-cultural system has been attributed to the Hopi religious elite’s determined efforts to preserve their religion and way of life, and also to a geographical isolation greater than that of many other Native American groups, an isolation that limited both cultural contact and exposure to European diseases.]] But equally important to Hopi cultural persistence may have been an inherent flexibility in their social system that may have allowed preservation of traditions even as the Hopis accommodated themselves to change. For example, the system of matrilineal clans was maintained throughout this period, even though some clans merged to form larger groups while others divided into smaller descent groups. Furthermore, although traditionally members of particular Hopi clans appear to have exclusively controlled particular ceremonies, a clan’s control of a ceremony might shift to another clan if the first became too small to manage the responsibility. Village leadership positions traditionally restricted to members of one clan might be similarly extended to members of other clans, and women might assume such positions under certain unusual conditions." ] },
    questions: [
      Q(1, "Inference", "E", "The author of the passage would be most likely to agree with which of the following statements about the explanation outlined in the text in bold?",
        ["It fails to take into account the effect of geographical circumstances on Hopi culture.",
         "It correctly emphasizes the role of the religious elite in maintaining the system of matrilineal clans.",
         "It represents a misreading of Hopi culture because it fails to take into account the actual differences that existed among the various Hopi clans.",
         "It underestimates the effect on Hopi cultural development of contact with other cultural groups.",
         "It is correct but may be insufficient in itself to explain Hopi socio-cultural persistence."],
        "The word after the bolded explanation is \"But\". That signals the author's own position.",
        "Where to look — \"But equally important to Hopi cultural persistence may have been an inherent flexibility in their social system.\"\nWhy (E) — \"equally important\" accepts the bolded explanation while saying it does not do the whole job on its own.\n(A) Geographical isolation is part of the bolded explanation, so it is taken into account.\n(B) The religious elite is credited with preserving religion and way of life, not with maintaining the clan system.\n(C) No misreading is alleged; the author adds to the account rather than rejecting it.\n(D) Contact with other groups appears as one of the pressures, and its effect is never said to be underestimated.", "medium"),
      Q(2, "Inference", "C", "Which of the following can be inferred from the passage about the Hopis’ geographic situation between 1680 and 1880?",
        ["It prevented the Hopis from experiencing a diminution in population.",
         "It helped to promote flexibility within their social system.",
         "It limited but did not eliminate contact with other cultural groups.",
         "It reinforced the religious elite’s determination to resist cultural change.",
         "It tended to limit contact between certain Hopi clans."],
        "One clause describes what the isolation did to contact.",
        "Where to look — \"a geographical isolation greater than that of many other Native American groups, an isolation that limited both cultural contact and exposure to European diseases.\"\nWhy (C) — limited, which implies reduced rather than eliminated; and the passage goes on to describe pressure from contact with outside groups.\n(A) The period is described as one of diminution in population, so the isolation did not prevent it.\n(B) The flexibility is called inherent in the social system, not a product of geography.\n(D) No link between isolation and the elite's determination is drawn.\n(E) Contact between Hopi clans is not discussed; clans merged and divided freely.", "easy"),
      Q(3, "Main idea / primary purpose", "D", "The passage is primarily concerned with",
        ["reassessing a phenomenon in light of new findings",
         "assessing the relative importance of two factors underlying a phenomenon",
         "examining the assumptions underlying an interpretation of a phenomenon",
         "expanding on an explanation of a phenomenon",
         "contrasting two methods for evaluating a phenomenon"],
        "The author accepts the existing account and then adds to it.",
        "The shape of the passage — a surprising stability; the explanation usually given for it; then \"But equally important ... may have been an inherent flexibility\", followed by three examples of that flexibility.\nWhy (D) — expanding on an explanation of a phenomenon.\n(A) No new findings are introduced; the author reasons from familiar material.\n(B) The two factors are called equally important, so no ranking is attempted.\n(C) The assumptions behind the existing interpretation are never examined.\n(E) No methods are compared, and nothing is evaluated.", "medium")
    ] },

  { id: "rc-700-lepidoptera", title: "Passage — Population Cycles in Lepidoptera", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "Hunting the Driving Force", paras: [
      "A small number of the forest species of lepidoptera (moths and butterflies, which exist as caterpillars during most of their life cycle) exhibit regularly recurring patterns of population growth and decline— such fluctuations in population are known as population cycles. Although many different variables influence population levels, a regular pattern such as a population cycle seems to imply a dominant, driving force. Identification of that driving force, however, has proved surprisingly elusive despite considerable research. The common approach of studying causes of population cycles by measuring the mortality caused by different agents, such as predatory birds or parasites, has been unproductive in the case of lepidoptera. Moreover, population ecologists’ attempts to alter cycles by changing the caterpillars’ habitat and by reducing caterpillar populations have not succeeded. In short, [[the evidence implies that these insect populations, if not self-regulating, may at least be regulated by an agent more intimately connected with the insect than are predatory birds or parasites]]. Recent work suggests that this agent may be a virus. For many years, viral disease had been reported in declining populations of caterpillars, but population ecologists had usually considered viral disease to have contributed to the decline once it was underway rather than to have initiated it. The recent work has been made possible by new techniques of molecular biology that allow viral DNA to be detected at low concentrations in the environment. Nuclear polyhedrosis viruses are hypothesized to be the driving force behind population cycles in lepidoptera in part because the viruses themselves follow an infectious cycle in which, if protected from direct sun light, they may remain virulent for many years in the environment, embedded in durable crystals of polyhedrin protein. Once ingested by a caterpillar, the crystals dissolve, releasing the virus to infect the insect’s cells. Late in the course of the infection, millions of new virus particles are formed and enclosed in polyhedrin crystals. These crystals reenter the environment after the insect dies and decomposes, thus becoming available to infect other caterpillars.",
      "One of the attractions of this hypothesis is its broad applicability. Remarkably, despite significant differences in habitat and behavior, many species of lepidoptera have population cycles of similar length, between eight and eleven years. Nuclear polyhedrosis viral infection is one factor these disparate species share." ] },
    questions: [
      Q(1, "Inference", "B", "Which of the following, if true, would most weaken the author’s conclusion in the text in bold?",
        ["New research reveals that the number of species of birds and parasites that prey on lepidoptera has dropped significantly in recent years.",
         "New experiments in which the habitats of lepidoptera are altered in previously untried ways result in the shortening of lepidoptera population cycles.",
         "Recent experiments have revealed that the nuclear polyhedrosis virus is present in a number of predators and parasites of lepidoptera.",
         "Differences among the habitats of lepidoptera species make it difficult to assess the effects of weather on lepidoptera population cycles.",
         "Viral disease is typically observed in a large proportion of the Lepidoptera population."],
        "The bolded conclusion says the regulating agent is [[internal]] to the insect. Find what would put an external agent back in play.",
        "Where to look — the conclusion rests on two failures: measuring mortality from predators and parasites was unproductive, and attempts to alter cycles by changing habitat and reducing populations did not succeed.\nWhy (B) — if new habitat manipulations do shorten the cycles, then an external, environmental factor can drive them after all, and the reason for looking inside the insect collapses.\n(A) Fewer predator species does not show that predators regulate the cycles.\n(C) Finding the virus in predators and parasites is consistent with a virus-driven cycle.\n(D) Difficulty assessing weather effects leaves the conclusion untouched.\n(E) Widespread viral disease supports an agent intimately connected with the insect.", "hard"),
      Q(2, "Inference", "A", "It can be inferred from the passage that the mortality caused by agents such as predatory birds or parasites was measured in an attempt to",
        ["develop an explanation for the existence of lepidoptera population cycles",
         "identify behavioral factors in lepidoptera that affect survival rates",
         "identify possible methods for controlling lepidoptera population growth",
         "provide evidence that lepidoptera populations are self-regulating",
         "determine the life stages of lepidoptera at which mortality rates are highest"],
        "The mortality measurements are introduced as \"the common approach of studying causes of population cycles\".",
        "Where to look — \"The common approach of studying causes of population cycles by measuring the mortality caused by different agents, such as predatory birds or parasites, has been unproductive.\"\nWhy (A) — the measurements were made in order to explain why the cycles occur.\n(B) Behaviour is not what mortality measurement addresses.\n(C) Controlling the populations is not the stated aim; identifying the driving force is.\n(D) Self-regulation is a possibility the failure of that approach suggests, not what the measuring was designed to show.\n(E) Life stages are never brought into it.", "medium"),
      Q(3, "Main idea / primary purpose", "C", "The primary purpose of the passage is to",
        ["describe the development of new techniques that may help to determine the driving force behind population cycles in lepidoptera",
         "present evidence that refutes a particular theory about the driving force behind population cycles in lepidoptera",
         "present a hypothesis about the driving force behind population cycles in lepidoptera",
         "describe the fluctuating patterns of population cycles in Lepidoptera",
         "question the idea that a single driving force is behind population cycles in lepidoptera"],
        "The second half of the passage is given over to one candidate explanation.",
        "The shape of the passage — a regular cycle implies a driving force; the usual candidates have not worked; recent work suggests a virus, and the mechanism and its broad applicability are then set out.\nWhy (C) — presenting a hypothesis about the driving force.\n(A) The new molecular techniques get one sentence, as what made the work possible.\n(B) No theory is refuted; earlier approaches are described as unproductive rather than disproved.\n(D) The cycles are described briefly at the start as the thing to be explained.\n(E) The passage assumes a dominant driving force and goes looking for it.", "easy"),
      Q(4, "Supporting detail", "D", "According to the passage, before the discovery of new techniques for detecting viral DNA, population ecologists believed that viral diseases",
        ["were not widely prevalent among insect populations generally",
         "affected only the caterpillar life stage of lepidoptera",
         "were the driving force behind lepidoptera population cycles",
         "attacked already declining caterpillar populations",
         "infected birds and parasites that prey on various species of lepidoptera"],
        "What did ecologists think viral disease was doing before the new techniques arrived?",
        "Where to look — \"population ecologists had usually considered viral disease to have contributed to the decline once it was underway rather than to have initiated it.\"\nWhy (D) — the viruses were taken to attack populations that were already declining.\n(A) Viral disease had been reported for many years, so its prevalence was not in doubt.\n(B) No restriction to the caterpillar stage is described in that earlier view.\n(C) That the virus drives the cycles is the new hypothesis, not the old belief.\n(E) Infection of birds and parasites is never mentioned.", "medium")
    ] },

  { id: "rc-700-birds", title: "Passage — Did Birds Evolve from Theropods?", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "Answering the Skeptics", paras: [
      "Although many lines of evidence indicate that birds evolved from ground-dwelling theropod dinosaurs, some scientists remain unconvinced. They argue that theropods appeared too late to have given rise to birds, noting that Archaeopteryx lithographica—the oldest known bird—appears in the fossil record about 150 million years ago, whereas the fossil remains of various nonavian maniraptor theropods—the closest known relatives of birds—date only to about 115 million years ago. But investigators have now uncovered bones that evidently belong to nonavian maniraptors dating to the time of Archaeopteryx. In any case, failure to find fossils of a predicted kind does not rule out their existence in an undiscovered deposit. Skeptics also argue that the fused clavicles (the “wishbone”) of birds differ from the unfused clavicles of theropods. This objection was reasonable when only early theropod clavicles had been discovered, but fossilized theropod clavicles that look just like the wishbone of Archaeopteryx have now been unearthed. Finally, some scientists argue that the complex lungs of birds could not have evolved from theropod lungs, an assertion that cannot be supported or falsified at the moment, because no fossil lungs are preserved in the paleontological record." ] },
    questions: [
      Q(1, "Inference", "C", "In the context of the passage, the phrase “fossils of a predicted kind” most likely refers to which of the following?",
        ["Theropod fossils with fused clavicles",
         "Theropod fossils that are similar in structure to Archaeopteryx fossils",
         "Theropod fossils dating back more than 150 million years",
         "Fossils indicating the structure of theropod lungs",
         "Fossils indicating the structure of Archaeopteryx lungs"],
        "The phrase follows the point about maniraptor bones now found at Archaeopteryx's date.",
        "Where to look — skeptics said theropods appeared too late; investigators then found maniraptor bones dating to the time of Archaeopteryx, about 150 million years ago; \"In any case, failure to find fossils of a predicted kind does not rule out their existence in an undiscovered deposit.\"\nWhy (C) — the fossils predicted by the theory are theropod fossils old enough to precede Archaeopteryx, so from more than 150 million years ago.\n(A) Fused theropod clavicles concern the second objection, and those fossils have already been found.\n(B) Structural similarity to Archaeopteryx is the clavicle point, again already settled.\n(D) and (E) Fossil lungs are the third objection, raised after this sentence.", "medium"),
      Q(2, "Supporting detail", "D", "Which of the following is mentioned in the passage as an argument made by scientists who are unconvinced that birds evolved from theropod dinosaurs?",
        ["There are no known theropod dinosaur fossils dating from a period after the time of Archaeopteryx.",
         "There are no known theropod dinosaur fossils that indicate the structure of those dinosaurs’ lungs.",
         "Theropod dinosaurs appear in the fossil record about 150 million years ago.",
         "Theropod dinosaurs did not have fused clavicles.",
         "Theropod dinosaurs had certain bones that look just like those of Archaeopteryx."],
        "Three skeptical arguments are given. Find the one an answer choice states correctly.",
        "Where to look — \"Skeptics also argue that the fused clavicles (the \"wishbone\") of birds differ from the unfused clavicles of theropods.\"\nWhy (D) — the skeptics' claim is exactly that theropods did not have fused clavicles.\n(A) The skeptics' complaint was that maniraptor theropods appeared too [[late]], not that none postdate Archaeopteryx.\n(B) The lung objection is that bird lungs are too complex to have evolved from theropod lungs; the absence of fossil lungs is the author's observation about why it cannot be settled.\n(C) 150 million years ago is when Archaeopteryx appears, not the theropods.\n(E) Theropod clavicles resembling Archaeopteryx's is the evidence [[against]] the skeptics.", "easy")
    ] },

  { id: "rc-700-episodic", title: "Passage — Episodic Memory in Scrub Jays", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "What, Where and When", paras: [
      "The term “episodic memory” was introduced by Tulving to refer to what he considered a uniquely human capacity—the ability to recollect specific past events, to travel back into the past in one’s own mind—as distinct from the capacity simply to use information acquired through past experiences. Subsequently, Clayton et al. developed criteria to test for episodic memory in animals. According to these criteria, episodic memories are not of individual bits of information; they involve multiple components of a single event “bound” together. Clayton sought to examine evidence of scrub jays’ accurate memory of “what,”“where,” and “when” information and their binding of this information. In the wild, these birds store food for retrieval later during periods of food scarcity. Clayton’s experiment required jays to remember the type, location, and freshness of stored food based on a unique learning event. Crickets were stored in one location and peanuts in another. Jays prefer crickets, but crickets degrade more quickly. Clayton’s birds switched their preference from crickets to peanuts once the food had been stored for a certain length of time, showing that they retain information about the what, the where, and the when. Such experiments cannot, however, reveal whether the birds were re-experiencing the past when retrieving the information. Clayton acknowledged this by using the term “episodic-like” memory." ] },
    questions: [
      Q(1, "Main idea / primary purpose", "B", "The primary purpose of the passage is to",
        ["explain how the findings of a particular experiment have been interpreted and offer an alternative interpretation",
         "describe a particular experiment and point out one of its limitations",
         "present similarities between human memory and animal memory",
         "point out a flaw in the argument that a certain capacity is uniquely human",
         "account for the unexpected behavior of animal subjects in a particular experiment"],
        "The last two sentences do something to the experiment just described.",
        "The shape of the passage — Tulving's term and criteria; Clayton's test; the scrub jays' switch from crickets to peanuts, showing what, where and when bound together; then \"Such experiments cannot, however, reveal whether the birds were re-experiencing the past\", which is why Clayton says \"episodic-like\".\nWhy (B) — describing a particular experiment and pointing out one of its limitations.\n(A) No alternative interpretation of the findings is offered.\n(C) Human and animal memory are not compared feature by feature.\n(D) The limitation preserves rather than undermines the claim that true episodic memory may be uniquely human.\n(E) The jays behaved as predicted; nothing was unexpected.", "medium"),
      Q(2, "Supporting detail", "C", "According to the passage, Clayton’s experiment depended on the fact that scrub jays",
        ["recall “when” and “where” information more distinctly than “what” information",
         "are not able to retain information about a single past event for an indefinitely long period of time",
         "choose peanuts over crickets when the crickets have been stored for a long period of time",
         "choose crickets over peanuts whenever both are available",
         "prefer peanuts that have been stored for a short period to crickets that have been stored for a short period"],
        "The design turns on a preference that changes with time.",
        "Where to look — \"Jays prefer crickets, but crickets degrade more quickly\", and the birds \"switched their preference from crickets to peanuts once the food had been stored for a certain length of time.\"\nWhy (C) — the experiment depends on jays choosing peanuts once the crickets have been stored long enough.\n(A) No ranking of the three kinds of information by distinctness is given.\n(B) Indefinite retention is not at issue; the test ran over a set period.\n(D) They prefer crickets, but not whenever both are available — that is the whole point of the switch.\n(E) Fresh crickets are the preferred food, so this reverses the preference.", "medium"),
      Q(3, "Inference", "C", "The passage suggests that Clayton’s experiment demonstrated scrub jays’ ability to",
        ["choose different storage places for different kinds of food to minimize the rate at which a food will degrade",
         "unlearn a behavior they use in the wild in order to adapt to laboratory conditions",
         "bind together information about different aspects of a single past event",
         "re-experience a past event in memory and act accordingly",
         "distinguish one learning event from a subsequent learning event"],
        "Clayton's criteria say what episodic memory requires. The experiment shows the birds meeting part of that.",
        "Where to look — episodic memories \"involve multiple components of a single event 'bound' together\", and the switch showed \"that they retain information about the what, the where, and the when.\"\nWhy (C) — binding together information about different aspects of one past event is what the result demonstrates.\n(A) Where each food was stored was set by the experimenter, not chosen by the jays to slow degradation.\n(B) No wild behaviour had to be unlearned; caching is what they do naturally.\n(D) Re-experiencing the past is exactly what the passage says such experiments cannot show.\n(E) The design used a single unique learning event, so no second event was there to distinguish.", "medium"),
      Q(4, "Inference", "A", "It can be inferred from the passage that both Tulving and Clayton would agree with which of the following statements?",
        ["Animals’ abilities to use information about a specific past event are not conclusive evidence of episodic memory.",
         "Animals do not share humans’ abilities to reexperience the past through memory.",
         "The accuracy of animals’ memories is difficult to determine through direct experimentation.",
         "Humans tend to recollect single bits of information more accurately than do animals.",
         "The binding of different kinds of information is not a distinctive feature of episodic memory."],
        "Tulving reserved episodic memory for recollecting an event; Clayton settled on \"episodic-like\".",
        "Where to look — Tulving distinguished recollecting past events from simply using information acquired through past experience; Clayton acknowledged that her experiments cannot show whether the birds re-experienced the past, and so called the memory \"episodic-like\".\nWhy (A) — both are committed to the view that using information about a past event does not by itself establish episodic memory.\n(B) Clayton leaves the question open rather than denying the ability to animals.\n(C) Clayton's experiment measured the accuracy of the jays' memories successfully; what it could not reach was the experience behind them.\n(D) No comparison of humans and animals on single bits of information is made.\n(E) Binding is one of Clayton's criteria, so she would deny this.", "hard")
    ] },

  { id: "rc-700-labor-myths", title: "Passage — Myths About Pay", section: "rc",
    source: "RC Latest 700-800 Level Questions (answers from the companion solutions volume)",
    passage: { title: "Labor Rates Are Not Labor Costs", paras: [
      "Many managers are influenced by dangerous myths about pay that lead to counterproductive decisions about how their companies compensate employees. One such myth is that [[labor rates, the rate per hour paid to workers, are identical with labor costs, the money spent on labor in relation to the productivity of the labor force]]. This myth leads to the assumption that a company can simply lower its labor costs by cutting wages. But labor costs and labor rates are not in fact the same: one company could pay its workers considerably more than another and yet have lower labor costs if that company’s productivity were higher due to the talent of its workforce, the efficiency of its work processes, or other factors. The confusion of costs with rates persists partly because labor rates are a convenient target for managers who want to make an impact on their company’s budgets. Because labor rates are highly visible, managers can easily compare their company’s rates with those of competitors. Furthermore, labor rates often appear to be a company’s most malleable financial variable: cutting wages appears an easier way to control costs than such options as reconfiguring work processes or altering product design.",
      "The myth that labor rates and labor costs are equivalent is supported by business journalists, who frequently confound the two. For example, [[prominent business journals often remark on the “high” cost of German labor, citing as evidence the average amount paid to German workers]]. The myth is also perpetuated by the compensation consulting industry, which has its own incentives to keep such myths alive. First, although some of these consulting firms have recently broadened their practices beyond the area of compensation, their mainstay continues to be advising companies on changing their compensation practices. Suggesting that a company’s performance can be improved in some other way than by altering its pay system may be empirically correct but contrary to the consultants’ interests. Furthermore, changes to the compensation system may appear to be simpler to implement than changes to other aspects of an organization, so managers are more likely to find such advice from consultants palatable. Finally, to the extent that changes in compensation create new problems, the consultants will continue to have work solving the problems that result from their advice." ] },
    questions: [
      Q(1, "Supporting detail", "A", "The passage suggests that the “myth” mentioned in the text in bold persists partly because",
        ["managers find it easier to compare their companies’ labor rates with those of competitors than to compare labor costs",
         "managers tend to assume that labor rates affect their companies’ budgets less than they actually do",
         "managers tend to believe that labor rates can have an impact on the efficiency of their companies’ work processes",
         "the average amount paid to workers differs significantly from one country to another",
         "many companies fail to rely on compensation consultants when making decisions about labor rates"],
        "The passage gives two reasons the confusion persists. One is about ease of comparison.",
        "Where to look — \"Because labor rates are highly visible, managers can easily compare their company's rates with those of competitors.\"\nWhy (A) — the visibility of rates, and the ease of comparing them, is offered as part of why the myth survives.\n(B) The passage says rates are a convenient target for managers who want to affect the budget, which is the opposite of thinking they matter little.\n(C) The efficiency of work processes is named as a factor in labor [[costs]], not as something managers think rates influence.\n(D) The German example illustrates journalists' confusion, not why managers hold the myth.\n(E) Consultants are said to perpetuate the myth, so relying on them less is not the explanation.", "medium"),
      Q(2, "Function / purpose of detail", "D", "The author of the passage mentions business journals in the text in bold primarily in order to",
        ["demonstrate how a particular kind of evidence can be used to support two different conclusions",
         "cast doubt on a particular view about the average amount paid to German workers",
         "suggest that business journalists may have a vested interest in perpetuating a particular view",
         "identify one source of support for a view common among business managers",
         "indicate a way in which a particular myth could be dispelled"],
        "The German example sits in a sentence about who supports the myth.",
        "Where to look — \"The myth ... is supported by business journalists, who frequently confound the two. For example, prominent business journals often remark on the 'high' cost of German labor, citing as evidence the average amount paid to German workers.\"\nWhy (D) — it identifies one source of support for the view managers hold.\n(A) The evidence is used to support one conclusion; no second conclusion is drawn from it.\n(B) The passage does not dispute the figure for German pay; it disputes calling that figure a cost.\n(C) The vested interest is attributed to the consulting industry, not to journalists.\n(E) No way of dispelling the myth is suggested here.", "medium"),
      Q(3, "Inference", "B", "It can be inferred from the passage that the author would be most likely to agree with which of the following statements about compensation?",
        ["A company’s labor costs are not affected by the efficiency of its work processes.",
         "High labor rates are not necessarily inconsistent with the goals of companies that want to reduce costs.",
         "It is more difficult for managers to compare their companies’ labor rates with those of competitors than to compare labor costs.",
         "A company whose labor rates are high is unlikely to have lower labor costs than other companies.",
         "Managers often use information about competitors’ labor costs to calculate those companies’ labor rates."],
        "The author's central distinction: paying more per hour need not mean spending more per unit of output.",
        "Where to look — \"one company could pay its workers considerably more than another and yet have lower labor costs if that company's productivity were higher.\"\nWhy (B) — high labor rates are therefore compatible with the aim of reducing costs.\n(A) Efficiency of work processes is named as one of the things that determines labor costs.\n(C) Reversed: rates are highly visible and easy to compare, which is why managers fasten on them.\n(D) This is exactly the confusion the passage exists to correct.\n(E) Managers are described as comparing rates, and nothing is said about calculating one from the other.", "medium"),
      Q(4, "Inference", "E", "The author of the passage suggests which of the following about the advice that the consulting firms discussed in the passage customarily give to companies attempting to control costs?",
        ["It often fails to bring about the intended changes in companies’ compensation systems.",
         "It has highly influenced views that predominate in prominent business journals.",
         "It tends to result in decreased labor rates but increased labor costs.",
         "It leads to changes in companies’ compensation practices that are less visible than changes to work processes would be.",
         "It might be different if the consulting firms were less narrowly specialized."],
        "Ask why these firms give the advice they do, rather than what happens afterwards.",
        "Where to look — \"their mainstay continues to be advising companies on changing their compensation practices. Suggesting that a company's performance can be improved in some other way than by altering its pay system may be empirically correct but contrary to the consultants' interests.\"\nWhy (E) — the author ties the content of the advice to what the firms sell. Recommending a change to work processes or product design would be against the interest of a firm whose business is compensation, so a firm not confined to compensation work would have no such reason to steer clients towards pay changes.\n(A) The advice does change compensation systems; the passage's complaint is that those changes create fresh problems, not that they fail to happen.\n(B) Journalists' confusion of rates with costs is attributed to the journalists, not to consultants' influence.\n(C) A specific outcome of lower rates and higher costs is never claimed.\n(D) Compensation changes are said to look [[simpler]] to implement than changes to work processes; visibility is claimed of labor rates, not of the changes.", "hard"),
      Q(5, "Supporting detail", "E", "According to the passage, which of the following is true about changes to a company’s compensation system?",
        ["They are often implemented in conjunction with a company’s efforts to reconfigure its work processes.",
         "They have been advocated by prominent business journals as the most direct way for a company to bring about changes in its labor costs.",
         "They are more likely to result in an increase in labor costs than they are to bring about competitive advantages for the company.",
         "They sometimes result in significant cost savings but are likely to create labor-relations problems for the company.",
         "They may seem to managers to be relatively easy to implement compared with other kinds of changes managers might consider."],
        "One clause says how such changes look to managers.",
        "Where to look — \"changes to the compensation system may appear to be simpler to implement than changes to other aspects of an organization, so managers are more likely to find such advice from consultants palatable.\"\nWhy (E) — they may seem relatively easy to implement compared with the alternatives.\n(A) Reconfiguring work processes is offered as the road not taken, not as a companion measure.\n(B) Journals are said to confound rates with costs; they advocate nothing.\n(C) No comparison of cost increases with competitive advantage is made.\n(D) Labor-relations problems are never mentioned; the new problems are left unspecified.", "easy")
    ] }
  ]);
})();
